package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AapassengerforEmployees generated by hbm2java
 */
@Entity
@Table(name = "AAPassengerforEmployees", schema = "dbo", catalog = "FMS4.0")
public class AapassengerforEmployees implements java.io.Serializable {

	private int id;
	private Integer groupId;
	private String empId;
	private Serializable tagId;
	private Serializable firstName;
	private Serializable lastName;
	private Character gender;
	private Integer homeAddressId;
	private Serializable email;
	private String mobileNo;
	private String phoneNo1;
	private String phoneNo2;
	private Boolean smsalert;
	private Boolean emailAlert;
	private Boolean isDeleted;

	public AapassengerforEmployees() {
	}

	public AapassengerforEmployees(int id) {
		this.id = id;
	}

	public AapassengerforEmployees(int id, Integer groupId, String empId, Serializable tagId, Serializable firstName,
			Serializable lastName, Character gender, Integer homeAddressId, Serializable email, String mobileNo,
			String phoneNo1, String phoneNo2, Boolean smsalert, Boolean emailAlert, Boolean isDeleted) {
		this.id = id;
		this.groupId = groupId;
		this.empId = empId;
		this.tagId = tagId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.homeAddressId = homeAddressId;
		this.email = email;
		this.mobileNo = mobileNo;
		this.phoneNo1 = phoneNo1;
		this.phoneNo2 = phoneNo2;
		this.smsalert = smsalert;
		this.emailAlert = emailAlert;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "EmpID", length = 25)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "TagID")
	public Serializable getTagId() {
		return this.tagId;
	}

	public void setTagId(Serializable tagId) {
		this.tagId = tagId;
	}

	@Column(name = "FirstName")
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName")
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "HomeAddressId")
	public Integer getHomeAddressId() {
		return this.homeAddressId;
	}

	public void setHomeAddressId(Integer homeAddressId) {
		this.homeAddressId = homeAddressId;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "MobileNo", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "PhoneNo1", length = 15)
	public String getPhoneNo1() {
		return this.phoneNo1;
	}

	public void setPhoneNo1(String phoneNo1) {
		this.phoneNo1 = phoneNo1;
	}

	@Column(name = "PhoneNo2", length = 15)
	public String getPhoneNo2() {
		return this.phoneNo2;
	}

	public void setPhoneNo2(String phoneNo2) {
		this.phoneNo2 = phoneNo2;
	}

	@Column(name = "SMSAlert")
	public Boolean getSmsalert() {
		return this.smsalert;
	}

	public void setSmsalert(Boolean smsalert) {
		this.smsalert = smsalert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
