package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aapassenger generated by hbm2java
 */
@Entity
@Table(name = "AAPassenger", schema = "dbo", catalog = "FMS4.0")
public class Aapassenger implements java.io.Serializable {

	private int id;
	private Integer groupId;
	private Serializable firstName;
	private Serializable lastName;
	private String empId;
	private Character gender;
	private Integer homeAddressId;
	private Serializable email;
	private String mobileNo;
	private String phoneNo1;
	private String phoneNo2;
	private Boolean smsalert;
	private Boolean emailAlert;
	private String managerId;
	private Serializable tagId;
	private Boolean isDeleted;
	private Serializable createdBy;
	private Date createOn;
	private Serializable modifiedBy;
	private Date modifiedOn;

	public Aapassenger() {
	}

	public Aapassenger(int id, Date createOn) {
		this.id = id;
		this.createOn = createOn;
	}

	public Aapassenger(int id, Integer groupId, Serializable firstName, Serializable lastName, String empId,
			Character gender, Integer homeAddressId, Serializable email, String mobileNo, String phoneNo1,
			String phoneNo2, Boolean smsalert, Boolean emailAlert, String managerId, Serializable tagId,
			Boolean isDeleted, Serializable createdBy, Date createOn, Serializable modifiedBy, Date modifiedOn) {
		this.id = id;
		this.groupId = groupId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.empId = empId;
		this.gender = gender;
		this.homeAddressId = homeAddressId;
		this.email = email;
		this.mobileNo = mobileNo;
		this.phoneNo1 = phoneNo1;
		this.phoneNo2 = phoneNo2;
		this.smsalert = smsalert;
		this.emailAlert = emailAlert;
		this.managerId = managerId;
		this.tagId = tagId;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "FirstName")
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName")
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EmpID", length = 25)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "Gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "HomeAddressId")
	public Integer getHomeAddressId() {
		return this.homeAddressId;
	}

	public void setHomeAddressId(Integer homeAddressId) {
		this.homeAddressId = homeAddressId;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "MobileNo", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "PhoneNo1", length = 15)
	public String getPhoneNo1() {
		return this.phoneNo1;
	}

	public void setPhoneNo1(String phoneNo1) {
		this.phoneNo1 = phoneNo1;
	}

	@Column(name = "PhoneNo2", length = 15)
	public String getPhoneNo2() {
		return this.phoneNo2;
	}

	public void setPhoneNo2(String phoneNo2) {
		this.phoneNo2 = phoneNo2;
	}

	@Column(name = "SMSAlert")
	public Boolean getSmsalert() {
		return this.smsalert;
	}

	public void setSmsalert(Boolean smsalert) {
		this.smsalert = smsalert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "ManagerId", length = 25)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "TagID")
	public Serializable getTagId() {
		return this.tagId;
	}

	public void setTagId(Serializable tagId) {
		this.tagId = tagId;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createOn", nullable = false, length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "modifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
