package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AddressforEmployee generated by hbm2java
 */
@Entity
@Table(name = "AddressforEmployee", schema = "dbo", catalog = "FMS4.0")
public class AddressforEmployee implements java.io.Serializable {

	private int id;
	private int waypointId;
	private Serializable area;
	private Serializable landmark;
	private boolean isdeleted;

	public AddressforEmployee() {
	}

	public AddressforEmployee(int id, int waypointId, boolean isdeleted) {
		this.id = id;
		this.waypointId = waypointId;
		this.isdeleted = isdeleted;
	}

	public AddressforEmployee(int id, int waypointId, Serializable area, Serializable landmark, boolean isdeleted) {
		this.id = id;
		this.waypointId = waypointId;
		this.area = area;
		this.landmark = landmark;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "WaypointID", nullable = false)
	public int getWaypointId() {
		return this.waypointId;
	}

	public void setWaypointId(int waypointId) {
		this.waypointId = waypointId;
	}

	@Column(name = "Area")
	public Serializable getArea() {
		return this.area;
	}

	public void setArea(Serializable area) {
		this.area = area;
	}

	@Column(name = "Landmark")
	public Serializable getLandmark() {
		return this.landmark;
	}

	public void setLandmark(Serializable landmark) {
		this.landmark = landmark;
	}

	@Column(name = "Isdeleted", nullable = false)
	public boolean isIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
