package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AlertAssignToGroups generated by hbm2java
 */
@Entity
@Table(name = "AlertAssignToGroups", schema = "dbo", catalog = "FMS4.0")
public class AlertAssignToGroups implements java.io.Serializable {

	private AlertAssignToGroupsId id;

	public AlertAssignToGroups() {
	}

	public AlertAssignToGroups(AlertAssignToGroupsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "eventTypeId", column = @Column(name = "EventTypeID", nullable = false)),
			@AttributeOverride(name = "alertTypeId", column = @Column(name = "AlertTypeID")),
			@AttributeOverride(name = "threshold", column = @Column(name = "Threshold")),
			@AttributeOverride(name = "phoneNumber", column = @Column(name = "PhoneNumber")),
			@AttributeOverride(name = "email", column = @Column(name = "Email")),
			@AttributeOverride(name = "fromHours", column = @Column(name = "FromHours")),
			@AttributeOverride(name = "fromMinutes", column = @Column(name = "FromMinutes")),
			@AttributeOverride(name = "toHours", column = @Column(name = "ToHours")),
			@AttributeOverride(name = "toMinutes", column = @Column(name = "ToMinutes")),
			@AttributeOverride(name = "fromTime", column = @Column(name = "FromTime", length = 16)),
			@AttributeOverride(name = "toTime", column = @Column(name = "ToTime", length = 16)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupId")),
			@AttributeOverride(name = "createdby", column = @Column(name = "Createdby")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")) })
	public AlertAssignToGroupsId getId() {
		return this.id;
	}

	public void setId(AlertAssignToGroupsId id) {
		this.id = id;
	}

}
