package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AlertMaster1 generated by hbm2java
 */
@Entity
@Table(name = "AlertMaster1", schema = "dbo", catalog = "FMS4.0")
public class AlertMaster1 implements java.io.Serializable {

	private AlertMaster1Id id;

	public AlertMaster1() {
	}

	public AlertMaster1(AlertMaster1Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "alertType", column = @Column(name = "AlertType", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "Description")),
			@AttributeOverride(name = "message", column = @Column(name = "Message", nullable = false)),
			@AttributeOverride(name = "emailSubject", column = @Column(name = "EmailSubject")),
			@AttributeOverride(name = "emailMessage", column = @Column(name = "EmailMessage")),
			@AttributeOverride(name = "smsmessage", column = @Column(name = "SMSMessage")),
			@AttributeOverride(name = "isNotificationRequired", column = @Column(name = "IsNotificationRequired")),
			@AttributeOverride(name = "isPassengerAlert", column = @Column(name = "IsPassengerAlert")),
			@AttributeOverride(name = "paramCount", column = @Column(name = "ParamCount", nullable = false)),
			@AttributeOverride(name = "fmsalertSequnce", column = @Column(name = "FMSAlertSequnce")),
			@AttributeOverride(name = "severityId", column = @Column(name = "SeverityID", nullable = false)),
			@AttributeOverride(name = "alertModeId", column = @Column(name = "AlertModeID", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "ModifiedBy", nullable = false)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted", nullable = false)) })
	public AlertMaster1Id getId() {
		return this.id;
	}

	public void setId(AlertMaster1Id id) {
		this.id = id;
	}

}
