package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlertMaster generated by hbm2java
 */
@Entity
@Table(name = "AlertMaster", schema = "dbo", catalog = "FMS4.0")
public class AlertMaster implements java.io.Serializable {

	private int id;
	private Lookup lookupBySeverityId;
	private Lookup lookupByAlertModeId;
	private Serializable alertType;
	private Serializable description;
	private Serializable message;
	private Serializable emailSubject;
	private Serializable emailMessage;
	private Serializable smsmessage;
	private Boolean isNotificationRequired;
	private Integer isPassengerAlert;
	private int paramCount;
	private Integer fmsalertSequnce;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;
	private Set<AlertAssignToCompanies> alertAssignToCompanieses = new HashSet<AlertAssignToCompanies>(0);

	public AlertMaster() {
	}

	public AlertMaster(int id, Lookup lookupBySeverityId, Lookup lookupByAlertModeId, Serializable alertType,
			Serializable message, int paramCount, Serializable createdBy, Date createdOn, Serializable modifiedBy,
			Date modifiedOn, boolean isDeleted) {
		this.id = id;
		this.lookupBySeverityId = lookupBySeverityId;
		this.lookupByAlertModeId = lookupByAlertModeId;
		this.alertType = alertType;
		this.message = message;
		this.paramCount = paramCount;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	public AlertMaster(int id, Lookup lookupBySeverityId, Lookup lookupByAlertModeId, Serializable alertType,
			Serializable description, Serializable message, Serializable emailSubject, Serializable emailMessage,
			Serializable smsmessage, Boolean isNotificationRequired, Integer isPassengerAlert, int paramCount,
			Integer fmsalertSequnce, Serializable createdBy, Date createdOn, Serializable modifiedBy, Date modifiedOn,
			boolean isDeleted, Set<AlertAssignToCompanies> alertAssignToCompanieses) {
		this.id = id;
		this.lookupBySeverityId = lookupBySeverityId;
		this.lookupByAlertModeId = lookupByAlertModeId;
		this.alertType = alertType;
		this.description = description;
		this.message = message;
		this.emailSubject = emailSubject;
		this.emailMessage = emailMessage;
		this.smsmessage = smsmessage;
		this.isNotificationRequired = isNotificationRequired;
		this.isPassengerAlert = isPassengerAlert;
		this.paramCount = paramCount;
		this.fmsalertSequnce = fmsalertSequnce;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.alertAssignToCompanieses = alertAssignToCompanieses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SeverityID", nullable = false)
	public Lookup getLookupBySeverityId() {
		return this.lookupBySeverityId;
	}

	public void setLookupBySeverityId(Lookup lookupBySeverityId) {
		this.lookupBySeverityId = lookupBySeverityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AlertModeID", nullable = false)
	public Lookup getLookupByAlertModeId() {
		return this.lookupByAlertModeId;
	}

	public void setLookupByAlertModeId(Lookup lookupByAlertModeId) {
		this.lookupByAlertModeId = lookupByAlertModeId;
	}

	@Column(name = "AlertType", nullable = false)
	public Serializable getAlertType() {
		return this.alertType;
	}

	public void setAlertType(Serializable alertType) {
		this.alertType = alertType;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "Message", nullable = false)
	public Serializable getMessage() {
		return this.message;
	}

	public void setMessage(Serializable message) {
		this.message = message;
	}

	@Column(name = "EmailSubject")
	public Serializable getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(Serializable emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "EmailMessage")
	public Serializable getEmailMessage() {
		return this.emailMessage;
	}

	public void setEmailMessage(Serializable emailMessage) {
		this.emailMessage = emailMessage;
	}

	@Column(name = "SMSMessage")
	public Serializable getSmsmessage() {
		return this.smsmessage;
	}

	public void setSmsmessage(Serializable smsmessage) {
		this.smsmessage = smsmessage;
	}

	@Column(name = "IsNotificationRequired")
	public Boolean getIsNotificationRequired() {
		return this.isNotificationRequired;
	}

	public void setIsNotificationRequired(Boolean isNotificationRequired) {
		this.isNotificationRequired = isNotificationRequired;
	}

	@Column(name = "IsPassengerAlert")
	public Integer getIsPassengerAlert() {
		return this.isPassengerAlert;
	}

	public void setIsPassengerAlert(Integer isPassengerAlert) {
		this.isPassengerAlert = isPassengerAlert;
	}

	@Column(name = "ParamCount", nullable = false)
	public int getParamCount() {
		return this.paramCount;
	}

	public void setParamCount(int paramCount) {
		this.paramCount = paramCount;
	}

	@Column(name = "FMSAlertSequnce")
	public Integer getFmsalertSequnce() {
		return this.fmsalertSequnce;
	}

	public void setFmsalertSequnce(Integer fmsalertSequnce) {
		this.fmsalertSequnce = fmsalertSequnce;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", nullable = false)
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", nullable = false, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alertMaster")
	public Set<AlertAssignToCompanies> getAlertAssignToCompanieses() {
		return this.alertAssignToCompanieses;
	}

	public void setAlertAssignToCompanieses(Set<AlertAssignToCompanies> alertAssignToCompanieses) {
		this.alertAssignToCompanieses = alertAssignToCompanieses;
	}

}
