package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlertNotificationStatus generated by hbm2java
 */
@Entity
@Table(name = "AlertNotificationStatus", schema = "dbo", catalog = "FMS4.0")
public class AlertNotificationStatus implements java.io.Serializable {

	private int id;
	private int companyId;
	private int groupId;
	private int notificationId;
	private int alertType;
	private Date alertTime;
	private Serializable vehicleNumber;
	private Double lat;
	private Double long_;
	private Double speed;
	private Serializable action;
	private Serializable reason;
	private boolean isdeleted;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;

	public AlertNotificationStatus() {
	}

	public AlertNotificationStatus(int id, int companyId, int groupId, int notificationId, int alertType,
			Date alertTime, boolean isdeleted, Serializable createdBy, Date createdOn) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.notificationId = notificationId;
		this.alertType = alertType;
		this.alertTime = alertTime;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	public AlertNotificationStatus(int id, int companyId, int groupId, int notificationId, int alertType,
			Date alertTime, Serializable vehicleNumber, Double lat, Double long_, Double speed, Serializable action,
			Serializable reason, boolean isdeleted, Serializable createdBy, Date createdOn, Serializable modifiedBy,
			Date modifiedOn) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.notificationId = notificationId;
		this.alertType = alertType;
		this.alertTime = alertTime;
		this.vehicleNumber = vehicleNumber;
		this.lat = lat;
		this.long_ = long_;
		this.speed = speed;
		this.action = action;
		this.reason = reason;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CompanyID", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "NotificationID", nullable = false)
	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "AlertType", nullable = false)
	public int getAlertType() {
		return this.alertType;
	}

	public void setAlertType(int alertType) {
		this.alertType = alertType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AlertTime", nullable = false, length = 23)
	public Date getAlertTime() {
		return this.alertTime;
	}

	public void setAlertTime(Date alertTime) {
		this.alertTime = alertTime;
	}

	@Column(name = "VehicleNumber")
	public Serializable getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(Serializable vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "lat", precision = 53, scale = 0)
	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "long", precision = 53, scale = 0)
	public Double getLong_() {
		return this.long_;
	}

	public void setLong_(Double long_) {
		this.long_ = long_;
	}

	@Column(name = "Speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Column(name = "Action")
	public Serializable getAction() {
		return this.action;
	}

	public void setAction(Serializable action) {
		this.action = action;
	}

	@Column(name = "Reason")
	public Serializable getReason() {
		return this.reason;
	}

	public void setReason(Serializable reason) {
		this.reason = reason;
	}

	@Column(name = "Isdeleted", nullable = false)
	public boolean isIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
