package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlertMaster1Id generated by hbm2java
 */
@Embeddable
public class AlertMaster1Id implements java.io.Serializable {

	private int id;
	private Serializable alertType;
	private Serializable description;
	private Serializable message;
	private Serializable emailSubject;
	private Serializable emailMessage;
	private Serializable smsmessage;
	private Boolean isNotificationRequired;
	private Integer isPassengerAlert;
	private int paramCount;
	private Integer fmsalertSequnce;
	private int severityId;
	private int alertModeId;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;

	public AlertMaster1Id() {
	}

	public AlertMaster1Id(int id, Serializable alertType, Serializable message, int paramCount, int severityId,
			int alertModeId, Serializable createdBy, Date createdOn, Serializable modifiedBy, Date modifiedOn,
			boolean isDeleted) {
		this.id = id;
		this.alertType = alertType;
		this.message = message;
		this.paramCount = paramCount;
		this.severityId = severityId;
		this.alertModeId = alertModeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	public AlertMaster1Id(int id, Serializable alertType, Serializable description, Serializable message,
			Serializable emailSubject, Serializable emailMessage, Serializable smsmessage,
			Boolean isNotificationRequired, Integer isPassengerAlert, int paramCount, Integer fmsalertSequnce,
			int severityId, int alertModeId, Serializable createdBy, Date createdOn, Serializable modifiedBy,
			Date modifiedOn, boolean isDeleted) {
		this.id = id;
		this.alertType = alertType;
		this.description = description;
		this.message = message;
		this.emailSubject = emailSubject;
		this.emailMessage = emailMessage;
		this.smsmessage = smsmessage;
		this.isNotificationRequired = isNotificationRequired;
		this.isPassengerAlert = isPassengerAlert;
		this.paramCount = paramCount;
		this.fmsalertSequnce = fmsalertSequnce;
		this.severityId = severityId;
		this.alertModeId = alertModeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "AlertType", nullable = false)
	public Serializable getAlertType() {
		return this.alertType;
	}

	public void setAlertType(Serializable alertType) {
		this.alertType = alertType;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "Message", nullable = false)
	public Serializable getMessage() {
		return this.message;
	}

	public void setMessage(Serializable message) {
		this.message = message;
	}

	@Column(name = "EmailSubject")
	public Serializable getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(Serializable emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "EmailMessage")
	public Serializable getEmailMessage() {
		return this.emailMessage;
	}

	public void setEmailMessage(Serializable emailMessage) {
		this.emailMessage = emailMessage;
	}

	@Column(name = "SMSMessage")
	public Serializable getSmsmessage() {
		return this.smsmessage;
	}

	public void setSmsmessage(Serializable smsmessage) {
		this.smsmessage = smsmessage;
	}

	@Column(name = "IsNotificationRequired")
	public Boolean getIsNotificationRequired() {
		return this.isNotificationRequired;
	}

	public void setIsNotificationRequired(Boolean isNotificationRequired) {
		this.isNotificationRequired = isNotificationRequired;
	}

	@Column(name = "IsPassengerAlert")
	public Integer getIsPassengerAlert() {
		return this.isPassengerAlert;
	}

	public void setIsPassengerAlert(Integer isPassengerAlert) {
		this.isPassengerAlert = isPassengerAlert;
	}

	@Column(name = "ParamCount", nullable = false)
	public int getParamCount() {
		return this.paramCount;
	}

	public void setParamCount(int paramCount) {
		this.paramCount = paramCount;
	}

	@Column(name = "FMSAlertSequnce")
	public Integer getFmsalertSequnce() {
		return this.fmsalertSequnce;
	}

	public void setFmsalertSequnce(Integer fmsalertSequnce) {
		this.fmsalertSequnce = fmsalertSequnce;
	}

	@Column(name = "SeverityID", nullable = false)
	public int getSeverityId() {
		return this.severityId;
	}

	public void setSeverityId(int severityId) {
		this.severityId = severityId;
	}

	@Column(name = "AlertModeID", nullable = false)
	public int getAlertModeId() {
		return this.alertModeId;
	}

	public void setAlertModeId(int alertModeId) {
		this.alertModeId = alertModeId;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", nullable = false)
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ModifiedOn", nullable = false, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlertMaster1Id))
			return false;
		AlertMaster1Id castOther = (AlertMaster1Id) other;

		return (this.getId() == castOther.getId())
				&& ((this.getAlertType() == castOther.getAlertType()) || (this.getAlertType() != null
						&& castOther.getAlertType() != null && this.getAlertType().equals(castOther.getAlertType())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getEmailSubject() == castOther.getEmailSubject())
						|| (this.getEmailSubject() != null && castOther.getEmailSubject() != null
								&& this.getEmailSubject().equals(castOther.getEmailSubject())))
				&& ((this.getEmailMessage() == castOther.getEmailMessage())
						|| (this.getEmailMessage() != null && castOther.getEmailMessage() != null
								&& this.getEmailMessage().equals(castOther.getEmailMessage())))
				&& ((this.getSmsmessage() == castOther.getSmsmessage()) || (this.getSmsmessage() != null
						&& castOther.getSmsmessage() != null && this.getSmsmessage().equals(castOther.getSmsmessage())))
				&& ((this.getIsNotificationRequired() == castOther.getIsNotificationRequired())
						|| (this.getIsNotificationRequired() != null && castOther.getIsNotificationRequired() != null
								&& this.getIsNotificationRequired().equals(castOther.getIsNotificationRequired())))
				&& ((this.getIsPassengerAlert() == castOther.getIsPassengerAlert())
						|| (this.getIsPassengerAlert() != null && castOther.getIsPassengerAlert() != null
								&& this.getIsPassengerAlert().equals(castOther.getIsPassengerAlert())))
				&& (this.getParamCount() == castOther.getParamCount())
				&& ((this.getFmsalertSequnce() == castOther.getFmsalertSequnce())
						|| (this.getFmsalertSequnce() != null && castOther.getFmsalertSequnce() != null
								&& this.getFmsalertSequnce().equals(castOther.getFmsalertSequnce())))
				&& (this.getSeverityId() == castOther.getSeverityId())
				&& (this.getAlertModeId() == castOther.getAlertModeId())
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
						&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& (this.isIsDeleted() == castOther.isIsDeleted());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getAlertType() == null ? 0 : this.getAlertType().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getEmailSubject() == null ? 0 : this.getEmailSubject().hashCode());
		result = 37 * result + (getEmailMessage() == null ? 0 : this.getEmailMessage().hashCode());
		result = 37 * result + (getSmsmessage() == null ? 0 : this.getSmsmessage().hashCode());
		result = 37 * result + (getIsNotificationRequired() == null ? 0 : this.getIsNotificationRequired().hashCode());
		result = 37 * result + (getIsPassengerAlert() == null ? 0 : this.getIsPassengerAlert().hashCode());
		result = 37 * result + this.getParamCount();
		result = 37 * result + (getFmsalertSequnce() == null ? 0 : this.getFmsalertSequnce().hashCode());
		result = 37 * result + this.getSeverityId();
		result = 37 * result + this.getAlertModeId();
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (this.isIsDeleted() ? 1 : 0);
		return result;
	}

}
