package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlertLog generated by hbm2java
 */
@Entity
@Table(name = "AlertLog", schema = "dbo", catalog = "FMS4.0")
public class AlertLog implements java.io.Serializable {

	private int id;
	private String vehicleno;
	private Double lat;
	private Double long_;
	private Double speed;
	private Date datetime;
	private String wayPointName;
	private Integer groupid;
	private Integer alerttype;
	private Integer fleetid;
	private Double odometerReading;
	private String probableroutes;
	private String routeName;
	private Date actualDateTime;

	public AlertLog() {
	}

	public AlertLog(int id) {
		this.id = id;
	}

	public AlertLog(int id, String vehicleno, Double lat, Double long_, Double speed, Date datetime,
			String wayPointName, Integer groupid, Integer alerttype, Integer fleetid, Double odometerReading,
			String probableroutes, String routeName, Date actualDateTime) {
		this.id = id;
		this.vehicleno = vehicleno;
		this.lat = lat;
		this.long_ = long_;
		this.speed = speed;
		this.datetime = datetime;
		this.wayPointName = wayPointName;
		this.groupid = groupid;
		this.alerttype = alerttype;
		this.fleetid = fleetid;
		this.odometerReading = odometerReading;
		this.probableroutes = probableroutes;
		this.routeName = routeName;
		this.actualDateTime = actualDateTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Vehicleno", length = 50)
	public String getVehicleno() {
		return this.vehicleno;
	}

	public void setVehicleno(String vehicleno) {
		this.vehicleno = vehicleno;
	}

	@Column(name = "lat", precision = 53, scale = 0)
	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "long", precision = 53, scale = 0)
	public Double getLong_() {
		return this.long_;
	}

	public void setLong_(Double long_) {
		this.long_ = long_;
	}

	@Column(name = "speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 23)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "WayPointName", length = 50)
	public String getWayPointName() {
		return this.wayPointName;
	}

	public void setWayPointName(String wayPointName) {
		this.wayPointName = wayPointName;
	}

	@Column(name = "Groupid")
	public Integer getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	@Column(name = "alerttype")
	public Integer getAlerttype() {
		return this.alerttype;
	}

	public void setAlerttype(Integer alerttype) {
		this.alerttype = alerttype;
	}

	@Column(name = "fleetid")
	public Integer getFleetid() {
		return this.fleetid;
	}

	public void setFleetid(Integer fleetid) {
		this.fleetid = fleetid;
	}

	@Column(name = "odometerReading", precision = 53, scale = 0)
	public Double getOdometerReading() {
		return this.odometerReading;
	}

	public void setOdometerReading(Double odometerReading) {
		this.odometerReading = odometerReading;
	}

	@Column(name = "Probableroutes", length = 200)
	public String getProbableroutes() {
		return this.probableroutes;
	}

	public void setProbableroutes(String probableroutes) {
		this.probableroutes = probableroutes;
	}

	@Column(name = "RouteName", length = 50)
	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualDateTime", length = 23)
	public Date getActualDateTime() {
		return this.actualDateTime;
	}

	public void setActualDateTime(Date actualDateTime) {
		this.actualDateTime = actualDateTime;
	}

}
