package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllocationRequest generated by hbm2java
 */
@Entity
@Table(name = "AllocationRequest", schema = "dbo", catalog = "FMS4.0")
public class AllocationRequest implements java.io.Serializable {

	private int id;
	private int groupId;
	private int passengerId;
	private Integer sourceId;
	private Serializable sourceName;
	private Integer destinationId;
	private Serializable destinationName;
	private Boolean requestType;
	private Date reguestedOn;
	private Date scheduledOn;
	private Date createdOn;
	private Date modifiedOn;
	private Double distance;
	private Double distancePrePoint;
	private Integer direction;
	private Integer statusId;
	private Integer vehicleId;
	private Integer updatedBy;
	private Serializable remarks;
	private Boolean isdeleted;
	private Integer projectType;
	private Boolean tripType;
	private Serializable fromLatLon;
	private Serializable toLatLon;
	private byte[] routeSegment;
	private Date endDate;
	private Serializable managerEmailId;

	public AllocationRequest() {
	}

	public AllocationRequest(int id, int groupId, int passengerId) {
		this.id = id;
		this.groupId = groupId;
		this.passengerId = passengerId;
	}

	public AllocationRequest(int id, int groupId, int passengerId, Integer sourceId, Serializable sourceName,
			Integer destinationId, Serializable destinationName, Boolean requestType, Date reguestedOn,
			Date scheduledOn, Date createdOn, Date modifiedOn, Double distance, Double distancePrePoint,
			Integer direction, Integer statusId, Integer vehicleId, Integer updatedBy, Serializable remarks,
			Boolean isdeleted, Integer projectType, Boolean tripType, Serializable fromLatLon, Serializable toLatLon,
			byte[] routeSegment, Date endDate, Serializable managerEmailId) {
		this.id = id;
		this.groupId = groupId;
		this.passengerId = passengerId;
		this.sourceId = sourceId;
		this.sourceName = sourceName;
		this.destinationId = destinationId;
		this.destinationName = destinationName;
		this.requestType = requestType;
		this.reguestedOn = reguestedOn;
		this.scheduledOn = scheduledOn;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.distance = distance;
		this.distancePrePoint = distancePrePoint;
		this.direction = direction;
		this.statusId = statusId;
		this.vehicleId = vehicleId;
		this.updatedBy = updatedBy;
		this.remarks = remarks;
		this.isdeleted = isdeleted;
		this.projectType = projectType;
		this.tripType = tripType;
		this.fromLatLon = fromLatLon;
		this.toLatLon = toLatLon;
		this.routeSegment = routeSegment;
		this.endDate = endDate;
		this.managerEmailId = managerEmailId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "PassengerID", nullable = false)
	public int getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(int passengerId) {
		this.passengerId = passengerId;
	}

	@Column(name = "SourceID")
	public Integer getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "SourceName")
	public Serializable getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(Serializable sourceName) {
		this.sourceName = sourceName;
	}

	@Column(name = "DestinationID")
	public Integer getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(Integer destinationId) {
		this.destinationId = destinationId;
	}

	@Column(name = "DestinationName")
	public Serializable getDestinationName() {
		return this.destinationName;
	}

	public void setDestinationName(Serializable destinationName) {
		this.destinationName = destinationName;
	}

	@Column(name = "RequestType")
	public Boolean getRequestType() {
		return this.requestType;
	}

	public void setRequestType(Boolean requestType) {
		this.requestType = requestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReguestedOn", length = 23)
	public Date getReguestedOn() {
		return this.reguestedOn;
	}

	public void setReguestedOn(Date reguestedOn) {
		this.reguestedOn = reguestedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ScheduledOn", length = 23)
	public Date getScheduledOn() {
		return this.scheduledOn;
	}

	public void setScheduledOn(Date scheduledOn) {
		this.scheduledOn = scheduledOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Distance", precision = 53, scale = 0)
	public Double getDistance() {
		return this.distance;
	}

	public void setDistance(Double distance) {
		this.distance = distance;
	}

	@Column(name = "DistancePrePoint", precision = 53, scale = 0)
	public Double getDistancePrePoint() {
		return this.distancePrePoint;
	}

	public void setDistancePrePoint(Double distancePrePoint) {
		this.distancePrePoint = distancePrePoint;
	}

	@Column(name = "Direction")
	public Integer getDirection() {
		return this.direction;
	}

	public void setDirection(Integer direction) {
		this.direction = direction;
	}

	@Column(name = "StatusID")
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "VehicleID")
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "UpdatedBy")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "Remarks")
	public Serializable getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Serializable remarks) {
		this.remarks = remarks;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "ProjectType")
	public Integer getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Integer projectType) {
		this.projectType = projectType;
	}

	@Column(name = "TripType")
	public Boolean getTripType() {
		return this.tripType;
	}

	public void setTripType(Boolean tripType) {
		this.tripType = tripType;
	}

	@Column(name = "FromLatLon")
	public Serializable getFromLatLon() {
		return this.fromLatLon;
	}

	public void setFromLatLon(Serializable fromLatLon) {
		this.fromLatLon = fromLatLon;
	}

	@Column(name = "ToLatLon")
	public Serializable getToLatLon() {
		return this.toLatLon;
	}

	public void setToLatLon(Serializable toLatLon) {
		this.toLatLon = toLatLon;
	}

	@Column(name = "RouteSegment")
	public byte[] getRouteSegment() {
		return this.routeSegment;
	}

	public void setRouteSegment(byte[] routeSegment) {
		this.routeSegment = routeSegment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ManagerEmailId")
	public Serializable getManagerEmailId() {
		return this.managerEmailId;
	}

	public void setManagerEmailId(Serializable managerEmailId) {
		this.managerEmailId = managerEmailId;
	}

}
