package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AndroidLoginDetails generated by hbm2java
 */
@Entity
@Table(name = "AndroidLoginDetails", schema = "dbo", catalog = "FMS4.0")
public class AndroidLoginDetails implements java.io.Serializable {

	private int id;
	private Serializable loginId;
	private Date loginTime;
	private Date alertTime;
	private Serializable deviceId;
	private Date createdOn;
	private Date modifiedOn;
	private Date alertReadTime;

	public AndroidLoginDetails() {
	}

	public AndroidLoginDetails(int id, Serializable loginId, Date loginTime) {
		this.id = id;
		this.loginId = loginId;
		this.loginTime = loginTime;
	}

	public AndroidLoginDetails(int id, Serializable loginId, Date loginTime, Date alertTime, Serializable deviceId,
			Date createdOn, Date modifiedOn, Date alertReadTime) {
		this.id = id;
		this.loginId = loginId;
		this.loginTime = loginTime;
		this.alertTime = alertTime;
		this.deviceId = deviceId;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.alertReadTime = alertReadTime;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LoginID", nullable = false)
	public Serializable getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Serializable loginId) {
		this.loginId = loginId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LoginTime", nullable = false, length = 23)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AlertTime", length = 23)
	public Date getAlertTime() {
		return this.alertTime;
	}

	public void setAlertTime(Date alertTime) {
		this.alertTime = alertTime;
	}

	@Column(name = "DeviceID")
	public Serializable getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Serializable deviceId) {
		this.deviceId = deviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AlertReadTime", length = 23)
	public Date getAlertReadTime() {
		return this.alertReadTime;
	}

	public void setAlertReadTime(Date alertReadTime) {
		this.alertReadTime = alertReadTime;
	}

}
