package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AravaliWaypointsId generated by hbm2java
 */
@Embeddable
public class AravaliWaypointsId implements java.io.Serializable {

	private Serializable name;
	private Serializable lat;
	private Serializable long_;

	public AravaliWaypointsId() {
	}

	public AravaliWaypointsId(Serializable name, Serializable lat, Serializable long_) {
		this.name = name;
		this.lat = lat;
		this.long_ = long_;
	}

	@Column(name = "Name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Lat")
	public Serializable getLat() {
		return this.lat;
	}

	public void setLat(Serializable lat) {
		this.lat = lat;
	}

	@Column(name = "Long")
	public Serializable getLong_() {
		return this.long_;
	}

	public void setLong_(Serializable long_) {
		this.long_ = long_;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AravaliWaypointsId))
			return false;
		AravaliWaypointsId castOther = (AravaliWaypointsId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getLat() == castOther.getLat()) || (this.getLat() != null && castOther.getLat() != null
						&& this.getLat().equals(castOther.getLat())))
				&& ((this.getLong_() == castOther.getLong_()) || (this.getLong_() != null
						&& castOther.getLong_() != null && this.getLong_().equals(castOther.getLong_())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getLat() == null ? 0 : this.getLat().hashCode());
		result = 37 * result + (getLong_() == null ? 0 : this.getLong_().hashCode());
		return result;
	}

}
