package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AravaliWaypoints generated by hbm2java
 */
@Entity
@Table(name = "AravaliWaypoints", schema = "dbo", catalog = "FMS4.0")
public class AravaliWaypoints implements java.io.Serializable {

	private AravaliWaypointsId id;

	public AravaliWaypoints() {
	}

	public AravaliWaypoints(AravaliWaypointsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "Name")),
			@AttributeOverride(name = "lat", column = @Column(name = "Lat")),
			@AttributeOverride(name = "long_", column = @Column(name = "Long")) })
	public AravaliWaypointsId getId() {
		return this.id;
	}

	public void setId(AravaliWaypointsId id) {
		this.id = id;
	}

}
