package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssetAlerts generated by hbm2java
 */
@Entity
@Table(name = "AssetAlerts", schema = "dbo", catalog = "FMS4.0")
public class AssetAlerts implements java.io.Serializable {

	private int id;
	private int vehicleId;
	private Serializable phoneNumber;
	private Serializable emailId;
	private Boolean smsAlert;
	private Boolean emailAlert;
	private boolean isdeleted;

	public AssetAlerts() {
	}

	public AssetAlerts(int id, int vehicleId, boolean isdeleted) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.isdeleted = isdeleted;
	}

	public AssetAlerts(int id, int vehicleId, Serializable phoneNumber, Serializable emailId, Boolean smsAlert,
			Boolean emailAlert, boolean isdeleted) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.phoneNumber = phoneNumber;
		this.emailId = emailId;
		this.smsAlert = smsAlert;
		this.emailAlert = emailAlert;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VehicleID", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "PhoneNumber")
	public Serializable getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Serializable phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "EmailID")
	public Serializable getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Serializable emailId) {
		this.emailId = emailId;
	}

	@Column(name = "SmsAlert")
	public Boolean getSmsAlert() {
		return this.smsAlert;
	}

	public void setSmsAlert(Boolean smsAlert) {
		this.smsAlert = smsAlert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "Isdeleted", nullable = false)
	public boolean isIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
