package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "Cities", schema = "dbo", catalog = "FMS4.0")
public class Cities implements java.io.Serializable {

	private long cityId;
	private long districtId;
	private String cityName;
	private Boolean isdeleted;

	public Cities() {
	}

	public Cities(long cityId, long districtId, String cityName) {
		this.cityId = cityId;
		this.districtId = districtId;
		this.cityName = cityName;
	}

	public Cities(long cityId, long districtId, String cityName, Boolean isdeleted) {
		this.cityId = cityId;
		this.districtId = districtId;
		this.cityName = cityName;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "CityId", unique = true, nullable = false)
	public long getCityId() {
		return this.cityId;
	}

	public void setCityId(long cityId) {
		this.cityId = cityId;
	}

	@Column(name = "DistrictId", nullable = false)
	public long getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(long districtId) {
		this.districtId = districtId;
	}

	@Column(name = "CityName", nullable = false, length = 100)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
