package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassOfVehicles generated by hbm2java
 */
@Entity
@Table(name = "ClassOfVehicles", schema = "dbo", catalog = "FMS4.0")
public class ClassOfVehicles implements java.io.Serializable {

	private int id;
	private int companyId;
	private int groupId;
	private Serializable vehicleClassName;
	private Serializable description;
	private Serializable maxSpeedLimit;
	private String createdBy;
	private Date createdOn;
	private String modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;

	public ClassOfVehicles() {
	}

	public ClassOfVehicles(int id, int companyId, int groupId, Serializable vehicleClassName,
			Serializable maxSpeedLimit, String createdBy, Date createdOn, String modifiedBy, Date modifiedOn,
			boolean isDeleted) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.vehicleClassName = vehicleClassName;
		this.maxSpeedLimit = maxSpeedLimit;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	public ClassOfVehicles(int id, int companyId, int groupId, Serializable vehicleClassName, Serializable description,
			Serializable maxSpeedLimit, String createdBy, Date createdOn, String modifiedBy, Date modifiedOn,
			boolean isDeleted) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.vehicleClassName = vehicleClassName;
		this.description = description;
		this.maxSpeedLimit = maxSpeedLimit;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CompanyID", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleClassName", nullable = false)
	public Serializable getVehicleClassName() {
		return this.vehicleClassName;
	}

	public void setVehicleClassName(Serializable vehicleClassName) {
		this.vehicleClassName = vehicleClassName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "MaxSpeedLimit", nullable = false)
	public Serializable getMaxSpeedLimit() {
		return this.maxSpeedLimit;
	}

	public void setMaxSpeedLimit(Serializable maxSpeedLimit) {
		this.maxSpeedLimit = maxSpeedLimit;
	}

	@Column(name = "CreatedBy", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", nullable = false, length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", nullable = false, length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
