package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "Countries", schema = "dbo", catalog = "FMS4.0")
public class Countries implements java.io.Serializable {

	private int countryId;
	private String countryName;
	private Boolean isdeleted;

	public Countries() {
	}

	public Countries(int countryId, String countryName) {
		this.countryId = countryId;
		this.countryName = countryName;
	}

	public Countries(int countryId, String countryName, Boolean isdeleted) {
		this.countryId = countryId;
		this.countryName = countryName;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "CountryID", unique = true, nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Column(name = "CountryName", nullable = false, length = 100)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
