package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DailyDriverSummary generated by hbm2java
 */
@Entity
@Table(name = "DailyDriverSummary", schema = "dbo", catalog = "FMS4.0")
public class DailyDriverSummary implements java.io.Serializable {

	private DailyDriverSummaryId id;
	private int groupId;
	private Date date;
	private Integer acceleration;
	private Integer braking;
	private Integer cornering;
	private Integer overSpeed;
	private Integer crossBorder;
	private Integer routeDeviate;
	private Integer missedStop;
	private Integer panic;

	public DailyDriverSummary() {
	}

	public DailyDriverSummary(DailyDriverSummaryId id, int groupId, Date date) {
		this.id = id;
		this.groupId = groupId;
		this.date = date;
	}

	public DailyDriverSummary(DailyDriverSummaryId id, int groupId, Date date, Integer acceleration, Integer braking,
			Integer cornering, Integer overSpeed, Integer crossBorder, Integer routeDeviate, Integer missedStop,
			Integer panic) {
		this.id = id;
		this.groupId = groupId;
		this.date = date;
		this.acceleration = acceleration;
		this.braking = braking;
		this.cornering = cornering;
		this.overSpeed = overSpeed;
		this.crossBorder = crossBorder;
		this.routeDeviate = routeDeviate;
		this.missedStop = missedStop;
		this.panic = panic;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "EmployeeId", nullable = false)) })
	public DailyDriverSummaryId getId() {
		return this.id;
	}

	public void setId(DailyDriverSummaryId id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Acceleration")
	public Integer getAcceleration() {
		return this.acceleration;
	}

	public void setAcceleration(Integer acceleration) {
		this.acceleration = acceleration;
	}

	@Column(name = "Braking")
	public Integer getBraking() {
		return this.braking;
	}

	public void setBraking(Integer braking) {
		this.braking = braking;
	}

	@Column(name = "Cornering")
	public Integer getCornering() {
		return this.cornering;
	}

	public void setCornering(Integer cornering) {
		this.cornering = cornering;
	}

	@Column(name = "OverSpeed")
	public Integer getOverSpeed() {
		return this.overSpeed;
	}

	public void setOverSpeed(Integer overSpeed) {
		this.overSpeed = overSpeed;
	}

	@Column(name = "CrossBorder")
	public Integer getCrossBorder() {
		return this.crossBorder;
	}

	public void setCrossBorder(Integer crossBorder) {
		this.crossBorder = crossBorder;
	}

	@Column(name = "RouteDeviate")
	public Integer getRouteDeviate() {
		return this.routeDeviate;
	}

	public void setRouteDeviate(Integer routeDeviate) {
		this.routeDeviate = routeDeviate;
	}

	@Column(name = "MissedStop")
	public Integer getMissedStop() {
		return this.missedStop;
	}

	public void setMissedStop(Integer missedStop) {
		this.missedStop = missedStop;
	}

	@Column(name = "Panic")
	public Integer getPanic() {
		return this.panic;
	}

	public void setPanic(Integer panic) {
		this.panic = panic;
	}

}
