package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DailyDriverSummaryId generated by hbm2java
 */
@Embeddable
public class DailyDriverSummaryId implements java.io.Serializable {

	private int id;
	private int employeeId;

	public DailyDriverSummaryId() {
	}

	public DailyDriverSummaryId(int id, int employeeId) {
		this.id = id;
		this.employeeId = employeeId;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "EmployeeId", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DailyDriverSummaryId))
			return false;
		DailyDriverSummaryId castOther = (DailyDriverSummaryId) other;

		return (this.getId() == castOther.getId()) && (this.getEmployeeId() == castOther.getEmployeeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getEmployeeId();
		return result;
	}

}
