package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirectionsId generated by hbm2java
 */
@Embeddable
public class DirectionsId implements java.io.Serializable {

	private int id;
	private Integer direction;
	private Double startPoint;
	private Double endPoint;

	public DirectionsId() {
	}

	public DirectionsId(int id) {
		this.id = id;
	}

	public DirectionsId(int id, Integer direction, Double startPoint, Double endPoint) {
		this.id = id;
		this.direction = direction;
		this.startPoint = startPoint;
		this.endPoint = endPoint;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Direction")
	public Integer getDirection() {
		return this.direction;
	}

	public void setDirection(Integer direction) {
		this.direction = direction;
	}

	@Column(name = "startPoint", precision = 53, scale = 0)
	public Double getStartPoint() {
		return this.startPoint;
	}

	public void setStartPoint(Double startPoint) {
		this.startPoint = startPoint;
	}

	@Column(name = "EndPoint", precision = 53, scale = 0)
	public Double getEndPoint() {
		return this.endPoint;
	}

	public void setEndPoint(Double endPoint) {
		this.endPoint = endPoint;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirectionsId))
			return false;
		DirectionsId castOther = (DirectionsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDirection() == castOther.getDirection()) || (this.getDirection() != null
						&& castOther.getDirection() != null && this.getDirection().equals(castOther.getDirection())))
				&& ((this.getStartPoint() == castOther.getStartPoint()) || (this.getStartPoint() != null
						&& castOther.getStartPoint() != null && this.getStartPoint().equals(castOther.getStartPoint())))
				&& ((this.getEndPoint() == castOther.getEndPoint()) || (this.getEndPoint() != null
						&& castOther.getEndPoint() != null && this.getEndPoint().equals(castOther.getEndPoint())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
		result = 37 * result + (getStartPoint() == null ? 0 : this.getStartPoint().hashCode());
		result = 37 * result + (getEndPoint() == null ? 0 : this.getEndPoint().hashCode());
		return result;
	}

}
