package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Directions generated by hbm2java
 */
@Entity
@Table(name = "Directions", schema = "dbo", catalog = "FMS4.0")
public class Directions implements java.io.Serializable {

	private DirectionsId id;

	public Directions() {
	}

	public Directions(DirectionsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "direction", column = @Column(name = "Direction")),
			@AttributeOverride(name = "startPoint", column = @Column(name = "startPoint", precision = 53, scale = 0)),
			@AttributeOverride(name = "endPoint", column = @Column(name = "EndPoint", precision = 53, scale = 0)) })
	public DirectionsId getId() {
		return this.id;
	}

	public void setId(DirectionsId id) {
		this.id = id;
	}

}
