package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Districts generated by hbm2java
 */
@Entity
@Table(name = "Districts", schema = "dbo", catalog = "FMS4.0")
public class Districts implements java.io.Serializable {

	private long districtId;
	private long stateId;
	private String districtName;
	private Boolean isdeleted;

	public Districts() {
	}

	public Districts(long districtId, long stateId, String districtName) {
		this.districtId = districtId;
		this.stateId = stateId;
		this.districtName = districtName;
	}

	public Districts(long districtId, long stateId, String districtName, Boolean isdeleted) {
		this.districtId = districtId;
		this.stateId = stateId;
		this.districtName = districtName;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "DistrictId", unique = true, nullable = false)
	public long getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(long districtId) {
		this.districtId = districtId;
	}

	@Column(name = "StateId", nullable = false)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

	@Column(name = "DistrictName", nullable = false, length = 100)
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
