package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DrivingBehaviourMaster generated by hbm2java
 */
@Entity
@Table(name = "DrivingBehaviourMaster", schema = "dbo", catalog = "FMS4.0")
public class DrivingBehaviourMaster implements java.io.Serializable {

	private DrivingBehaviourMasterId id;

	public DrivingBehaviourMaster() {
	}

	public DrivingBehaviourMaster(DrivingBehaviourMasterId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dbehaviourParameterId", column = @Column(name = "DBehaviourParameterID", nullable = false)),
			@AttributeOverride(name = "parameterName", column = @Column(name = "ParameterName")),
			@AttributeOverride(name = "description", column = @Column(name = "Description")),
			@AttributeOverride(name = "weightage", column = @Column(name = "Weightage", precision = 53, scale = 0)),
			@AttributeOverride(name = "behaviourTypeId", column = @Column(name = "BehaviourTypeID")),
			@AttributeOverride(name = "isRequired", column = @Column(name = "IsRequired")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "ModifiedBy")),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "IsDeleted")) })
	public DrivingBehaviourMasterId getId() {
		return this.id;
	}

	public void setId(DrivingBehaviourMasterId id) {
		this.id = id;
	}

}
