package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DrivingBehaviourClassificationId generated by hbm2java
 */
@Embeddable
public class DrivingBehaviourClassificationId implements java.io.Serializable {

	private int id;
	private Integer dbehaviourParameterId;
	private Integer groupId;
	private Double weightage;
	private Boolean isRequired;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;

	public DrivingBehaviourClassificationId() {
	}

	public DrivingBehaviourClassificationId(int id) {
		this.id = id;
	}

	public DrivingBehaviourClassificationId(int id, Integer dbehaviourParameterId, Integer groupId, Double weightage,
			Boolean isRequired, Serializable createdBy, Date createdOn, Serializable modifiedBy, Date modifiedOn) {
		this.id = id;
		this.dbehaviourParameterId = dbehaviourParameterId;
		this.groupId = groupId;
		this.weightage = weightage;
		this.isRequired = isRequired;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DBehaviourParameterID")
	public Integer getDbehaviourParameterId() {
		return this.dbehaviourParameterId;
	}

	public void setDbehaviourParameterId(Integer dbehaviourParameterId) {
		this.dbehaviourParameterId = dbehaviourParameterId;
	}

	@Column(name = "GroupID")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Weightage", precision = 53, scale = 0)
	public Double getWeightage() {
		return this.weightage;
	}

	public void setWeightage(Double weightage) {
		this.weightage = weightage;
	}

	@Column(name = "IsRequired")
	public Boolean getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DrivingBehaviourClassificationId))
			return false;
		DrivingBehaviourClassificationId castOther = (DrivingBehaviourClassificationId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDbehaviourParameterId() == castOther.getDbehaviourParameterId())
						|| (this.getDbehaviourParameterId() != null && castOther.getDbehaviourParameterId() != null
								&& this.getDbehaviourParameterId().equals(castOther.getDbehaviourParameterId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null
						&& castOther.getGroupId() != null && this.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getWeightage() == castOther.getWeightage()) || (this.getWeightage() != null
						&& castOther.getWeightage() != null && this.getWeightage().equals(castOther.getWeightage())))
				&& ((this.getIsRequired() == castOther.getIsRequired()) || (this.getIsRequired() != null
						&& castOther.getIsRequired() != null && this.getIsRequired().equals(castOther.getIsRequired())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn())
						|| (this.getModifiedOn() != null && castOther.getModifiedOn() != null
								&& this.getModifiedOn().equals(castOther.getModifiedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getDbehaviourParameterId() == null ? 0 : this.getDbehaviourParameterId().hashCode());
		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result + (getWeightage() == null ? 0 : this.getWeightage().hashCode());
		result = 37 * result + (getIsRequired() == null ? 0 : this.getIsRequired().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		return result;
	}

}
