package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DrivingBehaviourClassification generated by hbm2java
 */
@Entity
@Table(name = "DrivingBehaviourClassification", schema = "dbo", catalog = "FMS4.0")
public class DrivingBehaviourClassification implements java.io.Serializable {

	private DrivingBehaviourClassificationId id;

	public DrivingBehaviourClassification() {
	}

	public DrivingBehaviourClassification(DrivingBehaviourClassificationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "dbehaviourParameterId", column = @Column(name = "DBehaviourParameterID")),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID")),
			@AttributeOverride(name = "weightage", column = @Column(name = "Weightage", precision = 53, scale = 0)),
			@AttributeOverride(name = "isRequired", column = @Column(name = "IsRequired")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "ModifiedBy")),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)) })
	public DrivingBehaviourClassificationId getId() {
		return this.id;
	}

	public void setId(DrivingBehaviourClassificationId id) {
		this.id = id;
	}

}
