package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DutyAllocation generated by hbm2java
 */
@Entity
@Table(name = "DutyAllocation", schema = "dbo", catalog = "FMS4.0")
public class DutyAllocation implements java.io.Serializable {

	private int id;
	private Employees employees;
	private Serializable operatingDays;

	public DutyAllocation() {
	}

	public DutyAllocation(int id, Employees employees) {
		this.id = id;
		this.employees = employees;
	}

	public DutyAllocation(int id, Employees employees, Serializable operatingDays) {
		this.id = id;
		this.employees = employees;
		this.operatingDays = operatingDays;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EmployeeId", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "OperatingDays")
	public Serializable getOperatingDays() {
		return this.operatingDays;
	}

	public void setOperatingDays(Serializable operatingDays) {
		this.operatingDays = operatingDays;
	}

}
