package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeforAllocation generated by hbm2java
 */
@Entity
@Table(name = "EmployeeforAllocation", schema = "dbo", catalog = "FMS4.0")
public class EmployeeforAllocation implements java.io.Serializable {

	private int id;
	private int groupId;
	private Serializable firstName;
	private Character gender;
	private int homeAddressId;
	private Serializable email;
	private Serializable mobileNo;
	private Serializable contactNo;
	private Boolean smsalert;
	private Boolean emailAlert;
	private Boolean isDeleted;
	private Serializable createdBy;
	private Date createOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Integer area;
	private Serializable address;
	private Integer pickupPoint;
	private Integer dropPoint;
	private Integer pickupRouteId;
	private Integer dropRouteId;
	private Date pickupTime;
	private Date dropTime;

	public EmployeeforAllocation() {
	}

	public EmployeeforAllocation(int id, int groupId, Serializable firstName, int homeAddressId, Serializable email,
			Serializable mobileNo) {
		this.id = id;
		this.groupId = groupId;
		this.firstName = firstName;
		this.homeAddressId = homeAddressId;
		this.email = email;
		this.mobileNo = mobileNo;
	}

	public EmployeeforAllocation(int id, int groupId, Serializable firstName, Character gender, int homeAddressId,
			Serializable email, Serializable mobileNo, Serializable contactNo, Boolean smsalert, Boolean emailAlert,
			Boolean isDeleted, Serializable createdBy, Date createOn, Serializable modifiedBy, Date modifiedOn,
			Integer area, Serializable address, Integer pickupPoint, Integer dropPoint, Integer pickupRouteId,
			Integer dropRouteId, Date pickupTime, Date dropTime) {
		this.id = id;
		this.groupId = groupId;
		this.firstName = firstName;
		this.gender = gender;
		this.homeAddressId = homeAddressId;
		this.email = email;
		this.mobileNo = mobileNo;
		this.contactNo = contactNo;
		this.smsalert = smsalert;
		this.emailAlert = emailAlert;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.area = area;
		this.address = address;
		this.pickupPoint = pickupPoint;
		this.dropPoint = dropPoint;
		this.pickupRouteId = pickupRouteId;
		this.dropRouteId = dropRouteId;
		this.pickupTime = pickupTime;
		this.dropTime = dropTime;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "FirstName", nullable = false)
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "HomeAddressId", nullable = false)
	public int getHomeAddressId() {
		return this.homeAddressId;
	}

	public void setHomeAddressId(int homeAddressId) {
		this.homeAddressId = homeAddressId;
	}

	@Column(name = "Email", nullable = false)
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "MobileNo", nullable = false)
	public Serializable getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Serializable mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "ContactNo")
	public Serializable getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(Serializable contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "SMSAlert")
	public Boolean getSmsalert() {
		return this.smsalert;
	}

	public void setSmsalert(Boolean smsalert) {
		this.smsalert = smsalert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createOn", length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "modifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Area")
	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "PickupPoint")
	public Integer getPickupPoint() {
		return this.pickupPoint;
	}

	public void setPickupPoint(Integer pickupPoint) {
		this.pickupPoint = pickupPoint;
	}

	@Column(name = "DropPoint")
	public Integer getDropPoint() {
		return this.dropPoint;
	}

	public void setDropPoint(Integer dropPoint) {
		this.dropPoint = dropPoint;
	}

	@Column(name = "PickupRouteID")
	public Integer getPickupRouteId() {
		return this.pickupRouteId;
	}

	public void setPickupRouteId(Integer pickupRouteId) {
		this.pickupRouteId = pickupRouteId;
	}

	@Column(name = "DropRouteID")
	public Integer getDropRouteId() {
		return this.dropRouteId;
	}

	public void setDropRouteId(Integer dropRouteId) {
		this.dropRouteId = dropRouteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PickupTime", length = 23)
	public Date getPickupTime() {
		return this.pickupTime;
	}

	public void setPickupTime(Date pickupTime) {
		this.pickupTime = pickupTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DropTime", length = 23)
	public Date getDropTime() {
		return this.dropTime;
	}

	public void setDropTime(Date dropTime) {
		this.dropTime = dropTime;
	}

}
