package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FleetWayPointDetail generated by hbm2java
 */
@Entity
@Table(name = "FleetWayPointDetail", schema = "dbo", catalog = "FMS4.0")
public class FleetWayPointDetail implements java.io.Serializable {

	private int id;
	private int fleetId;
	private int wayPointId;
	private Serializable wayPointType;
	private Boolean isWayPoint;
	private Integer wayPointSequence;
	private Date wayPointTime;
	private Date createdOn;
	private Serializable createdBy;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private BigDecimal stopSpeed;
	private Integer newWayPointSequence;
	private Date scheduledWayPointTime;

	public FleetWayPointDetail() {
	}

	public FleetWayPointDetail(int id, int fleetId, int wayPointId) {
		this.id = id;
		this.fleetId = fleetId;
		this.wayPointId = wayPointId;
	}

	public FleetWayPointDetail(int id, int fleetId, int wayPointId, Serializable wayPointType, Boolean isWayPoint,
			Integer wayPointSequence, Date wayPointTime, Date createdOn, Serializable createdBy,
			Serializable modifiedBy, Date modifiedOn, BigDecimal stopSpeed, Integer newWayPointSequence,
			Date scheduledWayPointTime) {
		this.id = id;
		this.fleetId = fleetId;
		this.wayPointId = wayPointId;
		this.wayPointType = wayPointType;
		this.isWayPoint = isWayPoint;
		this.wayPointSequence = wayPointSequence;
		this.wayPointTime = wayPointTime;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.stopSpeed = stopSpeed;
		this.newWayPointSequence = newWayPointSequence;
		this.scheduledWayPointTime = scheduledWayPointTime;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "FleetId", nullable = false)
	public int getFleetId() {
		return this.fleetId;
	}

	public void setFleetId(int fleetId) {
		this.fleetId = fleetId;
	}

	@Column(name = "WayPointId", nullable = false)
	public int getWayPointId() {
		return this.wayPointId;
	}

	public void setWayPointId(int wayPointId) {
		this.wayPointId = wayPointId;
	}

	@Column(name = "WayPointType")
	public Serializable getWayPointType() {
		return this.wayPointType;
	}

	public void setWayPointType(Serializable wayPointType) {
		this.wayPointType = wayPointType;
	}

	@Column(name = "IsWayPoint")
	public Boolean getIsWayPoint() {
		return this.isWayPoint;
	}

	public void setIsWayPoint(Boolean isWayPoint) {
		this.isWayPoint = isWayPoint;
	}

	@Column(name = "WayPointSequence")
	public Integer getWayPointSequence() {
		return this.wayPointSequence;
	}

	public void setWayPointSequence(Integer wayPointSequence) {
		this.wayPointSequence = wayPointSequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WayPointTime", length = 23)
	public Date getWayPointTime() {
		return this.wayPointTime;
	}

	public void setWayPointTime(Date wayPointTime) {
		this.wayPointTime = wayPointTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "StopSpeed", precision = 18)
	public BigDecimal getStopSpeed() {
		return this.stopSpeed;
	}

	public void setStopSpeed(BigDecimal stopSpeed) {
		this.stopSpeed = stopSpeed;
	}

	@Column(name = "NewWayPointSequence")
	public Integer getNewWayPointSequence() {
		return this.newWayPointSequence;
	}

	public void setNewWayPointSequence(Integer newWayPointSequence) {
		this.newWayPointSequence = newWayPointSequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ScheduledWayPointTime", length = 23)
	public Date getScheduledWayPointTime() {
		return this.scheduledWayPointTime;
	}

	public void setScheduledWayPointTime(Date scheduledWayPointTime) {
		this.scheduledWayPointTime = scheduledWayPointTime;
	}

}
