package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupDirections generated by hbm2java
 */
@Entity
@Table(name = "GroupDirections", schema = "dbo", catalog = "FMS4.0")
public class GroupDirections implements java.io.Serializable {

	private GroupDirectionsId id;

	public GroupDirections() {
	}

	public GroupDirections(GroupDirectionsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID")),
			@AttributeOverride(name = "directionId", column = @Column(name = "DirectionID")),
			@AttributeOverride(name = "startPoint", column = @Column(name = "StartPoint", precision = 53, scale = 0)),
			@AttributeOverride(name = "endPoint", column = @Column(name = "EndPoint", precision = 53, scale = 0)) })
	public GroupDirectionsId getId() {
		return this.id;
	}

	public void setId(GroupDirectionsId id) {
		this.id = id;
	}

}
