package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupbasedClassification generated by hbm2java
 */
@Entity
@Table(name = "GroupbasedClassification", schema = "dbo", catalog = "FMS4.0")
public class GroupbasedClassification implements java.io.Serializable {

	private GroupbasedClassificationId id;

	public GroupbasedClassification() {
	}

	public GroupbasedClassification(GroupbasedClassificationId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "vehicleClassId", column = @Column(name = "VehicleClassID", nullable = false)),
			@AttributeOverride(name = "companyId", column = @Column(name = "CompanyID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "maxSpeedLimit", column = @Column(name = "MaxSpeedLimit", nullable = false, length = 50)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "ModifiedBy", nullable = false, length = 50)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", nullable = false, length = 23)) })
	public GroupbasedClassificationId getId() {
		return this.id;
	}

	public void setId(GroupbasedClassificationId id) {
		this.id = id;
	}

}
