package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "Groups", schema = "dbo", catalog = "FMS4.0")
public class Groups implements java.io.Serializable {

	private int id;
	private Serializable groupName;
	private Serializable address1;
	private Serializable address2;
	private Serializable address3;
	private Integer countryId;
	private Integer stateId;
	private Integer districtId;
	private Integer cityId;
	private Serializable contactPerson;
	private Serializable contactNumber1;
	private Serializable mobileNumber;
	private Serializable email;
	private Serializable fax;
	private Serializable pinCode;
	private Integer companyId;
	private Serializable createdBy;
	private Date createOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Boolean isDeleted;
	private Integer groupAdressId;
	private byte[] latLong;
	private Boolean createWaypoint;
	private Integer maxDistance;
	private String timezoneName;
	private Boolean isRoundTrip;
	private Integer tripEndTime;
	private Integer cutOffTime;
	private Set<UserGroupMapping> userGroupMappings = new HashSet<UserGroupMapping>(0);

	public Groups() {
	}

	public Groups(int id) {
		this.id = id;
	}

	public Groups(int id, Serializable groupName, Serializable address1, Serializable address2, Serializable address3,
			Integer countryId, Integer stateId, Integer districtId, Integer cityId, Serializable contactPerson,
			Serializable contactNumber1, Serializable mobileNumber, Serializable email, Serializable fax,
			Serializable pinCode, Integer companyId, Serializable createdBy, Date createOn, Serializable modifiedBy,
			Date modifiedOn, Boolean isDeleted, Integer groupAdressId, byte[] latLong, Boolean createWaypoint,
			Integer maxDistance, String timezoneName, Boolean isRoundTrip, Integer tripEndTime, Integer cutOffTime,
			Set<UserGroupMapping> userGroupMappings) {
		this.id = id;
		this.groupName = groupName;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.countryId = countryId;
		this.stateId = stateId;
		this.districtId = districtId;
		this.cityId = cityId;
		this.contactPerson = contactPerson;
		this.contactNumber1 = contactNumber1;
		this.mobileNumber = mobileNumber;
		this.email = email;
		this.fax = fax;
		this.pinCode = pinCode;
		this.companyId = companyId;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.groupAdressId = groupAdressId;
		this.latLong = latLong;
		this.createWaypoint = createWaypoint;
		this.maxDistance = maxDistance;
		this.timezoneName = timezoneName;
		this.isRoundTrip = isRoundTrip;
		this.tripEndTime = tripEndTime;
		this.cutOffTime = cutOffTime;
		this.userGroupMappings = userGroupMappings;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupName")
	public Serializable getGroupName() {
		return this.groupName;
	}

	public void setGroupName(Serializable groupName) {
		this.groupName = groupName;
	}

	@Column(name = "Address1")
	public Serializable getAddress1() {
		return this.address1;
	}

	public void setAddress1(Serializable address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2")
	public Serializable getAddress2() {
		return this.address2;
	}

	public void setAddress2(Serializable address2) {
		this.address2 = address2;
	}

	@Column(name = "Address3")
	public Serializable getAddress3() {
		return this.address3;
	}

	public void setAddress3(Serializable address3) {
		this.address3 = address3;
	}

	@Column(name = "CountryId")
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "StateId")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "DistrictId")
	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	@Column(name = "CityId")
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "ContactPerson")
	public Serializable getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(Serializable contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "ContactNumber1")
	public Serializable getContactNumber1() {
		return this.contactNumber1;
	}

	public void setContactNumber1(Serializable contactNumber1) {
		this.contactNumber1 = contactNumber1;
	}

	@Column(name = "MobileNumber")
	public Serializable getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(Serializable mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "Fax")
	public Serializable getFax() {
		return this.fax;
	}

	public void setFax(Serializable fax) {
		this.fax = fax;
	}

	@Column(name = "PinCode")
	public Serializable getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(Serializable pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "CompanyID")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateOn", length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "GroupAdressID")
	public Integer getGroupAdressId() {
		return this.groupAdressId;
	}

	public void setGroupAdressId(Integer groupAdressId) {
		this.groupAdressId = groupAdressId;
	}

	@Column(name = "LatLong")
	public byte[] getLatLong() {
		return this.latLong;
	}

	public void setLatLong(byte[] latLong) {
		this.latLong = latLong;
	}

	@Column(name = "CreateWaypoint")
	public Boolean getCreateWaypoint() {
		return this.createWaypoint;
	}

	public void setCreateWaypoint(Boolean createWaypoint) {
		this.createWaypoint = createWaypoint;
	}

	@Column(name = "MaxDistance")
	public Integer getMaxDistance() {
		return this.maxDistance;
	}

	public void setMaxDistance(Integer maxDistance) {
		this.maxDistance = maxDistance;
	}

	@Column(name = "Timezone_Name", length = 25)
	public String getTimezoneName() {
		return this.timezoneName;
	}

	public void setTimezoneName(String timezoneName) {
		this.timezoneName = timezoneName;
	}

	@Column(name = "IsRoundTrip")
	public Boolean getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Boolean isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}

	@Column(name = "TripEndTime")
	public Integer getTripEndTime() {
		return this.tripEndTime;
	}

	public void setTripEndTime(Integer tripEndTime) {
		this.tripEndTime = tripEndTime;
	}

	@Column(name = "CutOffTime")
	public Integer getCutOffTime() {
		return this.cutOffTime;
	}

	public void setCutOffTime(Integer cutOffTime) {
		this.cutOffTime = cutOffTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<UserGroupMapping> getUserGroupMappings() {
		return this.userGroupMappings;
	}

	public void setUserGroupMappings(Set<UserGroupMapping> userGroupMappings) {
		this.userGroupMappings = userGroupMappings;
	}

}
