package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Kar28 generated by hbm2java
 */
@Entity
@Table(name = "kar28", schema = "dbo", catalog = "FMS4.0")
public class Kar28 implements java.io.Serializable {

	private Kar28Id id;

	public Kar28() {
	}

	public Kar28(Kar28Id id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "routeid", column = @Column(name = "Routeid")),
			@AttributeOverride(name = "routename", column = @Column(name = "routename")),
			@AttributeOverride(name = "wayPointId", column = @Column(name = "WayPointID")),
			@AttributeOverride(name = "wayPointName", column = @Column(name = "WayPointName")),
			@AttributeOverride(name = "sequenceOrder", column = @Column(name = "SequenceOrder")) })
	public Kar28Id getId() {
		return this.id;
	}

	public void setId(Kar28Id id) {
		this.id = id;
	}

}
