package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Karnfc generated by hbm2java
 */
@Entity
@Table(name = "karnfc", schema = "dbo", catalog = "FMS4.0")
public class Karnfc implements java.io.Serializable {

	private KarnfcId id;

	public Karnfc() {
	}

	public Karnfc(KarnfcId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "vehicleNo", column = @Column(name = "VehicleNo", length = 20)),
			@AttributeOverride(name = "fuelValue", column = @Column(name = "FuelValue", precision = 53, scale = 0)),
			@AttributeOverride(name = "fuelDate", column = @Column(name = "FuelDate", length = 23)),
			@AttributeOverride(name = "distance", column = @Column(name = "Distance", precision = 53, scale = 0)),
			@AttributeOverride(name = "mileage", column = @Column(name = "Mileage", precision = 53, scale = 0)),
			@AttributeOverride(name = "lat", column = @Column(name = "Lat", precision = 53, scale = 0)),
			@AttributeOverride(name = "lon", column = @Column(name = "Lon", precision = 53, scale = 0)),
			@AttributeOverride(name = "nfcMileage", column = @Column(name = "nfcMileage")) })
	public KarnfcId getId() {
		return this.id;
	}

	public void setId(KarnfcId id) {
		this.id = id;
	}

}
