package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginAudit generated by hbm2java
 */
@Entity
@Table(name = "LoginAudit", schema = "dbo", catalog = "FMS4.0")
public class LoginAudit implements java.io.Serializable {

	private long auditId;
	private Serializable userId;
	private Date loginTime;
	private Date logoutTime;
	private Integer roles;
	private String ipaddress;
	private String sessionId;

	public LoginAudit() {
	}

	public LoginAudit(long auditId) {
		this.auditId = auditId;
	}

	public LoginAudit(long auditId, Serializable userId, Date loginTime, Date logoutTime, Integer roles,
			String ipaddress, String sessionId) {
		this.auditId = auditId;
		this.userId = userId;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.roles = roles;
		this.ipaddress = ipaddress;
		this.sessionId = sessionId;
	}

	@Id

	@Column(name = "AuditId", unique = true, nullable = false)
	public long getAuditId() {
		return this.auditId;
	}

	public void setAuditId(long auditId) {
		this.auditId = auditId;
	}

	@Column(name = "UserId")
	public Serializable getUserId() {
		return this.userId;
	}

	public void setUserId(Serializable userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LoginTime", length = 23)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LogoutTime", length = 23)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "Roles")
	public Integer getRoles() {
		return this.roles;
	}

	public void setRoles(Integer roles) {
		this.roles = roles;
	}

	@Column(name = "IPAddress", length = 50)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "SessionID", length = 50)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

}
