package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lookup generated by hbm2java
 */
@Entity
@Table(name = "Lookup", schema = "dbo", catalog = "FMS4.0")
public class Lookup implements java.io.Serializable {

	private int id;
	private String category;
	private String value;
	private String createdBy;
	private Date createOn;
	private String modifiedBy;
	private Date modifiedOn;
	private Boolean isDeleted;
	private Set<AlertMaster> alertMastersForSeverityId = new HashSet<AlertMaster>(0);
	private Set<AlertMaster> alertMastersForAlertModeId = new HashSet<AlertMaster>(0);

	public Lookup() {
	}

	public Lookup(int id, String category, String value) {
		this.id = id;
		this.category = category;
		this.value = value;
	}

	public Lookup(int id, String category, String value, String createdBy, Date createOn, String modifiedBy,
			Date modifiedOn, Boolean isDeleted, Set<AlertMaster> alertMastersForSeverityId,
			Set<AlertMaster> alertMastersForAlertModeId) {
		this.id = id;
		this.category = category;
		this.value = value;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.alertMastersForSeverityId = alertMastersForSeverityId;
		this.alertMastersForAlertModeId = alertMastersForAlertModeId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Category", nullable = false, length = 25)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Value", nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createOn", length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lookupBySeverityId")
	public Set<AlertMaster> getAlertMastersForSeverityId() {
		return this.alertMastersForSeverityId;
	}

	public void setAlertMastersForSeverityId(Set<AlertMaster> alertMastersForSeverityId) {
		this.alertMastersForSeverityId = alertMastersForSeverityId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lookupByAlertModeId")
	public Set<AlertMaster> getAlertMastersForAlertModeId() {
		return this.alertMastersForAlertModeId;
	}

	public void setAlertMastersForAlertModeId(Set<AlertMaster> alertMastersForAlertModeId) {
		this.alertMastersForAlertModeId = alertMastersForAlertModeId;
	}

}
