package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "Menu", schema = "dbo", catalog = "FMS4.0")
public class Menu implements java.io.Serializable {

	private int id;
	private Serializable name;
	private Character type;
	private Integer parentId;
	private String url;
	private Boolean isActive;
	private String description;
	private Integer menuOrder;
	private Integer subMenuOrder;
	private String createdBy;
	private Date createdOn;
	private String modifiedBy;
	private Date modifiedOn;
	private Boolean isDeleted;
	private Serializable controller;
	private Serializable action;

	public Menu() {
	}

	public Menu(int id) {
		this.id = id;
	}

	public Menu(int id, Serializable name, Character type, Integer parentId, String url, Boolean isActive,
			String description, Integer menuOrder, Integer subMenuOrder, String createdBy, Date createdOn,
			String modifiedBy, Date modifiedOn, Boolean isDeleted, Serializable controller, Serializable action) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.parentId = parentId;
		this.url = url;
		this.isActive = isActive;
		this.description = description;
		this.menuOrder = menuOrder;
		this.subMenuOrder = subMenuOrder;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.controller = controller;
		this.action = action;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "ParentId")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MenuOrder")
	public Integer getMenuOrder() {
		return this.menuOrder;
	}

	public void setMenuOrder(Integer menuOrder) {
		this.menuOrder = menuOrder;
	}

	@Column(name = "SubMenuOrder")
	public Integer getSubMenuOrder() {
		return this.subMenuOrder;
	}

	public void setSubMenuOrder(Integer subMenuOrder) {
		this.subMenuOrder = subMenuOrder;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "Controller")
	public Serializable getController() {
		return this.controller;
	}

	public void setController(Serializable controller) {
		this.controller = controller;
	}

	@Column(name = "Action")
	public Serializable getAction() {
		return this.action;
	}

	public void setAction(Serializable action) {
		this.action = action;
	}

}
