package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "Notifications", schema = "dbo", catalog = "FMS4.0")
public class Notifications implements java.io.Serializable {

	private NotificationsId id;
	private Integer groupId;
	private Serializable vehicleNumber;
	private int alertType;
	private Serializable param1;
	private Serializable param2;
	private Serializable param3;
	private Serializable param4;
	private Serializable param5;
	private Serializable param6;
	private Serializable param7;
	private Serializable param8;
	private Integer activeTrip;
	private Integer fleetId;
	private Double lat;
	private Double long_;
	private Serializable param9;
	private Boolean status;
	private Serializable param10;
	private Serializable etatime;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Serializable createdBy;
	private Date createdOn;
	private Integer panicStatus;
	private Double speed;
	private Date createddatetime;
	private Date modifieddatetime;

	public Notifications() {
	}

	public Notifications(NotificationsId id, int alertType) {
		this.id = id;
		this.alertType = alertType;
	}

	public Notifications(NotificationsId id, Integer groupId, Serializable vehicleNumber, int alertType,
			Serializable param1, Serializable param2, Serializable param3, Serializable param4, Serializable param5,
			Serializable param6, Serializable param7, Serializable param8, Integer activeTrip, Integer fleetId,
			Double lat, Double long_, Serializable param9, Boolean status, Serializable param10, Serializable etatime,
			Serializable modifiedBy, Date modifiedOn, Serializable createdBy, Date createdOn, Integer panicStatus,
			Double speed, Date createddatetime, Date modifieddatetime) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleNumber = vehicleNumber;
		this.alertType = alertType;
		this.param1 = param1;
		this.param2 = param2;
		this.param3 = param3;
		this.param4 = param4;
		this.param5 = param5;
		this.param6 = param6;
		this.param7 = param7;
		this.param8 = param8;
		this.activeTrip = activeTrip;
		this.fleetId = fleetId;
		this.lat = lat;
		this.long_ = long_;
		this.param9 = param9;
		this.status = status;
		this.param10 = param10;
		this.etatime = etatime;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.panicStatus = panicStatus;
		this.speed = speed;
		this.createddatetime = createddatetime;
		this.modifieddatetime = modifieddatetime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "alertTime", column = @Column(name = "AlertTime", nullable = false, length = 23)) })
	public NotificationsId getId() {
		return this.id;
	}

	public void setId(NotificationsId id) {
		this.id = id;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleNumber")
	public Serializable getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(Serializable vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "AlertType", nullable = false)
	public int getAlertType() {
		return this.alertType;
	}

	public void setAlertType(int alertType) {
		this.alertType = alertType;
	}

	@Column(name = "Param1")
	public Serializable getParam1() {
		return this.param1;
	}

	public void setParam1(Serializable param1) {
		this.param1 = param1;
	}

	@Column(name = "Param2")
	public Serializable getParam2() {
		return this.param2;
	}

	public void setParam2(Serializable param2) {
		this.param2 = param2;
	}

	@Column(name = "Param3")
	public Serializable getParam3() {
		return this.param3;
	}

	public void setParam3(Serializable param3) {
		this.param3 = param3;
	}

	@Column(name = "Param4")
	public Serializable getParam4() {
		return this.param4;
	}

	public void setParam4(Serializable param4) {
		this.param4 = param4;
	}

	@Column(name = "Param5")
	public Serializable getParam5() {
		return this.param5;
	}

	public void setParam5(Serializable param5) {
		this.param5 = param5;
	}

	@Column(name = "Param6")
	public Serializable getParam6() {
		return this.param6;
	}

	public void setParam6(Serializable param6) {
		this.param6 = param6;
	}

	@Column(name = "Param7")
	public Serializable getParam7() {
		return this.param7;
	}

	public void setParam7(Serializable param7) {
		this.param7 = param7;
	}

	@Column(name = "Param8")
	public Serializable getParam8() {
		return this.param8;
	}

	public void setParam8(Serializable param8) {
		this.param8 = param8;
	}

	@Column(name = "ActiveTrip")
	public Integer getActiveTrip() {
		return this.activeTrip;
	}

	public void setActiveTrip(Integer activeTrip) {
		this.activeTrip = activeTrip;
	}

	@Column(name = "FleetId")
	public Integer getFleetId() {
		return this.fleetId;
	}

	public void setFleetId(Integer fleetId) {
		this.fleetId = fleetId;
	}

	@Column(name = "lat", precision = 53, scale = 0)
	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "long", precision = 53, scale = 0)
	public Double getLong_() {
		return this.long_;
	}

	public void setLong_(Double long_) {
		this.long_ = long_;
	}

	@Column(name = "Param9")
	public Serializable getParam9() {
		return this.param9;
	}

	public void setParam9(Serializable param9) {
		this.param9 = param9;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "Param10")
	public Serializable getParam10() {
		return this.param10;
	}

	public void setParam10(Serializable param10) {
		this.param10 = param10;
	}

	@Column(name = "ETAtime")
	public Serializable getEtatime() {
		return this.etatime;
	}

	public void setEtatime(Serializable etatime) {
		this.etatime = etatime;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "PanicStatus")
	public Integer getPanicStatus() {
		return this.panicStatus;
	}

	public void setPanicStatus(Integer panicStatus) {
		this.panicStatus = panicStatus;
	}

	@Column(name = "speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddatetime", length = 23)
	public Date getCreateddatetime() {
		return this.createddatetime;
	}

	public void setCreateddatetime(Date createddatetime) {
		this.createddatetime = createddatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifieddatetime", length = 23)
	public Date getModifieddatetime() {
		return this.modifieddatetime;
	}

	public void setModifieddatetime(Date modifieddatetime) {
		this.modifieddatetime = modifieddatetime;
	}

}
