package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartsDetails generated by hbm2java
 */
@Entity
@Table(name = "PartsDetails", schema = "dbo", catalog = "FMS4.0")
public class PartsDetails implements java.io.Serializable {

	private int id;
	private Serializable partCode;
	private Integer partCategory;
	private Serializable partName;
	private Serializable partDescription;
	private Date purchasedDate;
	private Date expiredDate;
	private Serializable validityInKms;
	private Serializable status;
	private Serializable cost;
	private Serializable vendor;
	private Date createdOn;
	private Date modifiedOn;
	private Date deletedOn;
	private Integer isDeleted;
	private Integer groupId;
	private Integer profileId;
	private Integer isAssigned;
	private Date assignedOn;

	public PartsDetails() {
	}

	public PartsDetails(int id) {
		this.id = id;
	}

	public PartsDetails(int id, Serializable partCode, Integer partCategory, Serializable partName,
			Serializable partDescription, Date purchasedDate, Date expiredDate, Serializable validityInKms,
			Serializable status, Serializable cost, Serializable vendor, Date createdOn, Date modifiedOn,
			Date deletedOn, Integer isDeleted, Integer groupId, Integer profileId, Integer isAssigned,
			Date assignedOn) {
		this.id = id;
		this.partCode = partCode;
		this.partCategory = partCategory;
		this.partName = partName;
		this.partDescription = partDescription;
		this.purchasedDate = purchasedDate;
		this.expiredDate = expiredDate;
		this.validityInKms = validityInKms;
		this.status = status;
		this.cost = cost;
		this.vendor = vendor;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.deletedOn = deletedOn;
		this.isDeleted = isDeleted;
		this.groupId = groupId;
		this.profileId = profileId;
		this.isAssigned = isAssigned;
		this.assignedOn = assignedOn;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "PartCode")
	public Serializable getPartCode() {
		return this.partCode;
	}

	public void setPartCode(Serializable partCode) {
		this.partCode = partCode;
	}

	@Column(name = "PartCategory")
	public Integer getPartCategory() {
		return this.partCategory;
	}

	public void setPartCategory(Integer partCategory) {
		this.partCategory = partCategory;
	}

	@Column(name = "PartName")
	public Serializable getPartName() {
		return this.partName;
	}

	public void setPartName(Serializable partName) {
		this.partName = partName;
	}

	@Column(name = "PartDescription")
	public Serializable getPartDescription() {
		return this.partDescription;
	}

	public void setPartDescription(Serializable partDescription) {
		this.partDescription = partDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PurchasedDate", length = 23)
	public Date getPurchasedDate() {
		return this.purchasedDate;
	}

	public void setPurchasedDate(Date purchasedDate) {
		this.purchasedDate = purchasedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpiredDate", length = 23)
	public Date getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}

	@Column(name = "ValidityInKms")
	public Serializable getValidityInKms() {
		return this.validityInKms;
	}

	public void setValidityInKms(Serializable validityInKms) {
		this.validityInKms = validityInKms;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "Cost")
	public Serializable getCost() {
		return this.cost;
	}

	public void setCost(Serializable cost) {
		this.cost = cost;
	}

	@Column(name = "Vendor")
	public Serializable getVendor() {
		return this.vendor;
	}

	public void setVendor(Serializable vendor) {
		this.vendor = vendor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedOn", length = 23)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ProfileId")
	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	@Column(name = "IsAssigned")
	public Integer getIsAssigned() {
		return this.isAssigned;
	}

	public void setIsAssigned(Integer isAssigned) {
		this.isAssigned = isAssigned;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AssignedOn", length = 23)
	public Date getAssignedOn() {
		return this.assignedOn;
	}

	public void setAssignedOn(Date assignedOn) {
		this.assignedOn = assignedOn;
	}

}
