package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartsCategory generated by hbm2java
 */
@Entity
@Table(name = "PartsCategory", schema = "dbo", catalog = "FMS4.0")
public class PartsCategory implements java.io.Serializable {

	private int id;
	private Serializable category;
	private Serializable description;
	private Date createdOn;
	private Date modifiedOn;
	private Date deletedOn;
	private Integer isDeleted;
	private Integer companyId;
	private Integer groupId;

	public PartsCategory() {
	}

	public PartsCategory(int id) {
		this.id = id;
	}

	public PartsCategory(int id, Serializable category, Serializable description, Date createdOn, Date modifiedOn,
			Date deletedOn, Integer isDeleted, Integer companyId, Integer groupId) {
		this.id = id;
		this.category = category;
		this.description = description;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.deletedOn = deletedOn;
		this.isDeleted = isDeleted;
		this.companyId = companyId;
		this.groupId = groupId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Category")
	public Serializable getCategory() {
		return this.category;
	}

	public void setCategory(Serializable category) {
		this.category = category;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedOn", length = 23)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CompanyId")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

}
