package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartsMaintenence generated by hbm2java
 */
@Entity
@Table(name = "PartsMaintenence", schema = "dbo", catalog = "FMS4.0")
public class PartsMaintenence implements java.io.Serializable {

	private int id;
	private Serializable vehicleId;
	private Serializable partCode;
	private Serializable partName;
	private Integer quantity;
	private Serializable issuedBy;
	private Serializable receivedBy;
	private Date issuedDate;
	private Serializable remarks;
	private Date createdOn;
	private Date modifiedOn;
	private Date deletedOn;
	private Integer isDeleted;
	private Integer partsCategory;
	private Integer groupId;
	private Integer profileId;
	private Integer partId;
	private Double odoMeter;

	public PartsMaintenence() {
	}

	public PartsMaintenence(int id) {
		this.id = id;
	}

	public PartsMaintenence(int id, Serializable vehicleId, Serializable partCode, Serializable partName,
			Integer quantity, Serializable issuedBy, Serializable receivedBy, Date issuedDate, Serializable remarks,
			Date createdOn, Date modifiedOn, Date deletedOn, Integer isDeleted, Integer partsCategory, Integer groupId,
			Integer profileId, Integer partId, Double odoMeter) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.partCode = partCode;
		this.partName = partName;
		this.quantity = quantity;
		this.issuedBy = issuedBy;
		this.receivedBy = receivedBy;
		this.issuedDate = issuedDate;
		this.remarks = remarks;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.deletedOn = deletedOn;
		this.isDeleted = isDeleted;
		this.partsCategory = partsCategory;
		this.groupId = groupId;
		this.profileId = profileId;
		this.partId = partId;
		this.odoMeter = odoMeter;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VehicleId")
	public Serializable getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Serializable vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "PartCode")
	public Serializable getPartCode() {
		return this.partCode;
	}

	public void setPartCode(Serializable partCode) {
		this.partCode = partCode;
	}

	@Column(name = "PartName")
	public Serializable getPartName() {
		return this.partName;
	}

	public void setPartName(Serializable partName) {
		this.partName = partName;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "IssuedBy")
	public Serializable getIssuedBy() {
		return this.issuedBy;
	}

	public void setIssuedBy(Serializable issuedBy) {
		this.issuedBy = issuedBy;
	}

	@Column(name = "ReceivedBy")
	public Serializable getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(Serializable receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IssuedDate", length = 23)
	public Date getIssuedDate() {
		return this.issuedDate;
	}

	public void setIssuedDate(Date issuedDate) {
		this.issuedDate = issuedDate;
	}

	@Column(name = "Remarks")
	public Serializable getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Serializable remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedOn", length = 23)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "PartsCategory")
	public Integer getPartsCategory() {
		return this.partsCategory;
	}

	public void setPartsCategory(Integer partsCategory) {
		this.partsCategory = partsCategory;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ProfileId")
	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	@Column(name = "PartId")
	public Integer getPartId() {
		return this.partId;
	}

	public void setPartId(Integer partId) {
		this.partId = partId;
	}

	@Column(name = "OdoMeter", precision = 53, scale = 0)
	public Double getOdoMeter() {
		return this.odoMeter;
	}

	public void setOdoMeter(Double odoMeter) {
		this.odoMeter = odoMeter;
	}

}
