package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passengers generated by hbm2java
 */
@Entity
@Table(name = "Passengers", schema = "dbo", catalog = "FMS4.0")
public class Passengers implements java.io.Serializable {

	private PassengersId id;
	private int groupId;
	private String studentName;
	private Serializable lastName;
	private Date dob;
	private String fatherName;
	private String motherName;
	private String guardianName;
	private String gender;
	private int country;
	private int state;
	private int district;
	private int city;
	private String address1;
	private String address2;
	private String zipCode;
	private String mobileNo;
	private String phoneNo1;
	private String phoneNo2;
	private Serializable email;
	private int pickupPoint;
	private int dropPoint;
	private Date pickupTime;
	private Date dropTime;
	private int pickupRouteId;
	private int dropRouteId;
	private Boolean isDeleted;
	private Boolean smsAlert;
	private Boolean emailAlert;
	private Serializable ruleType;
	private Serializable etaptime;
	private Serializable etadtime;
	private Serializable busPassNo;
	private Boolean rfidSmsalert;
	private Date createdOn;

	public Passengers() {
	}

	public Passengers(PassengersId id, int groupId, String studentName, Date dob, String fatherName, String motherName,
			String gender, int country, int state, int district, int city, String address1, String zipCode,
			String phoneNo1, Serializable email, int pickupPoint, int dropPoint, Date pickupTime, Date dropTime,
			int pickupRouteId, int dropRouteId) {
		this.id = id;
		this.groupId = groupId;
		this.studentName = studentName;
		this.dob = dob;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.gender = gender;
		this.country = country;
		this.state = state;
		this.district = district;
		this.city = city;
		this.address1 = address1;
		this.zipCode = zipCode;
		this.phoneNo1 = phoneNo1;
		this.email = email;
		this.pickupPoint = pickupPoint;
		this.dropPoint = dropPoint;
		this.pickupTime = pickupTime;
		this.dropTime = dropTime;
		this.pickupRouteId = pickupRouteId;
		this.dropRouteId = dropRouteId;
	}

	public Passengers(PassengersId id, int groupId, String studentName, Serializable lastName, Date dob,
			String fatherName, String motherName, String guardianName, String gender, int country, int state,
			int district, int city, String address1, String address2, String zipCode, String mobileNo, String phoneNo1,
			String phoneNo2, Serializable email, int pickupPoint, int dropPoint, Date pickupTime, Date dropTime,
			int pickupRouteId, int dropRouteId, Boolean isDeleted, Boolean smsAlert, Boolean emailAlert,
			Serializable ruleType, Serializable etaptime, Serializable etadtime, Serializable busPassNo,
			Boolean rfidSmsalert, Date createdOn) {
		this.id = id;
		this.groupId = groupId;
		this.studentName = studentName;
		this.lastName = lastName;
		this.dob = dob;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.guardianName = guardianName;
		this.gender = gender;
		this.country = country;
		this.state = state;
		this.district = district;
		this.city = city;
		this.address1 = address1;
		this.address2 = address2;
		this.zipCode = zipCode;
		this.mobileNo = mobileNo;
		this.phoneNo1 = phoneNo1;
		this.phoneNo2 = phoneNo2;
		this.email = email;
		this.pickupPoint = pickupPoint;
		this.dropPoint = dropPoint;
		this.pickupTime = pickupTime;
		this.dropTime = dropTime;
		this.pickupRouteId = pickupRouteId;
		this.dropRouteId = dropRouteId;
		this.isDeleted = isDeleted;
		this.smsAlert = smsAlert;
		this.emailAlert = emailAlert;
		this.ruleType = ruleType;
		this.etaptime = etaptime;
		this.etadtime = etadtime;
		this.busPassNo = busPassNo;
		this.rfidSmsalert = rfidSmsalert;
		this.createdOn = createdOn;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "profileId", column = @Column(name = "ProfileID", nullable = false)),
			@AttributeOverride(name = "tagId", column = @Column(name = "TagId", nullable = false, length = 50)) })
	public PassengersId getId() {
		return this.id;
	}

	public void setId(PassengersId id) {
		this.id = id;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "StudentName", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "LastName")
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", nullable = false, length = 23)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "FatherName", nullable = false, length = 50)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "MotherName", nullable = false, length = 50)
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "GuardianName", length = 50)
	public String getGuardianName() {
		return this.guardianName;
	}

	public void setGuardianName(String guardianName) {
		this.guardianName = guardianName;
	}

	@Column(name = "Gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Country", nullable = false)
	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	@Column(name = "State", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "District", nullable = false)
	public int getDistrict() {
		return this.district;
	}

	public void setDistrict(int district) {
		this.district = district;
	}

	@Column(name = "City", nullable = false)
	public int getCity() {
		return this.city;
	}

	public void setCity(int city) {
		this.city = city;
	}

	@Column(name = "Address1", nullable = false, length = 250)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 250)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ZipCode", nullable = false, length = 7)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "MobileNo", length = 100)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "PhoneNo1", nullable = false, length = 15)
	public String getPhoneNo1() {
		return this.phoneNo1;
	}

	public void setPhoneNo1(String phoneNo1) {
		this.phoneNo1 = phoneNo1;
	}

	@Column(name = "PhoneNo2", length = 15)
	public String getPhoneNo2() {
		return this.phoneNo2;
	}

	public void setPhoneNo2(String phoneNo2) {
		this.phoneNo2 = phoneNo2;
	}

	@Column(name = "Email", nullable = false)
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "PickupPoint", nullable = false)
	public int getPickupPoint() {
		return this.pickupPoint;
	}

	public void setPickupPoint(int pickupPoint) {
		this.pickupPoint = pickupPoint;
	}

	@Column(name = "DropPoint", nullable = false)
	public int getDropPoint() {
		return this.dropPoint;
	}

	public void setDropPoint(int dropPoint) {
		this.dropPoint = dropPoint;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "PickupTime", nullable = false, length = 16)
	public Date getPickupTime() {
		return this.pickupTime;
	}

	public void setPickupTime(Date pickupTime) {
		this.pickupTime = pickupTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "DropTime", nullable = false, length = 16)
	public Date getDropTime() {
		return this.dropTime;
	}

	public void setDropTime(Date dropTime) {
		this.dropTime = dropTime;
	}

	@Column(name = "PickupRouteID", nullable = false)
	public int getPickupRouteId() {
		return this.pickupRouteId;
	}

	public void setPickupRouteId(int pickupRouteId) {
		this.pickupRouteId = pickupRouteId;
	}

	@Column(name = "DropRouteID", nullable = false)
	public int getDropRouteId() {
		return this.dropRouteId;
	}

	public void setDropRouteId(int dropRouteId) {
		this.dropRouteId = dropRouteId;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "SmsAlert")
	public Boolean getSmsAlert() {
		return this.smsAlert;
	}

	public void setSmsAlert(Boolean smsAlert) {
		this.smsAlert = smsAlert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "RuleType")
	public Serializable getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(Serializable ruleType) {
		this.ruleType = ruleType;
	}

	@Column(name = "ETAPTime")
	public Serializable getEtaptime() {
		return this.etaptime;
	}

	public void setEtaptime(Serializable etaptime) {
		this.etaptime = etaptime;
	}

	@Column(name = "ETADTime")
	public Serializable getEtadtime() {
		return this.etadtime;
	}

	public void setEtadtime(Serializable etadtime) {
		this.etadtime = etadtime;
	}

	@Column(name = "BusPassNo")
	public Serializable getBusPassNo() {
		return this.busPassNo;
	}

	public void setBusPassNo(Serializable busPassNo) {
		this.busPassNo = busPassNo;
	}

	@Column(name = "RfidSMSAlert")
	public Boolean getRfidSmsalert() {
		return this.rfidSmsalert;
	}

	public void setRfidSmsalert(Boolean rfidSmsalert) {
		this.rfidSmsalert = rfidSmsalert;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
