package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectType generated by hbm2java
 */
@Entity
@Table(name = "ProjectType", schema = "dbo", catalog = "FMS4.0")
public class ProjectType implements java.io.Serializable {

	private int id;
	private Integer comapnyId;
	private Integer groupId;
	private Serializable projectType;
	private Serializable loginTime;
	private Serializable logoutTime;
	private Boolean isdeleted;
	private Serializable createdBy;
	private Serializable modifiedBy;
	private Date createdOn;
	private Date modifiedOn;
	private Serializable email;

	public ProjectType() {
	}

	public ProjectType(int id) {
		this.id = id;
	}

	public ProjectType(int id, Integer comapnyId, Integer groupId, Serializable projectType, Serializable loginTime,
			Serializable logoutTime, Boolean isdeleted, Serializable createdBy, Serializable modifiedBy, Date createdOn,
			Date modifiedOn, Serializable email) {
		this.id = id;
		this.comapnyId = comapnyId;
		this.groupId = groupId;
		this.projectType = projectType;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.email = email;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ComapnyID")
	public Integer getComapnyId() {
		return this.comapnyId;
	}

	public void setComapnyId(Integer comapnyId) {
		this.comapnyId = comapnyId;
	}

	@Column(name = "GroupID")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ProjectType")
	public Serializable getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Serializable projectType) {
		this.projectType = projectType;
	}

	@Column(name = "LoginTime")
	public Serializable getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Serializable loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "LogoutTime")
	public Serializable getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Serializable logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

}
