package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reportspdtl generated by hbm2java
 */
@Entity
@Table(name = "reportspdtl", schema = "dbo", catalog = "FMS4.0")
public class Reportspdtl implements java.io.Serializable {

	private ReportspdtlId id;
	private ReportSpMaster reportSpMaster;

	public Reportspdtl() {
	}

	public Reportspdtl(ReportspdtlId id, ReportSpMaster reportSpMaster) {
		this.id = id;
		this.reportSpMaster = reportSpMaster;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "menuId", column = @Column(name = "MenuId", nullable = false)),
			@AttributeOverride(name = "specificName", column = @Column(name = "SPECIFIC_NAME", nullable = false)),
			@AttributeOverride(name = "ordinalPosition", column = @Column(name = "ORDINAL_POSITION", nullable = false)),
			@AttributeOverride(name = "parameterMode", column = @Column(name = "PARAMETER_MODE")),
			@AttributeOverride(name = "parameterName", column = @Column(name = "PARAMETER_NAME")),
			@AttributeOverride(name = "dataType", column = @Column(name = "DATA_TYPE", nullable = false)),
			@AttributeOverride(name = "characterMaximumLength", column = @Column(name = "CHARACTER_MAXIMUM_LENGTH")),
			@AttributeOverride(name = "specificCatalog", column = @Column(name = "SPECIFIC_CATALOG")),
			@AttributeOverride(name = "specificSchema", column = @Column(name = "SPECIFIC_SCHEMA")) })
	public ReportspdtlId getId() {
		return this.id;
	}

	public void setId(ReportspdtlId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MenuId", nullable = false, insertable = false, updatable = false)
	public ReportSpMaster getReportSpMaster() {
		return this.reportSpMaster;
	}

	public void setReportSpMaster(ReportSpMaster reportSpMaster) {
		this.reportSpMaster = reportSpMaster;
	}

}
