package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReportSpMaster generated by hbm2java
 */
@Entity
@Table(name = "ReportSpMaster", schema = "dbo", catalog = "FMS4.0")
public class ReportSpMaster implements java.io.Serializable {

	private int menuId;
	private int id;
	private Serializable menuName;
	private Serializable spName;
	private Integer isDeleted;
	private Set<Reportspdtl> reportspdtls = new HashSet<Reportspdtl>(0);

	public ReportSpMaster() {
	}

	public ReportSpMaster(int menuId, int id) {
		this.menuId = menuId;
		this.id = id;
	}

	public ReportSpMaster(int menuId, int id, Serializable menuName, Serializable spName, Integer isDeleted,
			Set<Reportspdtl> reportspdtls) {
		this.menuId = menuId;
		this.id = id;
		this.menuName = menuName;
		this.spName = spName;
		this.isDeleted = isDeleted;
		this.reportspdtls = reportspdtls;
	}

	@Id

	@Column(name = "MenuId", unique = true, nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MenuName")
	public Serializable getMenuName() {
		return this.menuName;
	}

	public void setMenuName(Serializable menuName) {
		this.menuName = menuName;
	}

	@Column(name = "SpName")
	public Serializable getSpName() {
		return this.spName;
	}

	public void setSpName(Serializable spName) {
		this.spName = spName;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportSpMaster")
	public Set<Reportspdtl> getReportspdtls() {
		return this.reportspdtls;
	}

	public void setReportspdtls(Set<Reportspdtl> reportspdtls) {
		this.reportspdtls = reportspdtls;
	}

}
