package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReportspdtlId generated by hbm2java
 */
@Embeddable
public class ReportspdtlId implements java.io.Serializable {

	private int id;
	private int menuId;
	private Serializable specificName;
	private int ordinalPosition;
	private Serializable parameterMode;
	private Serializable parameterName;
	private Serializable dataType;
	private Integer characterMaximumLength;
	private Serializable specificCatalog;
	private Serializable specificSchema;

	public ReportspdtlId() {
	}

	public ReportspdtlId(int id, int menuId, Serializable specificName, int ordinalPosition, Serializable dataType) {
		this.id = id;
		this.menuId = menuId;
		this.specificName = specificName;
		this.ordinalPosition = ordinalPosition;
		this.dataType = dataType;
	}

	public ReportspdtlId(int id, int menuId, Serializable specificName, int ordinalPosition, Serializable parameterMode,
			Serializable parameterName, Serializable dataType, Integer characterMaximumLength,
			Serializable specificCatalog, Serializable specificSchema) {
		this.id = id;
		this.menuId = menuId;
		this.specificName = specificName;
		this.ordinalPosition = ordinalPosition;
		this.parameterMode = parameterMode;
		this.parameterName = parameterName;
		this.dataType = dataType;
		this.characterMaximumLength = characterMaximumLength;
		this.specificCatalog = specificCatalog;
		this.specificSchema = specificSchema;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MenuId", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "SPECIFIC_NAME", nullable = false)
	public Serializable getSpecificName() {
		return this.specificName;
	}

	public void setSpecificName(Serializable specificName) {
		this.specificName = specificName;
	}

	@Column(name = "ORDINAL_POSITION", nullable = false)
	public int getOrdinalPosition() {
		return this.ordinalPosition;
	}

	public void setOrdinalPosition(int ordinalPosition) {
		this.ordinalPosition = ordinalPosition;
	}

	@Column(name = "PARAMETER_MODE")
	public Serializable getParameterMode() {
		return this.parameterMode;
	}

	public void setParameterMode(Serializable parameterMode) {
		this.parameterMode = parameterMode;
	}

	@Column(name = "PARAMETER_NAME")
	public Serializable getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(Serializable parameterName) {
		this.parameterName = parameterName;
	}

	@Column(name = "DATA_TYPE", nullable = false)
	public Serializable getDataType() {
		return this.dataType;
	}

	public void setDataType(Serializable dataType) {
		this.dataType = dataType;
	}

	@Column(name = "CHARACTER_MAXIMUM_LENGTH")
	public Integer getCharacterMaximumLength() {
		return this.characterMaximumLength;
	}

	public void setCharacterMaximumLength(Integer characterMaximumLength) {
		this.characterMaximumLength = characterMaximumLength;
	}

	@Column(name = "SPECIFIC_CATALOG")
	public Serializable getSpecificCatalog() {
		return this.specificCatalog;
	}

	public void setSpecificCatalog(Serializable specificCatalog) {
		this.specificCatalog = specificCatalog;
	}

	@Column(name = "SPECIFIC_SCHEMA")
	public Serializable getSpecificSchema() {
		return this.specificSchema;
	}

	public void setSpecificSchema(Serializable specificSchema) {
		this.specificSchema = specificSchema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReportspdtlId))
			return false;
		ReportspdtlId castOther = (ReportspdtlId) other;

		return (this.getId() == castOther.getId()) && (this.getMenuId() == castOther.getMenuId())
				&& ((this.getSpecificName() == castOther.getSpecificName())
						|| (this.getSpecificName() != null && castOther.getSpecificName() != null
								&& this.getSpecificName().equals(castOther.getSpecificName())))
				&& (this.getOrdinalPosition() == castOther.getOrdinalPosition())
				&& ((this.getParameterMode() == castOther.getParameterMode())
						|| (this.getParameterMode() != null && castOther.getParameterMode() != null
								&& this.getParameterMode().equals(castOther.getParameterMode())))
				&& ((this.getParameterName() == castOther.getParameterName())
						|| (this.getParameterName() != null && castOther.getParameterName() != null
								&& this.getParameterName().equals(castOther.getParameterName())))
				&& ((this.getDataType() == castOther.getDataType()) || (this.getDataType() != null
						&& castOther.getDataType() != null && this.getDataType().equals(castOther.getDataType())))
				&& ((this.getCharacterMaximumLength() == castOther.getCharacterMaximumLength())
						|| (this.getCharacterMaximumLength() != null && castOther.getCharacterMaximumLength() != null
								&& this.getCharacterMaximumLength().equals(castOther.getCharacterMaximumLength())))
				&& ((this.getSpecificCatalog() == castOther.getSpecificCatalog())
						|| (this.getSpecificCatalog() != null && castOther.getSpecificCatalog() != null
								&& this.getSpecificCatalog().equals(castOther.getSpecificCatalog())))
				&& ((this.getSpecificSchema() == castOther.getSpecificSchema())
						|| (this.getSpecificSchema() != null && castOther.getSpecificSchema() != null
								&& this.getSpecificSchema().equals(castOther.getSpecificSchema())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getMenuId();
		result = 37 * result + (getSpecificName() == null ? 0 : this.getSpecificName().hashCode());
		result = 37 * result + this.getOrdinalPosition();
		result = 37 * result + (getParameterMode() == null ? 0 : this.getParameterMode().hashCode());
		result = 37 * result + (getParameterName() == null ? 0 : this.getParameterName().hashCode());
		result = 37 * result + (getDataType() == null ? 0 : this.getDataType().hashCode());
		result = 37 * result + (getCharacterMaximumLength() == null ? 0 : this.getCharacterMaximumLength().hashCode());
		result = 37 * result + (getSpecificCatalog() == null ? 0 : this.getSpecificCatalog().hashCode());
		result = 37 * result + (getSpecificSchema() == null ? 0 : this.getSpecificSchema().hashCode());
		return result;
	}

}
