package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Routelog generated by hbm2java
 */
@Entity
@Table(name = "Routelog", schema = "dbo", catalog = "FMS4.0")
public class Routelog implements java.io.Serializable {

	private RoutelogId id;

	public Routelog() {
	}

	public Routelog(RoutelogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "routename", column = @Column(name = "ROutename", length = 50)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedON", length = 23)),
			@AttributeOverride(name = "rsource", column = @Column(name = "RSource", length = 50)),
			@AttributeOverride(name = "mode", column = @Column(name = "Mode", length = 50)),
			@AttributeOverride(name = "routeLog", column = @Column(name = "RouteLog", length = 500)),
			@AttributeOverride(name = "routeEtalog", column = @Column(name = "RouteETALog", length = 500)) })
	public RoutelogId getId() {
		return this.id;
	}

	public void setId(RoutelogId id) {
		this.id = id;
	}

}
