package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "States", schema = "dbo", catalog = "FMS4.0")
public class States implements java.io.Serializable {

	private long stateId;
	private int countryId;
	private String stateName;
	private Boolean isdeleted;

	public States() {
	}

	public States(long stateId, int countryId, String stateName) {
		this.stateId = stateId;
		this.countryId = countryId;
		this.stateName = stateName;
	}

	public States(long stateId, int countryId, String stateName, Boolean isdeleted) {
		this.stateId = stateId;
		this.countryId = countryId;
		this.stateName = stateName;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "StateId", unique = true, nullable = false)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

	@Column(name = "CountryID", nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Column(name = "StateName", nullable = false, length = 100)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
