package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAlertOptions generated by hbm2java
 */
@Entity
@Table(name = "tblAlertOptions", schema = "dbo", catalog = "FMS4.0")
public class TblAlertOptions implements java.io.Serializable {

	private int alertId;
	private Integer profileId;
	private Boolean pickupAtHome;
	private Boolean dropAtSchool;
	private Boolean pickupAtSchool;
	private Boolean dropAtHome;
	private Boolean etahomePickup;
	private Boolean etahomeDrop;
	private Boolean isEtapickUpByTime;
	private Boolean isEtapickUpByWayPoint;
	private Boolean isEtadropByTime;
	private Boolean isEtadropByWayPioint;
	private Date etapickUpByTime;
	private Integer etapickUpByWayPoint;
	private Date etadropByTime;
	private Integer etadropByWayPoint;

	public TblAlertOptions() {
	}

	public TblAlertOptions(int alertId) {
		this.alertId = alertId;
	}

	public TblAlertOptions(int alertId, Integer profileId, Boolean pickupAtHome, Boolean dropAtSchool,
			Boolean pickupAtSchool, Boolean dropAtHome, Boolean etahomePickup, Boolean etahomeDrop,
			Boolean isEtapickUpByTime, Boolean isEtapickUpByWayPoint, Boolean isEtadropByTime,
			Boolean isEtadropByWayPioint, Date etapickUpByTime, Integer etapickUpByWayPoint, Date etadropByTime,
			Integer etadropByWayPoint) {
		this.alertId = alertId;
		this.profileId = profileId;
		this.pickupAtHome = pickupAtHome;
		this.dropAtSchool = dropAtSchool;
		this.pickupAtSchool = pickupAtSchool;
		this.dropAtHome = dropAtHome;
		this.etahomePickup = etahomePickup;
		this.etahomeDrop = etahomeDrop;
		this.isEtapickUpByTime = isEtapickUpByTime;
		this.isEtapickUpByWayPoint = isEtapickUpByWayPoint;
		this.isEtadropByTime = isEtadropByTime;
		this.isEtadropByWayPioint = isEtadropByWayPioint;
		this.etapickUpByTime = etapickUpByTime;
		this.etapickUpByWayPoint = etapickUpByWayPoint;
		this.etadropByTime = etadropByTime;
		this.etadropByWayPoint = etadropByWayPoint;
	}

	@Id

	@Column(name = "AlertId", unique = true, nullable = false)
	public int getAlertId() {
		return this.alertId;
	}

	public void setAlertId(int alertId) {
		this.alertId = alertId;
	}

	@Column(name = "ProfileID")
	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	@Column(name = "PickupAtHome")
	public Boolean getPickupAtHome() {
		return this.pickupAtHome;
	}

	public void setPickupAtHome(Boolean pickupAtHome) {
		this.pickupAtHome = pickupAtHome;
	}

	@Column(name = "DropAtSchool")
	public Boolean getDropAtSchool() {
		return this.dropAtSchool;
	}

	public void setDropAtSchool(Boolean dropAtSchool) {
		this.dropAtSchool = dropAtSchool;
	}

	@Column(name = "PickupAtSchool")
	public Boolean getPickupAtSchool() {
		return this.pickupAtSchool;
	}

	public void setPickupAtSchool(Boolean pickupAtSchool) {
		this.pickupAtSchool = pickupAtSchool;
	}

	@Column(name = "DropAtHome")
	public Boolean getDropAtHome() {
		return this.dropAtHome;
	}

	public void setDropAtHome(Boolean dropAtHome) {
		this.dropAtHome = dropAtHome;
	}

	@Column(name = "ETAHomePickup")
	public Boolean getEtahomePickup() {
		return this.etahomePickup;
	}

	public void setEtahomePickup(Boolean etahomePickup) {
		this.etahomePickup = etahomePickup;
	}

	@Column(name = "ETAHomeDrop")
	public Boolean getEtahomeDrop() {
		return this.etahomeDrop;
	}

	public void setEtahomeDrop(Boolean etahomeDrop) {
		this.etahomeDrop = etahomeDrop;
	}

	@Column(name = "IsETAPickUpByTime")
	public Boolean getIsEtapickUpByTime() {
		return this.isEtapickUpByTime;
	}

	public void setIsEtapickUpByTime(Boolean isEtapickUpByTime) {
		this.isEtapickUpByTime = isEtapickUpByTime;
	}

	@Column(name = "IsETAPickUpByWayPoint")
	public Boolean getIsEtapickUpByWayPoint() {
		return this.isEtapickUpByWayPoint;
	}

	public void setIsEtapickUpByWayPoint(Boolean isEtapickUpByWayPoint) {
		this.isEtapickUpByWayPoint = isEtapickUpByWayPoint;
	}

	@Column(name = "IsETADropByTime")
	public Boolean getIsEtadropByTime() {
		return this.isEtadropByTime;
	}

	public void setIsEtadropByTime(Boolean isEtadropByTime) {
		this.isEtadropByTime = isEtadropByTime;
	}

	@Column(name = "IsETADropByWayPioint")
	public Boolean getIsEtadropByWayPioint() {
		return this.isEtadropByWayPioint;
	}

	public void setIsEtadropByWayPioint(Boolean isEtadropByWayPioint) {
		this.isEtadropByWayPioint = isEtadropByWayPioint;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ETAPickUpByTime", length = 16)
	public Date getEtapickUpByTime() {
		return this.etapickUpByTime;
	}

	public void setEtapickUpByTime(Date etapickUpByTime) {
		this.etapickUpByTime = etapickUpByTime;
	}

	@Column(name = "ETAPickUpByWayPoint")
	public Integer getEtapickUpByWayPoint() {
		return this.etapickUpByWayPoint;
	}

	public void setEtapickUpByWayPoint(Integer etapickUpByWayPoint) {
		this.etapickUpByWayPoint = etapickUpByWayPoint;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ETADropByTime", length = 16)
	public Date getEtadropByTime() {
		return this.etadropByTime;
	}

	public void setEtadropByTime(Date etadropByTime) {
		this.etadropByTime = etadropByTime;
	}

	@Column(name = "ETADropByWayPoint")
	public Integer getEtadropByWayPoint() {
		return this.etadropByWayPoint;
	}

	public void setEtadropByWayPoint(Integer etadropByWayPoint) {
		this.etadropByWayPoint = etadropByWayPoint;
	}

}
