package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblAndroidAppUsageDetailsId generated by hbm2java
 */
@Embeddable
public class TblAndroidAppUsageDetailsId implements java.io.Serializable {

	private int id;
	private Serializable loginId;
	private Serializable imeinumber;
	private Serializable appName;
	private Serializable details;
	private Date createdOn;
	private Date modifiedOn;

	public TblAndroidAppUsageDetailsId() {
	}

	public TblAndroidAppUsageDetailsId(int id) {
		this.id = id;
	}

	public TblAndroidAppUsageDetailsId(int id, Serializable loginId, Serializable imeinumber, Serializable appName,
			Serializable details, Date createdOn, Date modifiedOn) {
		this.id = id;
		this.loginId = loginId;
		this.imeinumber = imeinumber;
		this.appName = appName;
		this.details = details;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LoginID")
	public Serializable getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Serializable loginId) {
		this.loginId = loginId;
	}

	@Column(name = "IMEINumber")
	public Serializable getImeinumber() {
		return this.imeinumber;
	}

	public void setImeinumber(Serializable imeinumber) {
		this.imeinumber = imeinumber;
	}

	@Column(name = "AppName")
	public Serializable getAppName() {
		return this.appName;
	}

	public void setAppName(Serializable appName) {
		this.appName = appName;
	}

	@Column(name = "Details")
	public Serializable getDetails() {
		return this.details;
	}

	public void setDetails(Serializable details) {
		this.details = details;
	}

	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblAndroidAppUsageDetailsId))
			return false;
		TblAndroidAppUsageDetailsId castOther = (TblAndroidAppUsageDetailsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getLoginId() == castOther.getLoginId()) || (this.getLoginId() != null
						&& castOther.getLoginId() != null && this.getLoginId().equals(castOther.getLoginId())))
				&& ((this.getImeinumber() == castOther.getImeinumber()) || (this.getImeinumber() != null
						&& castOther.getImeinumber() != null && this.getImeinumber().equals(castOther.getImeinumber())))
				&& ((this.getAppName() == castOther.getAppName()) || (this.getAppName() != null
						&& castOther.getAppName() != null && this.getAppName().equals(castOther.getAppName())))
				&& ((this.getDetails() == castOther.getDetails()) || (this.getDetails() != null
						&& castOther.getDetails() != null && this.getDetails().equals(castOther.getDetails())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn())
						|| (this.getModifiedOn() != null && castOther.getModifiedOn() != null
								&& this.getModifiedOn().equals(castOther.getModifiedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result + (getImeinumber() == null ? 0 : this.getImeinumber().hashCode());
		result = 37 * result + (getAppName() == null ? 0 : this.getAppName().hashCode());
		result = 37 * result + (getDetails() == null ? 0 : this.getDetails().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		return result;
	}

}
