package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblAndroidAppUsageDetails generated by hbm2java
 */
@Entity
@Table(name = "tblAndroidAppUsageDetails", schema = "dbo", catalog = "FMS4.0")
public class TblAndroidAppUsageDetails implements java.io.Serializable {

	private TblAndroidAppUsageDetailsId id;

	public TblAndroidAppUsageDetails() {
	}

	public TblAndroidAppUsageDetails(TblAndroidAppUsageDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "loginId", column = @Column(name = "LoginID")),
			@AttributeOverride(name = "imeinumber", column = @Column(name = "IMEINumber")),
			@AttributeOverride(name = "appName", column = @Column(name = "AppName")),
			@AttributeOverride(name = "details", column = @Column(name = "Details")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)) })
	public TblAndroidAppUsageDetailsId getId() {
		return this.id;
	}

	public void setId(TblAndroidAppUsageDetailsId id) {
		this.id = id;
	}

}
