package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAndroidAppRequestDetails generated by hbm2java
 */
@Entity
@Table(name = "tblAndroidAppRequestDetails", schema = "dbo", catalog = "FMS4.0")
public class TblAndroidAppRequestDetails implements java.io.Serializable {

	private int id;
	private Serializable appName;
	private Serializable appVersion;
	private Serializable loginId;
	private Serializable typeOfRequest;
	private Serializable statusOfRequest;
	private Date createdOnUtc;
	private Serializable requestDateIst;
	private Integer totalRequest;

	public TblAndroidAppRequestDetails() {
	}

	public TblAndroidAppRequestDetails(int id) {
		this.id = id;
	}

	public TblAndroidAppRequestDetails(int id, Serializable appName, Serializable appVersion, Serializable loginId,
			Serializable typeOfRequest, Serializable statusOfRequest, Date createdOnUtc, Serializable requestDateIst,
			Integer totalRequest) {
		this.id = id;
		this.appName = appName;
		this.appVersion = appVersion;
		this.loginId = loginId;
		this.typeOfRequest = typeOfRequest;
		this.statusOfRequest = statusOfRequest;
		this.createdOnUtc = createdOnUtc;
		this.requestDateIst = requestDateIst;
		this.totalRequest = totalRequest;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "AppName")
	public Serializable getAppName() {
		return this.appName;
	}

	public void setAppName(Serializable appName) {
		this.appName = appName;
	}

	@Column(name = "AppVersion")
	public Serializable getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(Serializable appVersion) {
		this.appVersion = appVersion;
	}

	@Column(name = "LoginId")
	public Serializable getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Serializable loginId) {
		this.loginId = loginId;
	}

	@Column(name = "TypeOfRequest")
	public Serializable getTypeOfRequest() {
		return this.typeOfRequest;
	}

	public void setTypeOfRequest(Serializable typeOfRequest) {
		this.typeOfRequest = typeOfRequest;
	}

	@Column(name = "StatusOfRequest")
	public Serializable getStatusOfRequest() {
		return this.statusOfRequest;
	}

	public void setStatusOfRequest(Serializable statusOfRequest) {
		this.statusOfRequest = statusOfRequest;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOnUtc", length = 23)
	public Date getCreatedOnUtc() {
		return this.createdOnUtc;
	}

	public void setCreatedOnUtc(Date createdOnUtc) {
		this.createdOnUtc = createdOnUtc;
	}

	@Column(name = "RequestDateIST")
	public Serializable getRequestDateIst() {
		return this.requestDateIst;
	}

	public void setRequestDateIst(Serializable requestDateIst) {
		this.requestDateIst = requestDateIst;
	}

	@Column(name = "TotalRequest")
	public Integer getTotalRequest() {
		return this.totalRequest;
	}

	public void setTotalRequest(Integer totalRequest) {
		this.totalRequest = totalRequest;
	}

}
