package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAutoSchedular generated by hbm2java
 */
@Entity
@Table(name = "TblAutoSchedular", schema = "dbo", catalog = "FMS4.0")
public class TblAutoSchedular implements java.io.Serializable {

	private int id;
	private int groupId;
	private int reportTypeId;
	private Serializable reportName;
	private Serializable toMailId;
	private Serializable ccmailId;
	private Date scheduleTime;
	private int scheduleType;
	private boolean isdeleted;
	private Serializable createdBy;
	private Serializable modifiedBy;
	private Date createdOn;
	private Date modifiedOn;

	public TblAutoSchedular() {
	}

	public TblAutoSchedular(int id, int groupId, int reportTypeId, Serializable toMailId, Date scheduleTime,
			int scheduleType, boolean isdeleted) {
		this.id = id;
		this.groupId = groupId;
		this.reportTypeId = reportTypeId;
		this.toMailId = toMailId;
		this.scheduleTime = scheduleTime;
		this.scheduleType = scheduleType;
		this.isdeleted = isdeleted;
	}

	public TblAutoSchedular(int id, int groupId, int reportTypeId, Serializable reportName, Serializable toMailId,
			Serializable ccmailId, Date scheduleTime, int scheduleType, boolean isdeleted, Serializable createdBy,
			Serializable modifiedBy, Date createdOn, Date modifiedOn) {
		this.id = id;
		this.groupId = groupId;
		this.reportTypeId = reportTypeId;
		this.reportName = reportName;
		this.toMailId = toMailId;
		this.ccmailId = ccmailId;
		this.scheduleTime = scheduleTime;
		this.scheduleType = scheduleType;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ReportTypeId", nullable = false)
	public int getReportTypeId() {
		return this.reportTypeId;
	}

	public void setReportTypeId(int reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	@Column(name = "ReportName")
	public Serializable getReportName() {
		return this.reportName;
	}

	public void setReportName(Serializable reportName) {
		this.reportName = reportName;
	}

	@Column(name = "ToMailId", nullable = false)
	public Serializable getToMailId() {
		return this.toMailId;
	}

	public void setToMailId(Serializable toMailId) {
		this.toMailId = toMailId;
	}

	@Column(name = "CcmailId")
	public Serializable getCcmailId() {
		return this.ccmailId;
	}

	public void setCcmailId(Serializable ccmailId) {
		this.ccmailId = ccmailId;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ScheduleTime", nullable = false, length = 16)
	public Date getScheduleTime() {
		return this.scheduleTime;
	}

	public void setScheduleTime(Date scheduleTime) {
		this.scheduleTime = scheduleTime;
	}

	@Column(name = "ScheduleType", nullable = false)
	public int getScheduleType() {
		return this.scheduleType;
	}

	public void setScheduleType(int scheduleType) {
		this.scheduleType = scheduleType;
	}

	@Column(name = "Isdeleted", nullable = false)
	public boolean isIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
