package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblAaemailSmsrequestDetails generated by hbm2java
 */
@Entity
@Table(name = "tblAAEmailSMSRequestDetails", schema = "dbo", catalog = "FMS4.0")
public class TblAaemailSmsrequestDetails implements java.io.Serializable {

	private int id;
	private int aaemailSmsrequestType;
	private Serializable description;
	private Serializable smsemailFormat;
	private Serializable subject;

	public TblAaemailSmsrequestDetails() {
	}

	public TblAaemailSmsrequestDetails(int id, int aaemailSmsrequestType, Serializable description) {
		this.id = id;
		this.aaemailSmsrequestType = aaemailSmsrequestType;
		this.description = description;
	}

	public TblAaemailSmsrequestDetails(int id, int aaemailSmsrequestType, Serializable description,
			Serializable smsemailFormat, Serializable subject) {
		this.id = id;
		this.aaemailSmsrequestType = aaemailSmsrequestType;
		this.description = description;
		this.smsemailFormat = smsemailFormat;
		this.subject = subject;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "AAEmailSMSRequestType", nullable = false)
	public int getAaemailSmsrequestType() {
		return this.aaemailSmsrequestType;
	}

	public void setAaemailSmsrequestType(int aaemailSmsrequestType) {
		this.aaemailSmsrequestType = aaemailSmsrequestType;
	}

	@Column(name = "Description", nullable = false)
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "SMSEmailFormat")
	public Serializable getSmsemailFormat() {
		return this.smsemailFormat;
	}

	public void setSmsemailFormat(Serializable smsemailFormat) {
		this.smsemailFormat = smsemailFormat;
	}

	@Column(name = "Subject")
	public Serializable getSubject() {
		return this.subject;
	}

	public void setSubject(Serializable subject) {
		this.subject = subject;
	}

}
