package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAaemailSmsDetails generated by hbm2java
 */
@Entity
@Table(name = "tblAAEmailSmsDetails", schema = "dbo", catalog = "FMS4.0")
public class TblAaemailSmsDetails implements java.io.Serializable {

	private int id;
	private int groupId;
	private int employeeId;
	private int requestId;
	private int requestType;
	private Serializable employeeEmailId;
	private Serializable employeeMobileNo;
	private Serializable managerEmailId;
	private Serializable managerMobileNo;
	private Serializable taemailId;
	private Serializable tamobileNo;
	private Serializable emailSentStatus;
	private Serializable smssentStatus;
	private Boolean status;
	private Boolean isEmailEnabled;
	private Boolean isSmsEnabled;
	private Boolean isDeleted;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;

	public TblAaemailSmsDetails() {
	}

	public TblAaemailSmsDetails(int id, int groupId, int employeeId, int requestId, int requestType) {
		this.id = id;
		this.groupId = groupId;
		this.employeeId = employeeId;
		this.requestId = requestId;
		this.requestType = requestType;
	}

	public TblAaemailSmsDetails(int id, int groupId, int employeeId, int requestId, int requestType,
			Serializable employeeEmailId, Serializable employeeMobileNo, Serializable managerEmailId,
			Serializable managerMobileNo, Serializable taemailId, Serializable tamobileNo, Serializable emailSentStatus,
			Serializable smssentStatus, Boolean status, Boolean isEmailEnabled, Boolean isSmsEnabled, Boolean isDeleted,
			Date createdOn, Serializable createdBy, Date modifiedOn, Serializable modifiedBy) {
		this.id = id;
		this.groupId = groupId;
		this.employeeId = employeeId;
		this.requestId = requestId;
		this.requestType = requestType;
		this.employeeEmailId = employeeEmailId;
		this.employeeMobileNo = employeeMobileNo;
		this.managerEmailId = managerEmailId;
		this.managerMobileNo = managerMobileNo;
		this.taemailId = taemailId;
		this.tamobileNo = tamobileNo;
		this.emailSentStatus = emailSentStatus;
		this.smssentStatus = smssentStatus;
		this.status = status;
		this.isEmailEnabled = isEmailEnabled;
		this.isSmsEnabled = isSmsEnabled;
		this.isDeleted = isDeleted;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "EmployeeId", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "RequestId", nullable = false)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@Column(name = "RequestType", nullable = false)
	public int getRequestType() {
		return this.requestType;
	}

	public void setRequestType(int requestType) {
		this.requestType = requestType;
	}

	@Column(name = "EmployeeEmailId")
	public Serializable getEmployeeEmailId() {
		return this.employeeEmailId;
	}

	public void setEmployeeEmailId(Serializable employeeEmailId) {
		this.employeeEmailId = employeeEmailId;
	}

	@Column(name = "EmployeeMobileNo")
	public Serializable getEmployeeMobileNo() {
		return this.employeeMobileNo;
	}

	public void setEmployeeMobileNo(Serializable employeeMobileNo) {
		this.employeeMobileNo = employeeMobileNo;
	}

	@Column(name = "ManagerEmailId")
	public Serializable getManagerEmailId() {
		return this.managerEmailId;
	}

	public void setManagerEmailId(Serializable managerEmailId) {
		this.managerEmailId = managerEmailId;
	}

	@Column(name = "ManagerMobileNo")
	public Serializable getManagerMobileNo() {
		return this.managerMobileNo;
	}

	public void setManagerMobileNo(Serializable managerMobileNo) {
		this.managerMobileNo = managerMobileNo;
	}

	@Column(name = "TAEmailId")
	public Serializable getTaemailId() {
		return this.taemailId;
	}

	public void setTaemailId(Serializable taemailId) {
		this.taemailId = taemailId;
	}

	@Column(name = "TAMobileNo")
	public Serializable getTamobileNo() {
		return this.tamobileNo;
	}

	public void setTamobileNo(Serializable tamobileNo) {
		this.tamobileNo = tamobileNo;
	}

	@Column(name = "EmailSentStatus")
	public Serializable getEmailSentStatus() {
		return this.emailSentStatus;
	}

	public void setEmailSentStatus(Serializable emailSentStatus) {
		this.emailSentStatus = emailSentStatus;
	}

	@Column(name = "SMSSentStatus")
	public Serializable getSmssentStatus() {
		return this.smssentStatus;
	}

	public void setSmssentStatus(Serializable smssentStatus) {
		this.smssentStatus = smssentStatus;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "IsEmailEnabled")
	public Boolean getIsEmailEnabled() {
		return this.isEmailEnabled;
	}

	public void setIsEmailEnabled(Boolean isEmailEnabled) {
		this.isEmailEnabled = isEmailEnabled;
	}

	@Column(name = "IsSmsEnabled")
	public Boolean getIsSmsEnabled() {
		return this.isSmsEnabled;
	}

	public void setIsSmsEnabled(Boolean isSmsEnabled) {
		this.isSmsEnabled = isSmsEnabled;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
