package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAreaWaypoint generated by hbm2java
 */
@Entity
@Table(name = "tblAreaWaypoint", schema = "dbo", catalog = "FMS4.0")
public class TblAreaWaypoint implements java.io.Serializable {

	private int id;
	private int areaId;
	private int waypointId;
	private int groupId;
	private Boolean isDeleted;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;

	public TblAreaWaypoint() {
	}

	public TblAreaWaypoint(int id, int areaId, int waypointId, int groupId) {
		this.id = id;
		this.areaId = areaId;
		this.waypointId = waypointId;
		this.groupId = groupId;
	}

	public TblAreaWaypoint(int id, int areaId, int waypointId, int groupId, Boolean isDeleted, Date createdOn,
			Serializable createdBy, Date modifiedOn, Serializable modifiedBy) {
		this.id = id;
		this.areaId = areaId;
		this.waypointId = waypointId;
		this.groupId = groupId;
		this.isDeleted = isDeleted;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "AreaId", nullable = false)
	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	@Column(name = "WaypointId", nullable = false)
	public int getWaypointId() {
		return this.waypointId;
	}

	public void setWaypointId(int waypointId) {
		this.waypointId = waypointId;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
