package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAutoShedule generated by hbm2java
 */
@Entity
@Table(name = "tblAutoShedule", schema = "dbo", catalog = "FMS4.0")
public class TblAutoShedule implements java.io.Serializable {

	private int id;
	private int groupId;
	private Integer userId;
	private Serializable sessionId;
	private Serializable groupName;
	private Date sheduledOn;
	private byte[] listOfWaypoints;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;

	public TblAutoShedule() {
	}

	public TblAutoShedule(int id, int groupId) {
		this.id = id;
		this.groupId = groupId;
	}

	public TblAutoShedule(int id, int groupId, Integer userId, Serializable sessionId, Serializable groupName,
			Date sheduledOn, byte[] listOfWaypoints, Date createdOn, Serializable createdBy, Date modifiedOn,
			Serializable modifiedBy) {
		this.id = id;
		this.groupId = groupId;
		this.userId = userId;
		this.sessionId = sessionId;
		this.groupName = groupName;
		this.sheduledOn = sheduledOn;
		this.listOfWaypoints = listOfWaypoints;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "SessionId")
	public Serializable getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Serializable sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "GroupName")
	public Serializable getGroupName() {
		return this.groupName;
	}

	public void setGroupName(Serializable groupName) {
		this.groupName = groupName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SheduledOn", length = 23)
	public Date getSheduledOn() {
		return this.sheduledOn;
	}

	public void setSheduledOn(Date sheduledOn) {
		this.sheduledOn = sheduledOn;
	}

	@Column(name = "ListOfWaypoints")
	public byte[] getListOfWaypoints() {
		return this.listOfWaypoints;
	}

	public void setListOfWaypoints(byte[] listOfWaypoints) {
		this.listOfWaypoints = listOfWaypoints;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
