package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCabRequests generated by hbm2java
 */
@Entity
@Table(name = "tblCabRequests", schema = "dbo", catalog = "FMS4.0")
public class TblCabRequests implements java.io.Serializable {

	private int requestId;
	private Integer groupId;
	private Serializable firstName;
	private Serializable lastName;
	private Serializable mobileNo;
	private Serializable email;
	private Serializable fromPlace;
	private Serializable landmark;
	private Serializable toPlace;
	private Date fromDate;
	private Date toDate;
	private Integer tripId;
	private Integer status;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Integer isDeleted;

	public TblCabRequests() {
	}

	public TblCabRequests(int requestId) {
		this.requestId = requestId;
	}

	public TblCabRequests(int requestId, Integer groupId, Serializable firstName, Serializable lastName,
			Serializable mobileNo, Serializable email, Serializable fromPlace, Serializable landmark,
			Serializable toPlace, Date fromDate, Date toDate, Integer tripId, Integer status, Serializable createdBy,
			Date createdOn, Serializable modifiedBy, Date modifiedOn, Integer isDeleted) {
		this.requestId = requestId;
		this.groupId = groupId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.email = email;
		this.fromPlace = fromPlace;
		this.landmark = landmark;
		this.toPlace = toPlace;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.tripId = tripId;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "RequestID", unique = true, nullable = false)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "FirstName")
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName")
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MobileNo")
	public Serializable getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Serializable mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "FromPlace")
	public Serializable getFromPlace() {
		return this.fromPlace;
	}

	public void setFromPlace(Serializable fromPlace) {
		this.fromPlace = fromPlace;
	}

	@Column(name = "Landmark")
	public Serializable getLandmark() {
		return this.landmark;
	}

	public void setLandmark(Serializable landmark) {
		this.landmark = landmark;
	}

	@Column(name = "ToPlace")
	public Serializable getToPlace() {
		return this.toPlace;
	}

	public void setToPlace(Serializable toPlace) {
		this.toPlace = toPlace;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FromDate", length = 23)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ToDate", length = 23)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "TripID")
	public Integer getTripId() {
		return this.tripId;
	}

	public void setTripId(Integer tripId) {
		this.tripId = tripId;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "IsDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
