package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TblDailyVehicleActivity generated by hbm2java
 */
@Entity
@Table(name = "TblDailyVehicleActivity", schema = "dbo", catalog = "FMS4.0")
public class TblDailyVehicleActivity implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private int groupId;
	private Serializable vehicleRegNo;
	private Double speed;
	private Double lat;
	private Double long_;
	private Serializable location;
	private Serializable category;
	private Integer timeDiff;
	private Double distance;
	private Integer idleTime;
	private Integer stoppageTime;
	private Integer chk;
	private Double odometer;
	private Long ignition;

	public TblDailyVehicleActivity() {
	}

	public TblDailyVehicleActivity(int id, int groupId, Serializable vehicleRegNo) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleRegNo = vehicleRegNo;
	}

	public TblDailyVehicleActivity(int id, int groupId, Serializable vehicleRegNo, Double speed, Double lat,
			Double long_, Serializable location, Serializable category, Integer timeDiff, Double distance,
			Integer idleTime, Integer stoppageTime, Integer chk, Double odometer, Long ignition) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleRegNo = vehicleRegNo;
		this.speed = speed;
		this.lat = lat;
		this.long_ = long_;
		this.location = location;
		this.category = category;
		this.timeDiff = timeDiff;
		this.distance = distance;
		this.idleTime = idleTime;
		this.stoppageTime = stoppageTime;
		this.chk = chk;
		this.odometer = odometer;
		this.ignition = ignition;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleRegNo", nullable = false)
	public Serializable getVehicleRegNo() {
		return this.vehicleRegNo;
	}

	public void setVehicleRegNo(Serializable vehicleRegNo) {
		this.vehicleRegNo = vehicleRegNo;
	}

	@Column(name = "Speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Column(name = "Lat", precision = 53, scale = 0)
	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "Long", precision = 53, scale = 0)
	public Double getLong_() {
		return this.long_;
	}

	public void setLong_(Double long_) {
		this.long_ = long_;
	}

	@Column(name = "Location")
	public Serializable getLocation() {
		return this.location;
	}

	public void setLocation(Serializable location) {
		this.location = location;
	}

	@Column(name = "Category")
	public Serializable getCategory() {
		return this.category;
	}

	public void setCategory(Serializable category) {
		this.category = category;
	}

	@Column(name = "TimeDiff")
	public Integer getTimeDiff() {
		return this.timeDiff;
	}

	public void setTimeDiff(Integer timeDiff) {
		this.timeDiff = timeDiff;
	}

	@Column(name = "Distance", precision = 53, scale = 0)
	public Double getDistance() {
		return this.distance;
	}

	public void setDistance(Double distance) {
		this.distance = distance;
	}

	@Column(name = "IdleTime")
	public Integer getIdleTime() {
		return this.idleTime;
	}

	public void setIdleTime(Integer idleTime) {
		this.idleTime = idleTime;
	}

	@Column(name = "StoppageTime")
	public Integer getStoppageTime() {
		return this.stoppageTime;
	}

	public void setStoppageTime(Integer stoppageTime) {
		this.stoppageTime = stoppageTime;
	}

	@Column(name = "Chk")
	public Integer getChk() {
		return this.chk;
	}

	public void setChk(Integer chk) {
		this.chk = chk;
	}

	@Column(name = "odometer", precision = 53, scale = 0)
	public Double getOdometer() {
		return this.odometer;
	}

	public void setOdometer(Double odometer) {
		this.odometer = odometer;
	}

	@Column(name = "Ignition", precision = 10, scale = 0)
	public Long getIgnition() {
		return this.ignition;
	}

	public void setIgnition(Long ignition) {
		this.ignition = ignition;
	}

}
