package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLastReportTime generated by hbm2java
 */
@Entity
@Table(name = "TblLastReportTime", schema = "dbo", catalog = "FMS4.0")
public class TblLastReportTime implements java.io.Serializable {

	private int id;
	private int tblAutoSchedularId;
	private Date lastSentTime;
	private Serializable createdBy;
	private Date createdOn;
	private Date modifiedOn;
	private Serializable modifiedBy;

	public TblLastReportTime() {
	}

	public TblLastReportTime(int id, int tblAutoSchedularId, Date lastSentTime) {
		this.id = id;
		this.tblAutoSchedularId = tblAutoSchedularId;
		this.lastSentTime = lastSentTime;
	}

	public TblLastReportTime(int id, int tblAutoSchedularId, Date lastSentTime, Serializable createdBy, Date createdOn,
			Date modifiedOn, Serializable modifiedBy) {
		this.id = id;
		this.tblAutoSchedularId = tblAutoSchedularId;
		this.lastSentTime = lastSentTime;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TblAutoSchedularId", nullable = false)
	public int getTblAutoSchedularId() {
		return this.tblAutoSchedularId;
	}

	public void setTblAutoSchedularId(int tblAutoSchedularId) {
		this.tblAutoSchedularId = tblAutoSchedularId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastSentTime", nullable = false, length = 23)
	public Date getLastSentTime() {
		return this.lastSentTime;
	}

	public void setLastSentTime(Date lastSentTime) {
		this.lastSentTime = lastSentTime;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
