package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblLocationdataforRetail generated by hbm2java
 */
@Entity
@Table(name = "TblLocationdataforRetail", schema = "dbo", catalog = "FMS4.0")
public class TblLocationdataforRetail implements java.io.Serializable {

	private int id;
	private int waypointId;
	private Boolean smsalert;
	private Boolean emailAlert;
	private Serializable mobileno;
	private Serializable email;
	private Boolean locationIn;
	private Boolean locationOut;
	private Integer userId;

	public TblLocationdataforRetail() {
	}

	public TblLocationdataforRetail(int id, int waypointId) {
		this.id = id;
		this.waypointId = waypointId;
	}

	public TblLocationdataforRetail(int id, int waypointId, Boolean smsalert, Boolean emailAlert, Serializable mobileno,
			Serializable email, Boolean locationIn, Boolean locationOut, Integer userId) {
		this.id = id;
		this.waypointId = waypointId;
		this.smsalert = smsalert;
		this.emailAlert = emailAlert;
		this.mobileno = mobileno;
		this.email = email;
		this.locationIn = locationIn;
		this.locationOut = locationOut;
		this.userId = userId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "WaypointID", nullable = false)
	public int getWaypointId() {
		return this.waypointId;
	}

	public void setWaypointId(int waypointId) {
		this.waypointId = waypointId;
	}

	@Column(name = "SMSAlert")
	public Boolean getSmsalert() {
		return this.smsalert;
	}

	public void setSmsalert(Boolean smsalert) {
		this.smsalert = smsalert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

	@Column(name = "Mobileno")
	public Serializable getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(Serializable mobileno) {
		this.mobileno = mobileno;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "LocationIn")
	public Boolean getLocationIn() {
		return this.locationIn;
	}

	public void setLocationIn(Boolean locationIn) {
		this.locationIn = locationIn;
	}

	@Column(name = "LocationOut")
	public Boolean getLocationOut() {
		return this.locationOut;
	}

	public void setLocationOut(Boolean locationOut) {
		this.locationOut = locationOut;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
