package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMasterVehicleModel generated by hbm2java
 */
@Entity
@Table(name = "tblMasterVehicleModel", schema = "dbo", catalog = "FMS4.0")
public class TblMasterVehicleModel implements java.io.Serializable {

	private int id;
	private Serializable name;
	private double fuelCapacity;
	private int vehicleId;
	private Serializable createdBy;
	private Date createdOn;
	private Boolean isDeleted;

	public TblMasterVehicleModel() {
	}

	public TblMasterVehicleModel(int id, double fuelCapacity, int vehicleId) {
		this.id = id;
		this.fuelCapacity = fuelCapacity;
		this.vehicleId = vehicleId;
	}

	public TblMasterVehicleModel(int id, Serializable name, double fuelCapacity, int vehicleId, Serializable createdBy,
			Date createdOn, Boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.fuelCapacity = fuelCapacity;
		this.vehicleId = vehicleId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "FuelCapacity", nullable = false, precision = 53, scale = 0)
	public double getFuelCapacity() {
		return this.fuelCapacity;
	}

	public void setFuelCapacity(double fuelCapacity) {
		this.fuelCapacity = fuelCapacity;
	}

	@Column(name = "VehicleID", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
