package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblMasterFuelCaliberationTemp generated by hbm2java
 */
@Entity
@Table(name = "tblMasterFuelCaliberationTemp", schema = "dbo", catalog = "FMS4.0")
public class TblMasterFuelCaliberationTemp implements java.io.Serializable {

	private TblMasterFuelCaliberationTempId id;

	public TblMasterFuelCaliberationTemp() {
	}

	public TblMasterFuelCaliberationTemp(TblMasterFuelCaliberationTempId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "modelTypeId", column = @Column(name = "ModelTypeID", nullable = false)),
			@AttributeOverride(name = "fuelVolume", column = @Column(name = "FuelVolume", precision = 53, scale = 0)),
			@AttributeOverride(name = "voltage", column = @Column(name = "Voltage", precision = 53, scale = 0)) })
	public TblMasterFuelCaliberationTempId getId() {
		return this.id;
	}

	public void setId(TblMasterFuelCaliberationTempId id) {
		this.id = id;
	}

}
