package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMasterFuelCaliberation generated by hbm2java
 */
@Entity
@Table(name = "tblMasterFuelCaliberation", schema = "dbo", catalog = "FMS4.0")
public class TblMasterFuelCaliberation implements java.io.Serializable {

	private int id;
	private int modelTypeId;
	private Double fuelVolume;
	private Double voltage;
	private Serializable createdBy;
	private Date createdOn;
	private Boolean isDeleted;

	public TblMasterFuelCaliberation() {
	}

	public TblMasterFuelCaliberation(int id, int modelTypeId) {
		this.id = id;
		this.modelTypeId = modelTypeId;
	}

	public TblMasterFuelCaliberation(int id, int modelTypeId, Double fuelVolume, Double voltage, Serializable createdBy,
			Date createdOn, Boolean isDeleted) {
		this.id = id;
		this.modelTypeId = modelTypeId;
		this.fuelVolume = fuelVolume;
		this.voltage = voltage;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ModelTypeID", nullable = false)
	public int getModelTypeId() {
		return this.modelTypeId;
	}

	public void setModelTypeId(int modelTypeId) {
		this.modelTypeId = modelTypeId;
	}

	@Column(name = "FuelVolume", precision = 53, scale = 0)
	public Double getFuelVolume() {
		return this.fuelVolume;
	}

	public void setFuelVolume(Double fuelVolume) {
		this.fuelVolume = fuelVolume;
	}

	@Column(name = "Voltage", precision = 53, scale = 0)
	public Double getVoltage() {
		return this.voltage;
	}

	public void setVoltage(Double voltage) {
		this.voltage = voltage;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
