package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblMailhistory generated by hbm2java
 */
@Entity
@Table(name = "TBL_MAILHISTORY", schema = "dbo", catalog = "FMS4.0")
public class TblMailhistory implements java.io.Serializable {

	private TblMailhistoryId id;

	public TblMailhistory() {
	}

	public TblMailhistory(TblMailhistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "tomail", column = @Column(name = "TOMAIL")),
			@AttributeOverride(name = "subject", column = @Column(name = "SUBJECT")),
			@AttributeOverride(name = "mbody", column = @Column(name = "MBODY")),
			@AttributeOverride(name = "ismaildelivered", column = @Column(name = "ISMAILDELIVERED")),
			@AttributeOverride(name = "createdby", column = @Column(name = "CREATEDBY", length = 75)),
			@AttributeOverride(name = "createdon", column = @Column(name = "CREATEDON", length = 10)),
			@AttributeOverride(name = "modifiedby", column = @Column(name = "MODIFIEDBY", length = 75)),
			@AttributeOverride(name = "modifiedon", column = @Column(name = "MODIFIEDON", length = 10)),
			@AttributeOverride(name = "priority", column = @Column(name = "PRIORITY")),
			@AttributeOverride(name = "attempts", column = @Column(name = "ATTEMPTS")),
			@AttributeOverride(name = "cc", column = @Column(name = "CC")),
			@AttributeOverride(name = "bcc", column = @Column(name = "BCC")) })
	public TblMailhistoryId getId() {
		return this.id;
	}

	public void setId(TblMailhistoryId id) {
		this.id = id;
	}

}
