package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOfferRides generated by hbm2java
 */
@Entity
@Table(name = "tblOfferRides", schema = "dbo", catalog = "FMS4.0")
public class TblOfferRides implements java.io.Serializable {

	private int id;
	private Integer userId;
	private Integer tripType;
	private Serializable fromLocation;
	private Serializable toLocation;
	private Serializable vehicleModel;
	private Serializable vehicleMade;
	private Integer noOfSeats;
	private Boolean isRoundTrip;
	private Serializable outboundDays;
	private Serializable inboundDays;
	private Date departureDate;
	private Date returnDate;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;
	private Boolean isdeleted;
	private byte[] routSegment;
	private Serializable routSegmentString;

	public TblOfferRides() {
	}

	public TblOfferRides(int id) {
		this.id = id;
	}

	public TblOfferRides(int id, Integer userId, Integer tripType, Serializable fromLocation, Serializable toLocation,
			Serializable vehicleModel, Serializable vehicleMade, Integer noOfSeats, Boolean isRoundTrip,
			Serializable outboundDays, Serializable inboundDays, Date departureDate, Date returnDate, Date createdOn,
			Serializable createdBy, Date modifiedOn, Serializable modifiedBy, Boolean isdeleted, byte[] routSegment,
			Serializable routSegmentString) {
		this.id = id;
		this.userId = userId;
		this.tripType = tripType;
		this.fromLocation = fromLocation;
		this.toLocation = toLocation;
		this.vehicleModel = vehicleModel;
		this.vehicleMade = vehicleMade;
		this.noOfSeats = noOfSeats;
		this.isRoundTrip = isRoundTrip;
		this.outboundDays = outboundDays;
		this.inboundDays = inboundDays;
		this.departureDate = departureDate;
		this.returnDate = returnDate;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isdeleted = isdeleted;
		this.routSegment = routSegment;
		this.routSegmentString = routSegmentString;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "TripType")
	public Integer getTripType() {
		return this.tripType;
	}

	public void setTripType(Integer tripType) {
		this.tripType = tripType;
	}

	@Column(name = "FromLocation")
	public Serializable getFromLocation() {
		return this.fromLocation;
	}

	public void setFromLocation(Serializable fromLocation) {
		this.fromLocation = fromLocation;
	}

	@Column(name = "ToLocation")
	public Serializable getToLocation() {
		return this.toLocation;
	}

	public void setToLocation(Serializable toLocation) {
		this.toLocation = toLocation;
	}

	@Column(name = "VehicleModel")
	public Serializable getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(Serializable vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

	@Column(name = "VehicleMade")
	public Serializable getVehicleMade() {
		return this.vehicleMade;
	}

	public void setVehicleMade(Serializable vehicleMade) {
		this.vehicleMade = vehicleMade;
	}

	@Column(name = "NoOfSeats")
	public Integer getNoOfSeats() {
		return this.noOfSeats;
	}

	public void setNoOfSeats(Integer noOfSeats) {
		this.noOfSeats = noOfSeats;
	}

	@Column(name = "IsRoundTrip")
	public Boolean getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Boolean isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}

	@Column(name = "OutboundDays")
	public Serializable getOutboundDays() {
		return this.outboundDays;
	}

	public void setOutboundDays(Serializable outboundDays) {
		this.outboundDays = outboundDays;
	}

	@Column(name = "InboundDays")
	public Serializable getInboundDays() {
		return this.inboundDays;
	}

	public void setInboundDays(Serializable inboundDays) {
		this.inboundDays = inboundDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DepartureDate", length = 23)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReturnDate", length = 23)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "RoutSegment")
	public byte[] getRoutSegment() {
		return this.routSegment;
	}

	public void setRoutSegment(byte[] routSegment) {
		this.routSegment = routSegment;
	}

	@Column(name = "RoutSegmentString")
	public Serializable getRoutSegmentString() {
		return this.routSegmentString;
	}

	public void setRoutSegmentString(Serializable routSegmentString) {
		this.routSegmentString = routSegmentString;
	}

}
