package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblPoi generated by hbm2java
 */
@Entity
@Table(name = "tbl_POI", schema = "dbo", catalog = "FMS4.0")
public class TblPoi implements java.io.Serializable {

	private TblPoiId id;

	public TblPoi() {
	}

	public TblPoi(TblPoiId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "poiNme", column = @Column(name = "POI_NME")),
			@AttributeOverride(name = "poiId", column = @Column(name = "POI_ID")),
			@AttributeOverride(name = "ftrCry", column = @Column(name = "FTR_CRY")),
			@AttributeOverride(name = "desc", column = @Column(name = "DESC")),
			@AttributeOverride(name = "cityNme", column = @Column(name = "CITY_NME")),
			@AttributeOverride(name = "sttNme", column = @Column(name = "STT_NME")),
			@AttributeOverride(name = "cityId", column = @Column(name = "CITY_ID")),
			@AttributeOverride(name = "geom", column = @Column(name = "geom")) })
	public TblPoiId getId() {
		return this.id;
	}

	public void setId(TblPoiId id) {
		this.id = id;
	}

}
