package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblPoiId generated by hbm2java
 */
@Embeddable
public class TblPoiId implements java.io.Serializable {

	private int id;
	private Serializable poiNme;
	private Serializable poiId;
	private Serializable ftrCry;
	private Serializable desc;
	private Serializable cityNme;
	private Serializable sttNme;
	private Long cityId;
	private byte[] geom;

	public TblPoiId() {
	}

	public TblPoiId(int id) {
		this.id = id;
	}

	public TblPoiId(int id, Serializable poiNme, Serializable poiId, Serializable ftrCry, Serializable desc,
			Serializable cityNme, Serializable sttNme, Long cityId, byte[] geom) {
		this.id = id;
		this.poiNme = poiNme;
		this.poiId = poiId;
		this.ftrCry = ftrCry;
		this.desc = desc;
		this.cityNme = cityNme;
		this.sttNme = sttNme;
		this.cityId = cityId;
		this.geom = geom;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "POI_NME")
	public Serializable getPoiNme() {
		return this.poiNme;
	}

	public void setPoiNme(Serializable poiNme) {
		this.poiNme = poiNme;
	}

	@Column(name = "POI_ID")
	public Serializable getPoiId() {
		return this.poiId;
	}

	public void setPoiId(Serializable poiId) {
		this.poiId = poiId;
	}

	@Column(name = "FTR_CRY")
	public Serializable getFtrCry() {
		return this.ftrCry;
	}

	public void setFtrCry(Serializable ftrCry) {
		this.ftrCry = ftrCry;
	}

	@Column(name = "DESC")
	public Serializable getDesc() {
		return this.desc;
	}

	public void setDesc(Serializable desc) {
		this.desc = desc;
	}

	@Column(name = "CITY_NME")
	public Serializable getCityNme() {
		return this.cityNme;
	}

	public void setCityNme(Serializable cityNme) {
		this.cityNme = cityNme;
	}

	@Column(name = "STT_NME")
	public Serializable getSttNme() {
		return this.sttNme;
	}

	public void setSttNme(Serializable sttNme) {
		this.sttNme = sttNme;
	}

	@Column(name = "CITY_ID")
	public Long getCityId() {
		return this.cityId;
	}

	public void setCityId(Long cityId) {
		this.cityId = cityId;
	}

	@Column(name = "geom")
	public byte[] getGeom() {
		return this.geom;
	}

	public void setGeom(byte[] geom) {
		this.geom = geom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPoiId))
			return false;
		TblPoiId castOther = (TblPoiId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getPoiNme() == castOther.getPoiNme()) || (this.getPoiNme() != null
						&& castOther.getPoiNme() != null && this.getPoiNme().equals(castOther.getPoiNme())))
				&& ((this.getPoiId() == castOther.getPoiId()) || (this.getPoiId() != null
						&& castOther.getPoiId() != null && this.getPoiId().equals(castOther.getPoiId())))
				&& ((this.getFtrCry() == castOther.getFtrCry()) || (this.getFtrCry() != null
						&& castOther.getFtrCry() != null && this.getFtrCry().equals(castOther.getFtrCry())))
				&& ((this.getDesc() == castOther.getDesc()) || (this.getDesc() != null && castOther.getDesc() != null
						&& this.getDesc().equals(castOther.getDesc())))
				&& ((this.getCityNme() == castOther.getCityNme()) || (this.getCityNme() != null
						&& castOther.getCityNme() != null && this.getCityNme().equals(castOther.getCityNme())))
				&& ((this.getSttNme() == castOther.getSttNme()) || (this.getSttNme() != null
						&& castOther.getSttNme() != null && this.getSttNme().equals(castOther.getSttNme())))
				&& ((this.getCityId() == castOther.getCityId()) || (this.getCityId() != null
						&& castOther.getCityId() != null && this.getCityId().equals(castOther.getCityId())))
				&& ((this.getGeom() == castOther.getGeom()) || (this.getGeom() != null && castOther.getGeom() != null
						&& Arrays.equals(this.getGeom(), castOther.getGeom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getPoiNme() == null ? 0 : this.getPoiNme().hashCode());
		result = 37 * result + (getPoiId() == null ? 0 : this.getPoiId().hashCode());
		result = 37 * result + (getFtrCry() == null ? 0 : this.getFtrCry().hashCode());
		result = 37 * result + (getDesc() == null ? 0 : this.getDesc().hashCode());
		result = 37 * result + (getCityNme() == null ? 0 : this.getCityNme().hashCode());
		result = 37 * result + (getSttNme() == null ? 0 : this.getSttNme().hashCode());
		result = 37 * result + (getCityId() == null ? 0 : this.getCityId().hashCode());
		result = 37 * result + (getGeom() == null ? 0 : Arrays.hashCode(this.getGeom()));
		return result;
	}

}
