package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblRfidswipeDetails generated by hbm2java
 */
@Entity
@Table(name = "tblRFIDSwipeDetails", schema = "dbo", catalog = "FMS4.0")
public class TblRfidswipeDetails implements java.io.Serializable {

	private TblRfidswipeDetailsId id;

	public TblRfidswipeDetails() {
	}

	public TblRfidswipeDetails(TblRfidswipeDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "tripId", column = @Column(name = "TripID", nullable = false)),
			@AttributeOverride(name = "rfid", column = @Column(name = "RFID", nullable = false)),
			@AttributeOverride(name = "intime", column = @Column(name = "INTime", length = 23)),
			@AttributeOverride(name = "inlat", column = @Column(name = "INLat")),
			@AttributeOverride(name = "inlong", column = @Column(name = "INLong")),
			@AttributeOverride(name = "inwayPoint", column = @Column(name = "INWayPoint")),
			@AttributeOverride(name = "insms", column = @Column(name = "INSms")),
			@AttributeOverride(name = "outtime", column = @Column(name = "OUTTime", length = 23)),
			@AttributeOverride(name = "outlat", column = @Column(name = "OUTLat")),
			@AttributeOverride(name = "outlong", column = @Column(name = "OUTLong")),
			@AttributeOverride(name = "outwayPoint", column = @Column(name = "OUTWayPoint")),
			@AttributeOverride(name = "outsms", column = @Column(name = "OUTSms")),
			@AttributeOverride(name = "pickupOrDrop", column = @Column(name = "PickupOrDrop")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)) })
	public TblRfidswipeDetailsId getId() {
		return this.id;
	}

	public void setId(TblRfidswipeDetailsId id) {
		this.id = id;
	}

}
