package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRouteShedule generated by hbm2java
 */
@Entity
@Table(name = "tblRouteShedule", schema = "dbo", catalog = "FMS4.0")
public class TblRouteShedule implements java.io.Serializable {

	private int id;
	private int routeId;
	private int sheduleId;
	private Boolean isdeleted;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable routeName;

	public TblRouteShedule() {
	}

	public TblRouteShedule(int id, int routeId, int sheduleId) {
		this.id = id;
		this.routeId = routeId;
		this.sheduleId = sheduleId;
	}

	public TblRouteShedule(int id, int routeId, int sheduleId, Boolean isdeleted, Serializable createdBy,
			Date createdOn, Serializable routeName) {
		this.id = id;
		this.routeId = routeId;
		this.sheduleId = sheduleId;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.routeName = routeName;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "RouteId", nullable = false)
	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	@Column(name = "SheduleId", nullable = false)
	public int getSheduleId() {
		return this.sheduleId;
	}

	public void setSheduleId(int sheduleId) {
		this.sheduleId = sheduleId;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "RouteName")
	public Serializable getRouteName() {
		return this.routeName;
	}

	public void setRouteName(Serializable routeName) {
		this.routeName = routeName;
	}

}
