package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblReverseGeocodingId generated by hbm2java
 */
@Embeddable
public class TblReverseGeocodingId implements java.io.Serializable {

	private double lat;
	private double long_;

	public TblReverseGeocodingId() {
	}

	public TblReverseGeocodingId(double lat, double long_) {
		this.lat = lat;
		this.long_ = long_;
	}

	@Column(name = "Lat", nullable = false, precision = 53, scale = 0)
	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	@Column(name = "Long", nullable = false, precision = 53, scale = 0)
	public double getLong_() {
		return this.long_;
	}

	public void setLong_(double long_) {
		this.long_ = long_;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblReverseGeocodingId))
			return false;
		TblReverseGeocodingId castOther = (TblReverseGeocodingId) other;

		return (this.getLat() == castOther.getLat()) && (this.getLong_() == castOther.getLong_());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLat();
		result = 37 * result + (int) this.getLong_();
		return result;
	}

}
