package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblReportScheduler generated by hbm2java
 */
@Entity
@Table(name = "TblReportScheduler", schema = "dbo", catalog = "FMS4.0")
public class TblReportScheduler implements java.io.Serializable {

	private TblReportSchedulerId id;

	public TblReportScheduler() {
	}

	public TblReportScheduler(TblReportSchedulerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "companyId", column = @Column(name = "CompanyId", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupId", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false)),
			@AttributeOverride(name = "reportId", column = @Column(name = "ReportId", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleId", nullable = false)),
			@AttributeOverride(name = "reportName", column = @Column(name = "ReportName", nullable = false)),
			@AttributeOverride(name = "startDate", column = @Column(name = "StartDate", nullable = false, length = 23)),
			@AttributeOverride(name = "endDate", column = @Column(name = "EndDate", nullable = false, length = 23)),
			@AttributeOverride(name = "reportGenTime", column = @Column(name = "ReportGenTime", nullable = false, length = 23)),
			@AttributeOverride(name = "days", column = @Column(name = "Days", nullable = false)),
			@AttributeOverride(name = "emailId", column = @Column(name = "EmailId", nullable = false)),
			@AttributeOverride(name = "format", column = @Column(name = "Format", nullable = false)),
			@AttributeOverride(name = "parameters", column = @Column(name = "Parameters")),
			@AttributeOverride(name = "isdeleted", column = @Column(name = "Isdeleted")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", length = 23)),
			@AttributeOverride(name = "lastReportGenTime", column = @Column(name = "LastReportGenTime", length = 23)) })
	public TblReportSchedulerId getId() {
		return this.id;
	}

	public void setId(TblReportSchedulerId id) {
		this.id = id;
	}

}
