package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblReportSchedulerId generated by hbm2java
 */
@Embeddable
public class TblReportSchedulerId implements java.io.Serializable {

	private int id;
	private int companyId;
	private int groupId;
	private int userId;
	private int reportId;
	private int roleId;
	private Serializable reportName;
	private Date startDate;
	private Date endDate;
	private Date reportGenTime;
	private Serializable days;
	private Serializable emailId;
	private Serializable format;
	private Serializable parameters;
	private Boolean isdeleted;
	private Serializable createdBy;
	private Date createdOn;
	private Date lastReportGenTime;

	public TblReportSchedulerId() {
	}

	public TblReportSchedulerId(int id, int companyId, int groupId, int userId, int reportId, int roleId,
			Serializable reportName, Date startDate, Date endDate, Date reportGenTime, Serializable days,
			Serializable emailId, Serializable format) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.userId = userId;
		this.reportId = reportId;
		this.roleId = roleId;
		this.reportName = reportName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.reportGenTime = reportGenTime;
		this.days = days;
		this.emailId = emailId;
		this.format = format;
	}

	public TblReportSchedulerId(int id, int companyId, int groupId, int userId, int reportId, int roleId,
			Serializable reportName, Date startDate, Date endDate, Date reportGenTime, Serializable days,
			Serializable emailId, Serializable format, Serializable parameters, Boolean isdeleted,
			Serializable createdBy, Date createdOn, Date lastReportGenTime) {
		this.id = id;
		this.companyId = companyId;
		this.groupId = groupId;
		this.userId = userId;
		this.reportId = reportId;
		this.roleId = roleId;
		this.reportName = reportName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.reportGenTime = reportGenTime;
		this.days = days;
		this.emailId = emailId;
		this.format = format;
		this.parameters = parameters;
		this.isdeleted = isdeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastReportGenTime = lastReportGenTime;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CompanyId", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "UserId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "ReportId", nullable = false)
	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	@Column(name = "RoleId", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ReportName", nullable = false)
	public Serializable getReportName() {
		return this.reportName;
	}

	public void setReportName(Serializable reportName) {
		this.reportName = reportName;
	}

	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "EndDate", nullable = false, length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ReportGenTime", nullable = false, length = 23)
	public Date getReportGenTime() {
		return this.reportGenTime;
	}

	public void setReportGenTime(Date reportGenTime) {
		this.reportGenTime = reportGenTime;
	}

	@Column(name = "Days", nullable = false)
	public Serializable getDays() {
		return this.days;
	}

	public void setDays(Serializable days) {
		this.days = days;
	}

	@Column(name = "EmailId", nullable = false)
	public Serializable getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Serializable emailId) {
		this.emailId = emailId;
	}

	@Column(name = "Format", nullable = false)
	public Serializable getFormat() {
		return this.format;
	}

	public void setFormat(Serializable format) {
		this.format = format;
	}

	@Column(name = "Parameters")
	public Serializable getParameters() {
		return this.parameters;
	}

	public void setParameters(Serializable parameters) {
		this.parameters = parameters;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LastReportGenTime", length = 23)
	public Date getLastReportGenTime() {
		return this.lastReportGenTime;
	}

	public void setLastReportGenTime(Date lastReportGenTime) {
		this.lastReportGenTime = lastReportGenTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblReportSchedulerId))
			return false;
		TblReportSchedulerId castOther = (TblReportSchedulerId) other;

		return (this.getId() == castOther.getId()) && (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getGroupId() == castOther.getGroupId()) && (this.getUserId() == castOther.getUserId())
				&& (this.getReportId() == castOther.getReportId()) && (this.getRoleId() == castOther.getRoleId())
				&& ((this.getReportName() == castOther.getReportName()) || (this.getReportName() != null
						&& castOther.getReportName() != null && this.getReportName().equals(castOther.getReportName())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this.getStartDate() != null
						&& castOther.getStartDate() != null && this.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getReportGenTime() == castOther.getReportGenTime())
						|| (this.getReportGenTime() != null && castOther.getReportGenTime() != null
								&& this.getReportGenTime().equals(castOther.getReportGenTime())))
				&& ((this.getDays() == castOther.getDays()) || (this.getDays() != null && castOther.getDays() != null
						&& this.getDays().equals(castOther.getDays())))
				&& ((this.getEmailId() == castOther.getEmailId()) || (this.getEmailId() != null
						&& castOther.getEmailId() != null && this.getEmailId().equals(castOther.getEmailId())))
				&& ((this.getFormat() == castOther.getFormat()) || (this.getFormat() != null
						&& castOther.getFormat() != null && this.getFormat().equals(castOther.getFormat())))
				&& ((this.getParameters() == castOther.getParameters()) || (this.getParameters() != null
						&& castOther.getParameters() != null && this.getParameters().equals(castOther.getParameters())))
				&& ((this.getIsdeleted() == castOther.getIsdeleted()) || (this.getIsdeleted() != null
						&& castOther.getIsdeleted() != null && this.getIsdeleted().equals(castOther.getIsdeleted())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getLastReportGenTime() == castOther.getLastReportGenTime())
						|| (this.getLastReportGenTime() != null && castOther.getLastReportGenTime() != null
								&& this.getLastReportGenTime().equals(castOther.getLastReportGenTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getReportId();
		result = 37 * result + this.getRoleId();
		result = 37 * result + (getReportName() == null ? 0 : this.getReportName().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result + (getReportGenTime() == null ? 0 : this.getReportGenTime().hashCode());
		result = 37 * result + (getDays() == null ? 0 : this.getDays().hashCode());
		result = 37 * result + (getEmailId() == null ? 0 : this.getEmailId().hashCode());
		result = 37 * result + (getFormat() == null ? 0 : this.getFormat().hashCode());
		result = 37 * result + (getParameters() == null ? 0 : this.getParameters().hashCode());
		result = 37 * result + (getIsdeleted() == null ? 0 : this.getIsdeleted().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getLastReportGenTime() == null ? 0 : this.getLastReportGenTime().hashCode());
		return result;
	}

}
