package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblRfidswipeDetailsId generated by hbm2java
 */
@Embeddable
public class TblRfidswipeDetailsId implements java.io.Serializable {

	private int id;
	private int tripId;
	private Serializable rfid;
	private Date intime;
	private Serializable inlat;
	private Serializable inlong;
	private Serializable inwayPoint;
	private Boolean insms;
	private Date outtime;
	private Serializable outlat;
	private Serializable outlong;
	private Serializable outwayPoint;
	private Boolean outsms;
	private Boolean pickupOrDrop;
	private Date createdOn;
	private Date modifiedOn;

	public TblRfidswipeDetailsId() {
	}

	public TblRfidswipeDetailsId(int id, int tripId, Serializable rfid, Date createdOn) {
		this.id = id;
		this.tripId = tripId;
		this.rfid = rfid;
		this.createdOn = createdOn;
	}

	public TblRfidswipeDetailsId(int id, int tripId, Serializable rfid, Date intime, Serializable inlat,
			Serializable inlong, Serializable inwayPoint, Boolean insms, Date outtime, Serializable outlat,
			Serializable outlong, Serializable outwayPoint, Boolean outsms, Boolean pickupOrDrop, Date createdOn,
			Date modifiedOn) {
		this.id = id;
		this.tripId = tripId;
		this.rfid = rfid;
		this.intime = intime;
		this.inlat = inlat;
		this.inlong = inlong;
		this.inwayPoint = inwayPoint;
		this.insms = insms;
		this.outtime = outtime;
		this.outlat = outlat;
		this.outlong = outlong;
		this.outwayPoint = outwayPoint;
		this.outsms = outsms;
		this.pickupOrDrop = pickupOrDrop;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TripID", nullable = false)
	public int getTripId() {
		return this.tripId;
	}

	public void setTripId(int tripId) {
		this.tripId = tripId;
	}

	@Column(name = "RFID", nullable = false)
	public Serializable getRfid() {
		return this.rfid;
	}

	public void setRfid(Serializable rfid) {
		this.rfid = rfid;
	}

	@Column(name = "INTime", length = 23)
	public Date getIntime() {
		return this.intime;
	}

	public void setIntime(Date intime) {
		this.intime = intime;
	}

	@Column(name = "INLat")
	public Serializable getInlat() {
		return this.inlat;
	}

	public void setInlat(Serializable inlat) {
		this.inlat = inlat;
	}

	@Column(name = "INLong")
	public Serializable getInlong() {
		return this.inlong;
	}

	public void setInlong(Serializable inlong) {
		this.inlong = inlong;
	}

	@Column(name = "INWayPoint")
	public Serializable getInwayPoint() {
		return this.inwayPoint;
	}

	public void setInwayPoint(Serializable inwayPoint) {
		this.inwayPoint = inwayPoint;
	}

	@Column(name = "INSms")
	public Boolean getInsms() {
		return this.insms;
	}

	public void setInsms(Boolean insms) {
		this.insms = insms;
	}

	@Column(name = "OUTTime", length = 23)
	public Date getOuttime() {
		return this.outtime;
	}

	public void setOuttime(Date outtime) {
		this.outtime = outtime;
	}

	@Column(name = "OUTLat")
	public Serializable getOutlat() {
		return this.outlat;
	}

	public void setOutlat(Serializable outlat) {
		this.outlat = outlat;
	}

	@Column(name = "OUTLong")
	public Serializable getOutlong() {
		return this.outlong;
	}

	public void setOutlong(Serializable outlong) {
		this.outlong = outlong;
	}

	@Column(name = "OUTWayPoint")
	public Serializable getOutwayPoint() {
		return this.outwayPoint;
	}

	public void setOutwayPoint(Serializable outwayPoint) {
		this.outwayPoint = outwayPoint;
	}

	@Column(name = "OUTSms")
	public Boolean getOutsms() {
		return this.outsms;
	}

	public void setOutsms(Boolean outsms) {
		this.outsms = outsms;
	}

	@Column(name = "PickupOrDrop")
	public Boolean getPickupOrDrop() {
		return this.pickupOrDrop;
	}

	public void setPickupOrDrop(Boolean pickupOrDrop) {
		this.pickupOrDrop = pickupOrDrop;
	}

	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRfidswipeDetailsId))
			return false;
		TblRfidswipeDetailsId castOther = (TblRfidswipeDetailsId) other;

		return (this.getId() == castOther.getId()) && (this.getTripId() == castOther.getTripId())
				&& ((this.getRfid() == castOther.getRfid()) || (this.getRfid() != null && castOther.getRfid() != null
						&& this.getRfid().equals(castOther.getRfid())))
				&& ((this.getIntime() == castOther.getIntime()) || (this.getIntime() != null
						&& castOther.getIntime() != null && this.getIntime().equals(castOther.getIntime())))
				&& ((this.getInlat() == castOther.getInlat()) || (this.getInlat() != null
						&& castOther.getInlat() != null && this.getInlat().equals(castOther.getInlat())))
				&& ((this.getInlong() == castOther.getInlong()) || (this.getInlong() != null
						&& castOther.getInlong() != null && this.getInlong().equals(castOther.getInlong())))
				&& ((this.getInwayPoint() == castOther.getInwayPoint()) || (this.getInwayPoint() != null
						&& castOther.getInwayPoint() != null && this.getInwayPoint().equals(castOther.getInwayPoint())))
				&& ((this.getInsms() == castOther.getInsms()) || (this.getInsms() != null
						&& castOther.getInsms() != null && this.getInsms().equals(castOther.getInsms())))
				&& ((this.getOuttime() == castOther.getOuttime()) || (this.getOuttime() != null
						&& castOther.getOuttime() != null && this.getOuttime().equals(castOther.getOuttime())))
				&& ((this.getOutlat() == castOther.getOutlat()) || (this.getOutlat() != null
						&& castOther.getOutlat() != null && this.getOutlat().equals(castOther.getOutlat())))
				&& ((this.getOutlong() == castOther.getOutlong()) || (this.getOutlong() != null
						&& castOther.getOutlong() != null && this.getOutlong().equals(castOther.getOutlong())))
				&& ((this.getOutwayPoint() == castOther.getOutwayPoint())
						|| (this.getOutwayPoint() != null && castOther.getOutwayPoint() != null
								&& this.getOutwayPoint().equals(castOther.getOutwayPoint())))
				&& ((this.getOutsms() == castOther.getOutsms()) || (this.getOutsms() != null
						&& castOther.getOutsms() != null && this.getOutsms().equals(castOther.getOutsms())))
				&& ((this.getPickupOrDrop() == castOther.getPickupOrDrop())
						|| (this.getPickupOrDrop() != null && castOther.getPickupOrDrop() != null
								&& this.getPickupOrDrop().equals(castOther.getPickupOrDrop())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn())
						|| (this.getModifiedOn() != null && castOther.getModifiedOn() != null
								&& this.getModifiedOn().equals(castOther.getModifiedOn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getTripId();
		result = 37 * result + (getRfid() == null ? 0 : this.getRfid().hashCode());
		result = 37 * result + (getIntime() == null ? 0 : this.getIntime().hashCode());
		result = 37 * result + (getInlat() == null ? 0 : this.getInlat().hashCode());
		result = 37 * result + (getInlong() == null ? 0 : this.getInlong().hashCode());
		result = 37 * result + (getInwayPoint() == null ? 0 : this.getInwayPoint().hashCode());
		result = 37 * result + (getInsms() == null ? 0 : this.getInsms().hashCode());
		result = 37 * result + (getOuttime() == null ? 0 : this.getOuttime().hashCode());
		result = 37 * result + (getOutlat() == null ? 0 : this.getOutlat().hashCode());
		result = 37 * result + (getOutlong() == null ? 0 : this.getOutlong().hashCode());
		result = 37 * result + (getOutwayPoint() == null ? 0 : this.getOutwayPoint().hashCode());
		result = 37 * result + (getOutsms() == null ? 0 : this.getOutsms().hashCode());
		result = 37 * result + (getPickupOrDrop() == null ? 0 : this.getPickupOrDrop().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		return result;
	}

}
