package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblReportMaster generated by hbm2java
 */
@Entity
@Table(name = "tblReportMaster", schema = "dbo", catalog = "FMS4.0")
public class TblReportMaster implements java.io.Serializable {

	private int id;
	private Serializable reportName;
	private Serializable spName;

	public TblReportMaster() {
	}

	public TblReportMaster(int id, Serializable reportName) {
		this.id = id;
		this.reportName = reportName;
	}

	public TblReportMaster(int id, Serializable reportName, Serializable spName) {
		this.id = id;
		this.reportName = reportName;
		this.spName = spName;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ReportName", nullable = false)
	public Serializable getReportName() {
		return this.reportName;
	}

	public void setReportName(Serializable reportName) {
		this.reportName = reportName;
	}

	@Column(name = "SpName")
	public Serializable getSpName() {
		return this.spName;
	}

	public void setSpName(Serializable spName) {
		this.spName = spName;
	}

}
