package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRetailUserDetails generated by hbm2java
 */
@Entity
@Table(name = "tblRetailUserDetails", schema = "dbo", catalog = "FMS4.0")
public class TblRetailUserDetails implements java.io.Serializable {

	private int id;
	private Serializable loginId;
	private Integer userId;
	private Serializable userName;
	private Serializable emailId;
	private Serializable mobileNumber;
	private Serializable address;
	private Serializable soscontacts;
	private Serializable emergencyContacts;
	private Serializable passWord;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;

	public TblRetailUserDetails() {
	}

	public TblRetailUserDetails(int id) {
		this.id = id;
	}

	public TblRetailUserDetails(int id, Serializable loginId, Integer userId, Serializable userName,
			Serializable emailId, Serializable mobileNumber, Serializable address, Serializable soscontacts,
			Serializable emergencyContacts, Serializable passWord, Serializable createdBy, Date createdOn,
			Serializable modifiedBy, Date modifiedOn) {
		this.id = id;
		this.loginId = loginId;
		this.userId = userId;
		this.userName = userName;
		this.emailId = emailId;
		this.mobileNumber = mobileNumber;
		this.address = address;
		this.soscontacts = soscontacts;
		this.emergencyContacts = emergencyContacts;
		this.passWord = passWord;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LoginId")
	public Serializable getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Serializable loginId) {
		this.loginId = loginId;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName")
	public Serializable getUserName() {
		return this.userName;
	}

	public void setUserName(Serializable userName) {
		this.userName = userName;
	}

	@Column(name = "EmailID")
	public Serializable getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Serializable emailId) {
		this.emailId = emailId;
	}

	@Column(name = "MobileNumber")
	public Serializable getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(Serializable mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "SOSContacts")
	public Serializable getSoscontacts() {
		return this.soscontacts;
	}

	public void setSoscontacts(Serializable soscontacts) {
		this.soscontacts = soscontacts;
	}

	@Column(name = "EmergencyContacts")
	public Serializable getEmergencyContacts() {
		return this.emergencyContacts;
	}

	public void setEmergencyContacts(Serializable emergencyContacts) {
		this.emergencyContacts = emergencyContacts;
	}

	@Column(name = "PassWord")
	public Serializable getPassWord() {
		return this.passWord;
	}

	public void setPassWord(Serializable passWord) {
		this.passWord = passWord;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
