package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblRoads generated by hbm2java
 */
@Entity
@Table(name = "tbl_Roads", schema = "dbo", catalog = "FMS4.0")
public class TblRoads implements java.io.Serializable {

	private TblRoadsId id;

	public TblRoads() {
	}

	public TblRoads(TblRoadsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "roadNme", column = @Column(name = "ROAD_NME")),
			@AttributeOverride(name = "roadAlt", column = @Column(name = "ROAD_ALT")),
			@AttributeOverride(name = "ftrCry", column = @Column(name = "FTR_CRY")),
			@AttributeOverride(name = "fow", column = @Column(name = "FOW")),
			@AttributeOverride(name = "fowNme", column = @Column(name = "FOW_NME")),
			@AttributeOverride(name = "city", column = @Column(name = "CITY")),
			@AttributeOverride(name = "state", column = @Column(name = "STATE")),
			@AttributeOverride(name = "geom", column = @Column(name = "geom")) })
	public TblRoadsId getId() {
		return this.id;
	}

	public void setId(TblRoadsId id) {
		this.id = id;
	}

}
