package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblReverseGeocoding generated by hbm2java
 */
@Entity
@Table(name = "tblReverseGeocoding", schema = "dbo", catalog = "FMS4.0")
public class TblReverseGeocoding implements java.io.Serializable {

	private TblReverseGeocodingId id;
	private int id_1;
	private byte[] geom;
	private Serializable formattedAddress;
	private byte[] fenceGeom;
	private Serializable geomAddress;
	private Date date;
	private Double latRound;
	private Double longRound;

	public TblReverseGeocoding() {
	}

	public TblReverseGeocoding(TblReverseGeocodingId id, int id_1) {
		this.id = id;
		this.id_1 = id_1;
	}

	public TblReverseGeocoding(TblReverseGeocodingId id, int id_1, byte[] geom, Serializable formattedAddress,
			byte[] fenceGeom, Serializable geomAddress, Date date, Double latRound, Double longRound) {
		this.id = id;
		this.id_1 = id_1;
		this.geom = geom;
		this.formattedAddress = formattedAddress;
		this.fenceGeom = fenceGeom;
		this.geomAddress = geomAddress;
		this.date = date;
		this.latRound = latRound;
		this.longRound = longRound;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lat", column = @Column(name = "Lat", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "long_", column = @Column(name = "Long", nullable = false, precision = 53, scale = 0)) })
	public TblReverseGeocodingId getId() {
		return this.id;
	}

	public void setId(TblReverseGeocodingId id) {
		this.id = id;
	}

	@Column(name = "id", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "geom")
	public byte[] getGeom() {
		return this.geom;
	}

	public void setGeom(byte[] geom) {
		this.geom = geom;
	}

	@Column(name = "FormattedAddress")
	public Serializable getFormattedAddress() {
		return this.formattedAddress;
	}

	public void setFormattedAddress(Serializable formattedAddress) {
		this.formattedAddress = formattedAddress;
	}

	@Column(name = "Fence_geom")
	public byte[] getFenceGeom() {
		return this.fenceGeom;
	}

	public void setFenceGeom(byte[] fenceGeom) {
		this.fenceGeom = fenceGeom;
	}

	@Column(name = "GeomAddress")
	public Serializable getGeomAddress() {
		return this.geomAddress;
	}

	public void setGeomAddress(Serializable geomAddress) {
		this.geomAddress = geomAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "LatRound", precision = 53, scale = 0)
	public Double getLatRound() {
		return this.latRound;
	}

	public void setLatRound(Double latRound) {
		this.latRound = latRound;
	}

	@Column(name = "LongRound", precision = 53, scale = 0)
	public Double getLongRound() {
		return this.longRound;
	}

	public void setLongRound(Double longRound) {
		this.longRound = longRound;
	}

}
