package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRetailAssetDetails generated by hbm2java
 */
@Entity
@Table(name = "tblRetailAssetDetails", schema = "dbo", catalog = "FMS4.0")
public class TblRetailAssetDetails implements java.io.Serializable {

	private int id;
	private Serializable assetName;
	private Serializable assetType;
	private Integer userId;
	private Serializable imeinumber;
	private Date insuranceDueDate;
	private Double speedLimit;
	private Serializable driverName;
	private Double mileage;
	private Long odometer;
	private Integer waypointId;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;
	private Integer vehicleId;

	public TblRetailAssetDetails() {
	}

	public TblRetailAssetDetails(int id) {
		this.id = id;
	}

	public TblRetailAssetDetails(int id, Serializable assetName, Serializable assetType, Integer userId,
			Serializable imeinumber, Date insuranceDueDate, Double speedLimit, Serializable driverName, Double mileage,
			Long odometer, Integer waypointId, Date createdOn, Serializable createdBy, Date modifiedOn,
			Serializable modifiedBy, Integer vehicleId) {
		this.id = id;
		this.assetName = assetName;
		this.assetType = assetType;
		this.userId = userId;
		this.imeinumber = imeinumber;
		this.insuranceDueDate = insuranceDueDate;
		this.speedLimit = speedLimit;
		this.driverName = driverName;
		this.mileage = mileage;
		this.odometer = odometer;
		this.waypointId = waypointId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vehicleId = vehicleId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "AssetName")
	public Serializable getAssetName() {
		return this.assetName;
	}

	public void setAssetName(Serializable assetName) {
		this.assetName = assetName;
	}

	@Column(name = "AssetType")
	public Serializable getAssetType() {
		return this.assetType;
	}

	public void setAssetType(Serializable assetType) {
		this.assetType = assetType;
	}

	@Column(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "IMEINumber")
	public Serializable getImeinumber() {
		return this.imeinumber;
	}

	public void setImeinumber(Serializable imeinumber) {
		this.imeinumber = imeinumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsuranceDueDate", length = 23)
	public Date getInsuranceDueDate() {
		return this.insuranceDueDate;
	}

	public void setInsuranceDueDate(Date insuranceDueDate) {
		this.insuranceDueDate = insuranceDueDate;
	}

	@Column(name = "SpeedLimit", precision = 53, scale = 0)
	public Double getSpeedLimit() {
		return this.speedLimit;
	}

	public void setSpeedLimit(Double speedLimit) {
		this.speedLimit = speedLimit;
	}

	@Column(name = "DriverName")
	public Serializable getDriverName() {
		return this.driverName;
	}

	public void setDriverName(Serializable driverName) {
		this.driverName = driverName;
	}

	@Column(name = "Mileage", precision = 53, scale = 0)
	public Double getMileage() {
		return this.mileage;
	}

	public void setMileage(Double mileage) {
		this.mileage = mileage;
	}

	@Column(name = "Odometer", precision = 18, scale = 0)
	public Long getOdometer() {
		return this.odometer;
	}

	public void setOdometer(Long odometer) {
		this.odometer = odometer;
	}

	@Column(name = "WaypointId")
	public Integer getWaypointId() {
		return this.waypointId;
	}

	public void setWaypointId(Integer waypointId) {
		this.waypointId = waypointId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "VehicleId")
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

}
