package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRideRequests generated by hbm2java
 */
@Entity
@Table(name = "tblRideRequests", schema = "dbo", catalog = "FMS4.0")
public class TblRideRequests implements java.io.Serializable {

	private int id;
	private Integer ownerId;
	private Integer requestedOfferId;
	private Integer requestUserId;
	private Serializable requestUserName;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;
	private Boolean isDeleted;
	private Serializable status;

	public TblRideRequests() {
	}

	public TblRideRequests(int id) {
		this.id = id;
	}

	public TblRideRequests(int id, Integer ownerId, Integer requestedOfferId, Integer requestUserId,
			Serializable requestUserName, Date createdOn, Serializable createdBy, Date modifiedOn,
			Serializable modifiedBy, Boolean isDeleted, Serializable status) {
		this.id = id;
		this.ownerId = ownerId;
		this.requestedOfferId = requestedOfferId;
		this.requestUserId = requestUserId;
		this.requestUserName = requestUserName;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isDeleted = isDeleted;
		this.status = status;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "OwnerId")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "RequestedOfferId")
	public Integer getRequestedOfferId() {
		return this.requestedOfferId;
	}

	public void setRequestedOfferId(Integer requestedOfferId) {
		this.requestedOfferId = requestedOfferId;
	}

	@Column(name = "RequestUserId")
	public Integer getRequestUserId() {
		return this.requestUserId;
	}

	public void setRequestUserId(Integer requestUserId) {
		this.requestUserId = requestUserId;
	}

	@Column(name = "RequestUserName")
	public Serializable getRequestUserName() {
		return this.requestUserName;
	}

	public void setRequestUserName(Serializable requestUserName) {
		this.requestUserName = requestUserName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

}
