package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblSmsQuery generated by hbm2java
 */
@Entity
@Table(name = "tblSmsQuery", schema = "dbo", catalog = "FMS4.0")
public class TblSmsQuery implements java.io.Serializable {

	private TblSmsQueryId id;

	public TblSmsQuery() {
	}

	public TblSmsQuery(TblSmsQueryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "message", column = @Column(name = "Message", nullable = false)),
			@AttributeOverride(name = "sendNumber", column = @Column(name = "SendNumber", nullable = false)),
			@AttributeOverride(name = "toNumber", column = @Column(name = "ToNumber", nullable = false)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", nullable = false)) })
	public TblSmsQueryId getId() {
		return this.id;
	}

	public void setId(TblSmsQueryId id) {
		this.id = id;
	}

}
