package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TblSpCall generated by hbm2java
 */
@Entity
@Table(name = "tblSpCall", schema = "dbo", catalog = "FMS4.0")
public class TblSpCall implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private Serializable spName;

	public TblSpCall() {
	}

	public TblSpCall(int id) {
		this.id = id;
	}

	public TblSpCall(int id, Serializable spName) {
		this.id = id;
		this.spName = spName;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "SpName")
	public Serializable getSpName() {
		return this.spName;
	}

	public void setSpName(Serializable spName) {
		this.spName = spName;
	}

}
