package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSosdetails generated by hbm2java
 */
@Entity
@Table(name = "tblSOSDetails", schema = "dbo", catalog = "FMS4.0")
public class TblSosdetails implements java.io.Serializable {

	private int id;
	private Serializable soscontactName;
	private Serializable sosnumber;
	private int groupId;
	private Boolean isdeleted;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;

	public TblSosdetails() {
	}

	public TblSosdetails(int id, Serializable soscontactName, Serializable sosnumber, int groupId) {
		this.id = id;
		this.soscontactName = soscontactName;
		this.sosnumber = sosnumber;
		this.groupId = groupId;
	}

	public TblSosdetails(int id, Serializable soscontactName, Serializable sosnumber, int groupId, Boolean isdeleted,
			Date createdOn, Serializable createdBy, Date modifiedOn, Serializable modifiedBy) {
		this.id = id;
		this.soscontactName = soscontactName;
		this.sosnumber = sosnumber;
		this.groupId = groupId;
		this.isdeleted = isdeleted;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "SOSContactName", nullable = false)
	public Serializable getSoscontactName() {
		return this.soscontactName;
	}

	public void setSoscontactName(Serializable soscontactName) {
		this.soscontactName = soscontactName;
	}

	@Column(name = "SOSNumber", nullable = false)
	public Serializable getSosnumber() {
		return this.sosnumber;
	}

	public void setSosnumber(Serializable sosnumber) {
		this.sosnumber = sosnumber;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
