package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblsample generated by hbm2java
 */
@Entity
@Table(name = "tblsample", schema = "dbo", catalog = "FMS4.0")
public class Tblsample implements java.io.Serializable {

	private TblsampleId id;

	public Tblsample() {
	}

	public Tblsample(TblsampleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "groupbyId", column = @Column(name = "GroupbyID")),
			@AttributeOverride(name = "fuel", column = @Column(name = "fuel", precision = 53, scale = 0)) })
	public TblsampleId getId() {
		return this.id;
	}

	public void setId(TblsampleId id) {
		this.id = id;
	}

}
