package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblSmsQueryId generated by hbm2java
 */
@Embeddable
public class TblSmsQueryId implements java.io.Serializable {

	private int id;
	private Serializable message;
	private Serializable sendNumber;
	private Serializable toNumber;
	private Date createdOn;
	private Date modifiedOn;
	private boolean status;

	public TblSmsQueryId() {
	}

	public TblSmsQueryId(int id, Serializable message, Serializable sendNumber, Serializable toNumber, Date createdOn,
			boolean status) {
		this.id = id;
		this.message = message;
		this.sendNumber = sendNumber;
		this.toNumber = toNumber;
		this.createdOn = createdOn;
		this.status = status;
	}

	public TblSmsQueryId(int id, Serializable message, Serializable sendNumber, Serializable toNumber, Date createdOn,
			Date modifiedOn, boolean status) {
		this.id = id;
		this.message = message;
		this.sendNumber = sendNumber;
		this.toNumber = toNumber;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.status = status;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Message", nullable = false)
	public Serializable getMessage() {
		return this.message;
	}

	public void setMessage(Serializable message) {
		this.message = message;
	}

	@Column(name = "SendNumber", nullable = false)
	public Serializable getSendNumber() {
		return this.sendNumber;
	}

	public void setSendNumber(Serializable sendNumber) {
		this.sendNumber = sendNumber;
	}

	@Column(name = "ToNumber", nullable = false)
	public Serializable getToNumber() {
		return this.toNumber;
	}

	public void setToNumber(Serializable toNumber) {
		this.toNumber = toNumber;
	}

	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblSmsQueryId))
			return false;
		TblSmsQueryId castOther = (TblSmsQueryId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getSendNumber() == castOther.getSendNumber()) || (this.getSendNumber() != null
						&& castOther.getSendNumber() != null && this.getSendNumber().equals(castOther.getSendNumber())))
				&& ((this.getToNumber() == castOther.getToNumber()) || (this.getToNumber() != null
						&& castOther.getToNumber() != null && this.getToNumber().equals(castOther.getToNumber())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
						&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& (this.isStatus() == castOther.isStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getSendNumber() == null ? 0 : this.getSendNumber().hashCode());
		result = 37 * result + (getToNumber() == null ? 0 : this.getToNumber().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (this.isStatus() ? 1 : 0);
		return result;
	}

}
