package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TblTripHistoryDistance generated by hbm2java
 */
@Entity
@Table(name = "tblTripHistoryDistance", schema = "dbo", catalog = "FMS4.0")
public class TblTripHistoryDistance implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private Serializable vehicleRegistrationNo;
	private int routeId;
	private Double latitude;
	private Double longitude;
	private Double interDistance;
	private Date createdOn;
	private Boolean isDeleted;

	public TblTripHistoryDistance() {
	}

	public TblTripHistoryDistance(int id, Serializable vehicleRegistrationNo, int routeId, Date createdOn) {
		this.id = id;
		this.vehicleRegistrationNo = vehicleRegistrationNo;
		this.routeId = routeId;
		this.createdOn = createdOn;
	}

	public TblTripHistoryDistance(int id, Serializable vehicleRegistrationNo, int routeId, Double latitude,
			Double longitude, Double interDistance, Date createdOn, Boolean isDeleted) {
		this.id = id;
		this.vehicleRegistrationNo = vehicleRegistrationNo;
		this.routeId = routeId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.interDistance = interDistance;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "VehicleRegistrationNo", nullable = false)
	public Serializable getVehicleRegistrationNo() {
		return this.vehicleRegistrationNo;
	}

	public void setVehicleRegistrationNo(Serializable vehicleRegistrationNo) {
		this.vehicleRegistrationNo = vehicleRegistrationNo;
	}

	@Column(name = "RouteId", nullable = false)
	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "InterDistance", precision = 53, scale = 0)
	public Double getInterDistance() {
		return this.interDistance;
	}

	public void setInterDistance(Double interDistance) {
		this.interDistance = interDistance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
