package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblVendor generated by hbm2java
 */
@Entity
@Table(name = "tblVendor", schema = "dbo", catalog = "FMS4.0")
public class TblVendor implements java.io.Serializable {

	private int id;
	private Integer groupId;
	private Integer comapnyId;
	private Serializable vendorName;
	private Serializable contactNumber;
	private Serializable contactName;
	private Serializable address;
	private Serializable description;
	private Integer vendorRatio;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;
	private Boolean isdeleted;

	public TblVendor() {
	}

	public TblVendor(int id, Serializable vendorName, Serializable contactNumber, Serializable contactName) {
		this.id = id;
		this.vendorName = vendorName;
		this.contactNumber = contactNumber;
		this.contactName = contactName;
	}

	public TblVendor(int id, Integer groupId, Integer comapnyId, Serializable vendorName, Serializable contactNumber,
			Serializable contactName, Serializable address, Serializable description, Integer vendorRatio,
			Date createdOn, Serializable createdBy, Date modifiedOn, Serializable modifiedBy, Boolean isdeleted) {
		this.id = id;
		this.groupId = groupId;
		this.comapnyId = comapnyId;
		this.vendorName = vendorName;
		this.contactNumber = contactNumber;
		this.contactName = contactName;
		this.address = address;
		this.description = description;
		this.vendorRatio = vendorRatio;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ComapnyID")
	public Integer getComapnyId() {
		return this.comapnyId;
	}

	public void setComapnyId(Integer comapnyId) {
		this.comapnyId = comapnyId;
	}

	@Column(name = "VendorName", nullable = false)
	public Serializable getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(Serializable vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "ContactNumber", nullable = false)
	public Serializable getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(Serializable contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "ContactName", nullable = false)
	public Serializable getContactName() {
		return this.contactName;
	}

	public void setContactName(Serializable contactName) {
		this.contactName = contactName;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "VendorRatio")
	public Integer getVendorRatio() {
		return this.vendorRatio;
	}

	public void setVendorRatio(Integer vendorRatio) {
		this.vendorRatio = vendorRatio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "Isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
