package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblVehicleVendorMaster generated by hbm2java
 */
@Entity
@Table(name = "tblVehicleVendorMaster", schema = "dbo", catalog = "FMS4.0")
public class TblVehicleVendorMaster implements java.io.Serializable {

	private int id;
	private int vehicleId;
	private int vendorId;
	private Serializable vehicleName;
	private Serializable vendorName;
	private Integer seatingCapacity;
	private Boolean isDeleted;
	private Date createdOn;
	private Serializable createdBy;
	private Date modifiedOn;
	private Serializable modifiedBy;
	private Integer vehicleTypeId;
	private Serializable vehicleTypeName;
	private Integer groupId;

	public TblVehicleVendorMaster() {
	}

	public TblVehicleVendorMaster(int id, int vehicleId, int vendorId) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.vendorId = vendorId;
	}

	public TblVehicleVendorMaster(int id, int vehicleId, int vendorId, Serializable vehicleName,
			Serializable vendorName, Integer seatingCapacity, Boolean isDeleted, Date createdOn, Serializable createdBy,
			Date modifiedOn, Serializable modifiedBy, Integer vehicleTypeId, Serializable vehicleTypeName,
			Integer groupId) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.vendorId = vendorId;
		this.vehicleName = vehicleName;
		this.vendorName = vendorName;
		this.seatingCapacity = seatingCapacity;
		this.isDeleted = isDeleted;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vehicleTypeId = vehicleTypeId;
		this.vehicleTypeName = vehicleTypeName;
		this.groupId = groupId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VehicleId", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "VendorId", nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "VehicleName")
	public Serializable getVehicleName() {
		return this.vehicleName;
	}

	public void setVehicleName(Serializable vehicleName) {
		this.vehicleName = vehicleName;
	}

	@Column(name = "VendorName")
	public Serializable getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(Serializable vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "SeatingCapacity")
	public Integer getSeatingCapacity() {
		return this.seatingCapacity;
	}

	public void setSeatingCapacity(Integer seatingCapacity) {
		this.seatingCapacity = seatingCapacity;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "VehicleTypeId")
	public Integer getVehicleTypeId() {
		return this.vehicleTypeId;
	}

	public void setVehicleTypeId(Integer vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	@Column(name = "VehicleTypeName")
	public Serializable getVehicleTypeName() {
		return this.vehicleTypeName;
	}

	public void setVehicleTypeName(Serializable vehicleTypeName) {
		this.vehicleTypeName = vehicleTypeName;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

}
