package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWaypoints generated by hbm2java
 */
@Entity
@Table(name = "tblWaypoints", schema = "dbo", catalog = "FMS4.0")
public class TblWaypoints implements java.io.Serializable {

	private int id;
	private int groupId;
	private Serializable waypointName;
	private int waypointType;
	private Serializable color;
	private boolean isDeleted;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;

	public TblWaypoints() {
	}

	public TblWaypoints(int id, int groupId, Serializable waypointName, int waypointType, Serializable color,
			boolean isDeleted, Serializable createdBy, Date createdOn) {
		this.id = id;
		this.groupId = groupId;
		this.waypointName = waypointName;
		this.waypointType = waypointType;
		this.color = color;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	public TblWaypoints(int id, int groupId, Serializable waypointName, int waypointType, Serializable color,
			boolean isDeleted, Serializable createdBy, Date createdOn, Serializable modifiedBy, Date modifiedOn) {
		this.id = id;
		this.groupId = groupId;
		this.waypointName = waypointName;
		this.waypointType = waypointType;
		this.color = color;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "WaypointName", nullable = false)
	public Serializable getWaypointName() {
		return this.waypointName;
	}

	public void setWaypointName(Serializable waypointName) {
		this.waypointName = waypointName;
	}

	@Column(name = "WaypointType", nullable = false)
	public int getWaypointType() {
		return this.waypointType;
	}

	public void setWaypointType(int waypointType) {
		this.waypointType = waypointType;
	}

	@Column(name = "Color", nullable = false)
	public Serializable getColor() {
		return this.color;
	}

	public void setColor(Serializable color) {
		this.color = color;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
