package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Timezone generated by hbm2java
 */
@Entity
@Table(name = "TIMEZONE", schema = "dbo", catalog = "FMS4.0")
public class Timezone implements java.io.Serializable {

	private String timezoneName;
	private double gmtOffset;
	private String dstAbbrv;
	private boolean dstBit;

	public Timezone() {
	}

	public Timezone(String timezoneName, double gmtOffset, boolean dstBit) {
		this.timezoneName = timezoneName;
		this.gmtOffset = gmtOffset;
		this.dstBit = dstBit;
	}

	public Timezone(String timezoneName, double gmtOffset, String dstAbbrv, boolean dstBit) {
		this.timezoneName = timezoneName;
		this.gmtOffset = gmtOffset;
		this.dstAbbrv = dstAbbrv;
		this.dstBit = dstBit;
	}

	@Id

	@Column(name = "Timezone_Name", unique = true, nullable = false, length = 25)
	public String getTimezoneName() {
		return this.timezoneName;
	}

	public void setTimezoneName(String timezoneName) {
		this.timezoneName = timezoneName;
	}

	@Column(name = "GMT_Offset", nullable = false, precision = 53, scale = 0)
	public double getGmtOffset() {
		return this.gmtOffset;
	}

	public void setGmtOffset(double gmtOffset) {
		this.gmtOffset = gmtOffset;
	}

	@Column(name = "DST_Abbrv", length = 6)
	public String getDstAbbrv() {
		return this.dstAbbrv;
	}

	public void setDstAbbrv(String dstAbbrv) {
		this.dstAbbrv = dstAbbrv;
	}

	@Column(name = "DST_bit", nullable = false)
	public boolean isDstBit() {
		return this.dstBit;
	}

	public void setDstBit(boolean dstBit) {
		this.dstBit = dstBit;
	}

}
