package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trips generated by hbm2java
 */
@Entity
@Table(name = "Trips", schema = "dbo", catalog = "FMS4.0")
public class Trips implements java.io.Serializable {

	private int id;
	private Serializable tripId;
	private int groupId;
	private Date scheduledTripStartTime;
	private Date scheduledTripEndTime;
	private String createdBy;
	private Date createOn;
	private String modifiedBy;
	private Date modifiedOn;
	private Boolean isDeleted;
	private Integer routeId;
	private Integer vehicleId;
	private Integer employeeId;
	private Date actualTripStartTime;
	private Date actualTripEndTime;
	private Integer helperId;
	private Integer attandentId;
	private Boolean isActive;
	private Boolean pickuporDrop;
	private Integer shiftType;
	private Boolean isRoundTrip;
	private Integer chkUi;
	private Boolean isGenerated;
	private Serializable approvedDistance;

	public Trips() {
	}

	public Trips(int id, int groupId) {
		this.id = id;
		this.groupId = groupId;
	}

	public Trips(int id, Serializable tripId, int groupId, Date scheduledTripStartTime, Date scheduledTripEndTime,
			String createdBy, Date createOn, String modifiedBy, Date modifiedOn, Boolean isDeleted, Integer routeId,
			Integer vehicleId, Integer employeeId, Date actualTripStartTime, Date actualTripEndTime, Integer helperId,
			Integer attandentId, Boolean isActive, Boolean pickuporDrop, Integer shiftType, Boolean isRoundTrip,
			Integer chkUi, Boolean isGenerated, Serializable approvedDistance) {
		this.id = id;
		this.tripId = tripId;
		this.groupId = groupId;
		this.scheduledTripStartTime = scheduledTripStartTime;
		this.scheduledTripEndTime = scheduledTripEndTime;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.routeId = routeId;
		this.vehicleId = vehicleId;
		this.employeeId = employeeId;
		this.actualTripStartTime = actualTripStartTime;
		this.actualTripEndTime = actualTripEndTime;
		this.helperId = helperId;
		this.attandentId = attandentId;
		this.isActive = isActive;
		this.pickuporDrop = pickuporDrop;
		this.shiftType = shiftType;
		this.isRoundTrip = isRoundTrip;
		this.chkUi = chkUi;
		this.isGenerated = isGenerated;
		this.approvedDistance = approvedDistance;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TripID")
	public Serializable getTripId() {
		return this.tripId;
	}

	public void setTripId(Serializable tripId) {
		this.tripId = tripId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ScheduledTripStartTime", length = 23)
	public Date getScheduledTripStartTime() {
		return this.scheduledTripStartTime;
	}

	public void setScheduledTripStartTime(Date scheduledTripStartTime) {
		this.scheduledTripStartTime = scheduledTripStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ScheduledTripEndTime", length = 23)
	public Date getScheduledTripEndTime() {
		return this.scheduledTripEndTime;
	}

	public void setScheduledTripEndTime(Date scheduledTripEndTime) {
		this.scheduledTripEndTime = scheduledTripEndTime;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createOn", length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "RouteID")
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "VehicleId")
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "EmployeeId")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualTripStartTime", length = 23)
	public Date getActualTripStartTime() {
		return this.actualTripStartTime;
	}

	public void setActualTripStartTime(Date actualTripStartTime) {
		this.actualTripStartTime = actualTripStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualTripEndTime", length = 23)
	public Date getActualTripEndTime() {
		return this.actualTripEndTime;
	}

	public void setActualTripEndTime(Date actualTripEndTime) {
		this.actualTripEndTime = actualTripEndTime;
	}

	@Column(name = "HelperId")
	public Integer getHelperId() {
		return this.helperId;
	}

	public void setHelperId(Integer helperId) {
		this.helperId = helperId;
	}

	@Column(name = "AttandentId")
	public Integer getAttandentId() {
		return this.attandentId;
	}

	public void setAttandentId(Integer attandentId) {
		this.attandentId = attandentId;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "PickuporDrop")
	public Boolean getPickuporDrop() {
		return this.pickuporDrop;
	}

	public void setPickuporDrop(Boolean pickuporDrop) {
		this.pickuporDrop = pickuporDrop;
	}

	@Column(name = "ShiftType")
	public Integer getShiftType() {
		return this.shiftType;
	}

	public void setShiftType(Integer shiftType) {
		this.shiftType = shiftType;
	}

	@Column(name = "IsRoundTrip")
	public Boolean getIsRoundTrip() {
		return this.isRoundTrip;
	}

	public void setIsRoundTrip(Boolean isRoundTrip) {
		this.isRoundTrip = isRoundTrip;
	}

	@Column(name = "ChkUI")
	public Integer getChkUi() {
		return this.chkUi;
	}

	public void setChkUi(Integer chkUi) {
		this.chkUi = chkUi;
	}

	@Column(name = "IsGenerated")
	public Boolean getIsGenerated() {
		return this.isGenerated;
	}

	public void setIsGenerated(Boolean isGenerated) {
		this.isGenerated = isGenerated;
	}

	@Column(name = "ApprovedDistance")
	public Serializable getApprovedDistance() {
		return this.approvedDistance;
	}

	public void setApprovedDistance(Serializable approvedDistance) {
		this.approvedDistance = approvedDistance;
	}

}
