package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tripslist generated by hbm2java
 */
@Entity
@Table(name = "TRIPSLIST", schema = "dbo", catalog = "FMS4.0")
public class Tripslist implements java.io.Serializable {

	private TripslistId id;

	public Tripslist() {
	}

	public Tripslist(TripslistId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "vehicleno", column = @Column(name = "VEHICLENO")),
			@AttributeOverride(name = "astarttime", column = @Column(name = "ASTARTTIME", length = 23)),
			@AttributeOverride(name = "aendtime", column = @Column(name = "AENDTIME", length = 23)) })
	public TripslistId getId() {
		return this.id;
	}

	public void setId(TripslistId id) {
		this.id = id;
	}

}
