package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userprofile generated by hbm2java
 */
@Entity
@Table(name = "Userprofile", schema = "dbo", catalog = "FMS4.0")
public class Userprofile implements java.io.Serializable {

	private UserprofileId id;
	private Users users;

	public Userprofile() {
	}

	public Userprofile(UserprofileId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userid", column = @Column(name = "Userid", nullable = false)),
			@AttributeOverride(name = "birthyear", column = @Column(name = "Birthyear")),
			@AttributeOverride(name = "gender", column = @Column(name = "Gender", nullable = false)),
			@AttributeOverride(name = "address", column = @Column(name = "Address")),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "photo", column = @Column(name = "Photo")),
			@AttributeOverride(name = "photoLocation", column = @Column(name = "PhotoLocation")) })
	public UserprofileId getId() {
		return this.id;
	}

	public void setId(UserprofileId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Userid", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
