package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserprofileId generated by hbm2java
 */
@Embeddable
public class UserprofileId implements java.io.Serializable {

	private int userid;
	private Integer birthyear;
	private String gender;
	private String address;
	private int id;
	private byte[] photo;
	private Serializable photoLocation;

	public UserprofileId() {
	}

	public UserprofileId(int userid, String gender, int id) {
		this.userid = userid;
		this.gender = gender;
		this.id = id;
	}

	public UserprofileId(int userid, Integer birthyear, String gender, String address, int id, byte[] photo,
			Serializable photoLocation) {
		this.userid = userid;
		this.birthyear = birthyear;
		this.gender = gender;
		this.address = address;
		this.id = id;
		this.photo = photo;
		this.photoLocation = photoLocation;
	}

	@Column(name = "Userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "Birthyear")
	public Integer getBirthyear() {
		return this.birthyear;
	}

	public void setBirthyear(Integer birthyear) {
		this.birthyear = birthyear;
	}

	@Column(name = "Gender", nullable = false)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Column(name = "PhotoLocation")
	public Serializable getPhotoLocation() {
		return this.photoLocation;
	}

	public void setPhotoLocation(Serializable photoLocation) {
		this.photoLocation = photoLocation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserprofileId))
			return false;
		UserprofileId castOther = (UserprofileId) other;

		return (this.getUserid() == castOther.getUserid())
				&& ((this.getBirthyear() == castOther.getBirthyear()) || (this.getBirthyear() != null
						&& castOther.getBirthyear() != null && this.getBirthyear().equals(castOther.getBirthyear())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& (this.getId() == castOther.getId())
				&& ((this.getPhoto() == castOther.getPhoto()) || (this.getPhoto() != null
						&& castOther.getPhoto() != null && Arrays.equals(this.getPhoto(), castOther.getPhoto())))
				&& ((this.getPhotoLocation() == castOther.getPhotoLocation())
						|| (this.getPhotoLocation() != null && castOther.getPhotoLocation() != null
								&& this.getPhotoLocation().equals(castOther.getPhotoLocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + (getBirthyear() == null ? 0 : this.getBirthyear().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getPhoto() == null ? 0 : Arrays.hashCode(this.getPhoto()));
		result = 37 * result + (getPhotoLocation() == null ? 0 : this.getPhotoLocation().hashCode());
		return result;
	}

}
