package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsersAlert generated by hbm2java
 */
@Entity
@Table(name = "UsersAlert", schema = "dbo", catalog = "FMS4.0")
public class UsersAlert implements java.io.Serializable {

	private int id;
	private int groupId;
	private int alertType;
	private boolean isdeleted;
	private Date createdOn;
	private Serializable createdBy;

	public UsersAlert() {
	}

	public UsersAlert(int id, int groupId, int alertType, boolean isdeleted) {
		this.id = id;
		this.groupId = groupId;
		this.alertType = alertType;
		this.isdeleted = isdeleted;
	}

	public UsersAlert(int id, int groupId, int alertType, boolean isdeleted, Date createdOn, Serializable createdBy) {
		this.id = id;
		this.groupId = groupId;
		this.alertType = alertType;
		this.isdeleted = isdeleted;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "AlertType", nullable = false)
	public int getAlertType() {
		return this.alertType;
	}

	public void setAlertType(int alertType) {
		this.alertType = alertType;
	}

	@Column(name = "Isdeleted", nullable = false)
	public boolean isIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

}
