package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehicleFuelConsumedDetailId generated by hbm2java
 */
@Embeddable
public class VehicleFuelConsumedDetailId implements java.io.Serializable {

	private int groupId;
	private int vehicleId;
	private Date fuelConsumedDate;

	public VehicleFuelConsumedDetailId() {
	}

	public VehicleFuelConsumedDetailId(int groupId, int vehicleId, Date fuelConsumedDate) {
		this.groupId = groupId;
		this.vehicleId = vehicleId;
		this.fuelConsumedDate = fuelConsumedDate;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleID", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "FuelConsumedDate", nullable = false, length = 23)
	public Date getFuelConsumedDate() {
		return this.fuelConsumedDate;
	}

	public void setFuelConsumedDate(Date fuelConsumedDate) {
		this.fuelConsumedDate = fuelConsumedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleFuelConsumedDetailId))
			return false;
		VehicleFuelConsumedDetailId castOther = (VehicleFuelConsumedDetailId) other;

		return (this.getGroupId() == castOther.getGroupId()) && (this.getVehicleId() == castOther.getVehicleId())
				&& ((this.getFuelConsumedDate() == castOther.getFuelConsumedDate())
						|| (this.getFuelConsumedDate() != null && castOther.getFuelConsumedDate() != null
								&& this.getFuelConsumedDate().equals(castOther.getFuelConsumedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getVehicleId();
		result = 37 * result + (getFuelConsumedDate() == null ? 0 : this.getFuelConsumedDate().hashCode());
		return result;
	}

}
