package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VehicleLog generated by hbm2java
 */
@Entity
@Table(name = "VehicleLog", schema = "dbo", catalog = "FMS4.0")
public class VehicleLog implements java.io.Serializable {

	private VehicleLogId id;

	public VehicleLog() {
	}

	public VehicleLog(VehicleLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "vehicleId", column = @Column(name = "VehicleID")),
			@AttributeOverride(name = "registrationNo", column = @Column(name = "RegistrationNo")),
			@AttributeOverride(name = "currentDeviceId", column = @Column(name = "CurrentDeviceID")),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "modifiedBy")),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "modifiedOn", length = 23)),
			@AttributeOverride(name = "machineName", column = @Column(name = "MachineName")),
			@AttributeOverride(name = "loggedInUser", column = @Column(name = "LoggedInUser")) })
	public VehicleLogId getId() {
		return this.id;
	}

	public void setId(VehicleLogId id) {
		this.id = id;
	}

}
