package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleDriver generated by hbm2java
 */
@Entity
@Table(name = "VehicleDriver", schema = "dbo", catalog = "FMS4.0")
public class VehicleDriver implements java.io.Serializable {

	private int id;
	private Integer groupId;
	private Integer vehicleId;
	private Integer driverId;
	private Date fromDate;
	private Date toDate;
	private Boolean isCurrent;

	public VehicleDriver() {
	}

	public VehicleDriver(int id) {
		this.id = id;
	}

	public VehicleDriver(int id, Integer groupId, Integer vehicleId, Integer driverId, Date fromDate, Date toDate,
			Boolean isCurrent) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleId = vehicleId;
		this.driverId = driverId;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.isCurrent = isCurrent;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupId")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleId")
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "DriverId")
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FromDate", length = 23)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ToDate", length = 23)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "IsCurrent")
	public Boolean getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

}
