package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name = "Vehicles", schema = "dbo", catalog = "FMS4.0")
public class Vehicles implements java.io.Serializable {

	private int id;
	private Serializable registrationNo;
	private int groupId;
	private Integer type;
	private Integer vehicleClassType;
	private Serializable puccnumber;
	private Date puccexpiry;
	private Serializable cngnumber;
	private Date cngexpiry;
	private Serializable insuranceNo;
	private Date insuranceExpiry;
	private Serializable currentDeviceId;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;
	private Serializable insurancePolicyType;
	private Boolean isactivated;
	private Integer isCurrent;
	private Date lastServiceDate;
	private Date nextServiceDueDate;
	private Date permitDueDate;
	private Serializable vehicleMake;
	private Serializable imei;
	private Serializable mobileNo;
	private Date commissionDate;
	private Integer yearOfManufacturing;
	private Integer seatingCapacity;
	private Serializable fcnumber;
	private Date fcdate;
	private Date fcexpiryDate;
	private Date taxPaidDate;
	private Date taxPaidRenewalDate;
	private Serializable mileage;
	private Integer fuelCapacity;
	private Serializable odometer;
	private Serializable routeName;
	private Serializable assetType;
	private Integer vehicleType;
	private Date installationdate;
	private Serializable deviceType;
	private Integer vendorId;
	private Integer vehicleTypeId;
	private Serializable vehicleImagePath;
	private Serializable taxPaidImagePath;
	private Serializable puccimagePath;
	private Serializable insuranceImagePath;
	private Serializable fcimagePath;
	private Serializable cngimagePath;
	private String vehicleTagId;

	public Vehicles() {
	}

	public Vehicles(int id, Serializable registrationNo, int groupId, Date createdOn, boolean isDeleted) {
		this.id = id;
		this.registrationNo = registrationNo;
		this.groupId = groupId;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
	}

	public Vehicles(int id, Serializable registrationNo, int groupId, Integer type, Integer vehicleClassType,
			Serializable puccnumber, Date puccexpiry, Serializable cngnumber, Date cngexpiry, Serializable insuranceNo,
			Date insuranceExpiry, Serializable currentDeviceId, Serializable createdBy, Date createdOn,
			Serializable modifiedBy, Date modifiedOn, boolean isDeleted, Serializable insurancePolicyType,
			Boolean isactivated, Integer isCurrent, Date lastServiceDate, Date nextServiceDueDate, Date permitDueDate,
			Serializable vehicleMake, Serializable imei, Serializable mobileNo, Date commissionDate,
			Integer yearOfManufacturing, Integer seatingCapacity, Serializable fcnumber, Date fcdate, Date fcexpiryDate,
			Date taxPaidDate, Date taxPaidRenewalDate, Serializable mileage, Integer fuelCapacity,
			Serializable odometer, Serializable routeName, Serializable assetType, Integer vehicleType,
			Date installationdate, Serializable deviceType, Integer vendorId, Integer vehicleTypeId,
			Serializable vehicleImagePath, Serializable taxPaidImagePath, Serializable puccimagePath,
			Serializable insuranceImagePath, Serializable fcimagePath, Serializable cngimagePath, String vehicleTagId) {
		this.id = id;
		this.registrationNo = registrationNo;
		this.groupId = groupId;
		this.type = type;
		this.vehicleClassType = vehicleClassType;
		this.puccnumber = puccnumber;
		this.puccexpiry = puccexpiry;
		this.cngnumber = cngnumber;
		this.cngexpiry = cngexpiry;
		this.insuranceNo = insuranceNo;
		this.insuranceExpiry = insuranceExpiry;
		this.currentDeviceId = currentDeviceId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.insurancePolicyType = insurancePolicyType;
		this.isactivated = isactivated;
		this.isCurrent = isCurrent;
		this.lastServiceDate = lastServiceDate;
		this.nextServiceDueDate = nextServiceDueDate;
		this.permitDueDate = permitDueDate;
		this.vehicleMake = vehicleMake;
		this.imei = imei;
		this.mobileNo = mobileNo;
		this.commissionDate = commissionDate;
		this.yearOfManufacturing = yearOfManufacturing;
		this.seatingCapacity = seatingCapacity;
		this.fcnumber = fcnumber;
		this.fcdate = fcdate;
		this.fcexpiryDate = fcexpiryDate;
		this.taxPaidDate = taxPaidDate;
		this.taxPaidRenewalDate = taxPaidRenewalDate;
		this.mileage = mileage;
		this.fuelCapacity = fuelCapacity;
		this.odometer = odometer;
		this.routeName = routeName;
		this.assetType = assetType;
		this.vehicleType = vehicleType;
		this.installationdate = installationdate;
		this.deviceType = deviceType;
		this.vendorId = vendorId;
		this.vehicleTypeId = vehicleTypeId;
		this.vehicleImagePath = vehicleImagePath;
		this.taxPaidImagePath = taxPaidImagePath;
		this.puccimagePath = puccimagePath;
		this.insuranceImagePath = insuranceImagePath;
		this.fcimagePath = fcimagePath;
		this.cngimagePath = cngimagePath;
		this.vehicleTagId = vehicleTagId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "RegistrationNo", nullable = false)
	public Serializable getRegistrationNo() {
		return this.registrationNo;
	}

	public void setRegistrationNo(Serializable registrationNo) {
		this.registrationNo = registrationNo;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "VehicleClassType")
	public Integer getVehicleClassType() {
		return this.vehicleClassType;
	}

	public void setVehicleClassType(Integer vehicleClassType) {
		this.vehicleClassType = vehicleClassType;
	}

	@Column(name = "PUCCNumber")
	public Serializable getPuccnumber() {
		return this.puccnumber;
	}

	public void setPuccnumber(Serializable puccnumber) {
		this.puccnumber = puccnumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUCCExpiry", length = 23)
	public Date getPuccexpiry() {
		return this.puccexpiry;
	}

	public void setPuccexpiry(Date puccexpiry) {
		this.puccexpiry = puccexpiry;
	}

	@Column(name = "CNGNumber")
	public Serializable getCngnumber() {
		return this.cngnumber;
	}

	public void setCngnumber(Serializable cngnumber) {
		this.cngnumber = cngnumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNGExpiry", length = 23)
	public Date getCngexpiry() {
		return this.cngexpiry;
	}

	public void setCngexpiry(Date cngexpiry) {
		this.cngexpiry = cngexpiry;
	}

	@Column(name = "InsuranceNo")
	public Serializable getInsuranceNo() {
		return this.insuranceNo;
	}

	public void setInsuranceNo(Serializable insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsuranceExpiry", length = 23)
	public Date getInsuranceExpiry() {
		return this.insuranceExpiry;
	}

	public void setInsuranceExpiry(Date insuranceExpiry) {
		this.insuranceExpiry = insuranceExpiry;
	}

	@Column(name = "CurrentDeviceID")
	public Serializable getCurrentDeviceId() {
		return this.currentDeviceId;
	}

	public void setCurrentDeviceId(Serializable currentDeviceId) {
		this.currentDeviceId = currentDeviceId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "InsurancePolicyType")
	public Serializable getInsurancePolicyType() {
		return this.insurancePolicyType;
	}

	public void setInsurancePolicyType(Serializable insurancePolicyType) {
		this.insurancePolicyType = insurancePolicyType;
	}

	@Column(name = "isactivated")
	public Boolean getIsactivated() {
		return this.isactivated;
	}

	public void setIsactivated(Boolean isactivated) {
		this.isactivated = isactivated;
	}

	@Column(name = "isCurrent")
	public Integer getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Integer isCurrent) {
		this.isCurrent = isCurrent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastServiceDate", length = 23)
	public Date getLastServiceDate() {
		return this.lastServiceDate;
	}

	public void setLastServiceDate(Date lastServiceDate) {
		this.lastServiceDate = lastServiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextServiceDueDate", length = 23)
	public Date getNextServiceDueDate() {
		return this.nextServiceDueDate;
	}

	public void setNextServiceDueDate(Date nextServiceDueDate) {
		this.nextServiceDueDate = nextServiceDueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PermitDueDate", length = 23)
	public Date getPermitDueDate() {
		return this.permitDueDate;
	}

	public void setPermitDueDate(Date permitDueDate) {
		this.permitDueDate = permitDueDate;
	}

	@Column(name = "VehicleMake")
	public Serializable getVehicleMake() {
		return this.vehicleMake;
	}

	public void setVehicleMake(Serializable vehicleMake) {
		this.vehicleMake = vehicleMake;
	}

	@Column(name = "IMEI")
	public Serializable getImei() {
		return this.imei;
	}

	public void setImei(Serializable imei) {
		this.imei = imei;
	}

	@Column(name = "MobileNo")
	public Serializable getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Serializable mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CommissionDate", length = 23)
	public Date getCommissionDate() {
		return this.commissionDate;
	}

	public void setCommissionDate(Date commissionDate) {
		this.commissionDate = commissionDate;
	}

	@Column(name = "YearOfManufacturing")
	public Integer getYearOfManufacturing() {
		return this.yearOfManufacturing;
	}

	public void setYearOfManufacturing(Integer yearOfManufacturing) {
		this.yearOfManufacturing = yearOfManufacturing;
	}

	@Column(name = "SeatingCapacity")
	public Integer getSeatingCapacity() {
		return this.seatingCapacity;
	}

	public void setSeatingCapacity(Integer seatingCapacity) {
		this.seatingCapacity = seatingCapacity;
	}

	@Column(name = "FCNumber")
	public Serializable getFcnumber() {
		return this.fcnumber;
	}

	public void setFcnumber(Serializable fcnumber) {
		this.fcnumber = fcnumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCDate", length = 23)
	public Date getFcdate() {
		return this.fcdate;
	}

	public void setFcdate(Date fcdate) {
		this.fcdate = fcdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCExpiryDate", length = 23)
	public Date getFcexpiryDate() {
		return this.fcexpiryDate;
	}

	public void setFcexpiryDate(Date fcexpiryDate) {
		this.fcexpiryDate = fcexpiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TaxPaidDate", length = 23)
	public Date getTaxPaidDate() {
		return this.taxPaidDate;
	}

	public void setTaxPaidDate(Date taxPaidDate) {
		this.taxPaidDate = taxPaidDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TaxPaidRenewalDate", length = 23)
	public Date getTaxPaidRenewalDate() {
		return this.taxPaidRenewalDate;
	}

	public void setTaxPaidRenewalDate(Date taxPaidRenewalDate) {
		this.taxPaidRenewalDate = taxPaidRenewalDate;
	}

	@Column(name = "Mileage")
	public Serializable getMileage() {
		return this.mileage;
	}

	public void setMileage(Serializable mileage) {
		this.mileage = mileage;
	}

	@Column(name = "FuelCapacity")
	public Integer getFuelCapacity() {
		return this.fuelCapacity;
	}

	public void setFuelCapacity(Integer fuelCapacity) {
		this.fuelCapacity = fuelCapacity;
	}

	@Column(name = "Odometer")
	public Serializable getOdometer() {
		return this.odometer;
	}

	public void setOdometer(Serializable odometer) {
		this.odometer = odometer;
	}

	@Column(name = "RouteName")
	public Serializable getRouteName() {
		return this.routeName;
	}

	public void setRouteName(Serializable routeName) {
		this.routeName = routeName;
	}

	@Column(name = "AssetType")
	public Serializable getAssetType() {
		return this.assetType;
	}

	public void setAssetType(Serializable assetType) {
		this.assetType = assetType;
	}

	@Column(name = "VehicleType")
	public Integer getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(Integer vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Installationdate", length = 23)
	public Date getInstallationdate() {
		return this.installationdate;
	}

	public void setInstallationdate(Date installationdate) {
		this.installationdate = installationdate;
	}

	@Column(name = "DeviceType")
	public Serializable getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(Serializable deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "VendorId")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "VehicleTypeId")
	public Integer getVehicleTypeId() {
		return this.vehicleTypeId;
	}

	public void setVehicleTypeId(Integer vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	@Column(name = "VehicleImagePath")
	public Serializable getVehicleImagePath() {
		return this.vehicleImagePath;
	}

	public void setVehicleImagePath(Serializable vehicleImagePath) {
		this.vehicleImagePath = vehicleImagePath;
	}

	@Column(name = "TaxPaidImagePath")
	public Serializable getTaxPaidImagePath() {
		return this.taxPaidImagePath;
	}

	public void setTaxPaidImagePath(Serializable taxPaidImagePath) {
		this.taxPaidImagePath = taxPaidImagePath;
	}

	@Column(name = "PUCCImagePath")
	public Serializable getPuccimagePath() {
		return this.puccimagePath;
	}

	public void setPuccimagePath(Serializable puccimagePath) {
		this.puccimagePath = puccimagePath;
	}

	@Column(name = "InsuranceImagePath")
	public Serializable getInsuranceImagePath() {
		return this.insuranceImagePath;
	}

	public void setInsuranceImagePath(Serializable insuranceImagePath) {
		this.insuranceImagePath = insuranceImagePath;
	}

	@Column(name = "FCImagePath")
	public Serializable getFcimagePath() {
		return this.fcimagePath;
	}

	public void setFcimagePath(Serializable fcimagePath) {
		this.fcimagePath = fcimagePath;
	}

	@Column(name = "CNGImagePath")
	public Serializable getCngimagePath() {
		return this.cngimagePath;
	}

	public void setCngimagePath(Serializable cngimagePath) {
		this.cngimagePath = cngimagePath;
	}

	@Column(name = "VehicleTagId", length = 50)
	public String getVehicleTagId() {
		return this.vehicleTagId;
	}

	public void setVehicleTagId(String vehicleTagId) {
		this.vehicleTagId = vehicleTagId;
	}

}
