package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehicleLogId generated by hbm2java
 */
@Embeddable
public class VehicleLogId implements java.io.Serializable {

	private int id;
	private Integer vehicleId;
	private Serializable registrationNo;
	private Serializable currentDeviceId;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Serializable machineName;
	private Serializable loggedInUser;

	public VehicleLogId() {
	}

	public VehicleLogId(int id) {
		this.id = id;
	}

	public VehicleLogId(int id, Integer vehicleId, Serializable registrationNo, Serializable currentDeviceId,
			Serializable modifiedBy, Date modifiedOn, Serializable machineName, Serializable loggedInUser) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.registrationNo = registrationNo;
		this.currentDeviceId = currentDeviceId;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.machineName = machineName;
		this.loggedInUser = loggedInUser;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VehicleID")
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "RegistrationNo")
	public Serializable getRegistrationNo() {
		return this.registrationNo;
	}

	public void setRegistrationNo(Serializable registrationNo) {
		this.registrationNo = registrationNo;
	}

	@Column(name = "CurrentDeviceID")
	public Serializable getCurrentDeviceId() {
		return this.currentDeviceId;
	}

	public void setCurrentDeviceId(Serializable currentDeviceId) {
		this.currentDeviceId = currentDeviceId;
	}

	@Column(name = "modifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "MachineName")
	public Serializable getMachineName() {
		return this.machineName;
	}

	public void setMachineName(Serializable machineName) {
		this.machineName = machineName;
	}

	@Column(name = "LoggedInUser")
	public Serializable getLoggedInUser() {
		return this.loggedInUser;
	}

	public void setLoggedInUser(Serializable loggedInUser) {
		this.loggedInUser = loggedInUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleLogId))
			return false;
		VehicleLogId castOther = (VehicleLogId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getVehicleId() == castOther.getVehicleId()) || (this.getVehicleId() != null
						&& castOther.getVehicleId() != null && this.getVehicleId().equals(castOther.getVehicleId())))
				&& ((this.getRegistrationNo() == castOther.getRegistrationNo())
						|| (this.getRegistrationNo() != null && castOther.getRegistrationNo() != null
								&& this.getRegistrationNo().equals(castOther.getRegistrationNo())))
				&& ((this.getCurrentDeviceId() == castOther.getCurrentDeviceId())
						|| (this.getCurrentDeviceId() != null && castOther.getCurrentDeviceId() != null
								&& this.getCurrentDeviceId().equals(castOther.getCurrentDeviceId())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
						&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& ((this.getMachineName() == castOther.getMachineName())
						|| (this.getMachineName() != null && castOther.getMachineName() != null
								&& this.getMachineName().equals(castOther.getMachineName())))
				&& ((this.getLoggedInUser() == castOther.getLoggedInUser())
						|| (this.getLoggedInUser() != null && castOther.getLoggedInUser() != null
								&& this.getLoggedInUser().equals(castOther.getLoggedInUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getVehicleId() == null ? 0 : this.getVehicleId().hashCode());
		result = 37 * result + (getRegistrationNo() == null ? 0 : this.getRegistrationNo().hashCode());
		result = 37 * result + (getCurrentDeviceId() == null ? 0 : this.getCurrentDeviceId().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (getMachineName() == null ? 0 : this.getMachineName().hashCode());
		result = 37 * result + (getLoggedInUser() == null ? 0 : this.getLoggedInUser().hashCode());
		return result;
	}

}
