package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "VehicleTypeMaster", schema = "dbo", catalog = "FMS4.0")
public class VehicleTypeMaster implements java.io.Serializable {

	private int vehicleTypeId;
	private Serializable vehicleTypeName;
	private Serializable description;
	private Serializable imageUrl;
	private Long speed;
	private Serializable createdBy;
	private Serializable modifiedBy;
	private Date createdDate;
	private Date modifiedDate;
	private boolean isDeleted;
	private Integer vendorId;

	public VehicleTypeMaster() {
	}

	public VehicleTypeMaster(int vehicleTypeId, boolean isDeleted) {
		this.vehicleTypeId = vehicleTypeId;
		this.isDeleted = isDeleted;
	}

	public VehicleTypeMaster(int vehicleTypeId, Serializable vehicleTypeName, Serializable description,
			Serializable imageUrl, Long speed, Serializable createdBy, Serializable modifiedBy, Date createdDate,
			Date modifiedDate, boolean isDeleted, Integer vendorId) {
		this.vehicleTypeId = vehicleTypeId;
		this.vehicleTypeName = vehicleTypeName;
		this.description = description;
		this.imageUrl = imageUrl;
		this.speed = speed;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.isDeleted = isDeleted;
		this.vendorId = vendorId;
	}

	@Id

	@Column(name = "VehicleTypeID", unique = true, nullable = false)
	public int getVehicleTypeId() {
		return this.vehicleTypeId;
	}

	public void setVehicleTypeId(int vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	@Column(name = "VehicleTypeName")
	public Serializable getVehicleTypeName() {
		return this.vehicleTypeName;
	}

	public void setVehicleTypeName(Serializable vehicleTypeName) {
		this.vehicleTypeName = vehicleTypeName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "ImageURL")
	public Serializable getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(Serializable imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "Speed", precision = 18, scale = 0)
	public Long getSpeed() {
		return this.speed;
	}

	public void setSpeed(Long speed) {
		this.speed = speed;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", length = 23)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "VendorId")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

}
