package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleCrewAssociaton generated by hbm2java
 */
@Entity
@Table(name = "VehicleCrewAssociaton", schema = "dbo", catalog = "FMS4.0")
public class VehicleCrewAssociaton implements java.io.Serializable {

	private int id;
	private int vehicleId;
	private int driverId;
	private Date fromdate;
	private Date todate;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private Serializable reason;
	private Boolean isdeleted;

	public VehicleCrewAssociaton() {
	}

	public VehicleCrewAssociaton(int id, int vehicleId, int driverId, Date fromdate, Date todate) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.driverId = driverId;
		this.fromdate = fromdate;
		this.todate = todate;
	}

	public VehicleCrewAssociaton(int id, int vehicleId, int driverId, Date fromdate, Date todate,
			Serializable createdBy, Date createdOn, Serializable modifiedBy, Date modifiedOn, Serializable reason,
			Boolean isdeleted) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.driverId = driverId;
		this.fromdate = fromdate;
		this.todate = todate;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.reason = reason;
		this.isdeleted = isdeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VehicleID", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "DriverID", nullable = false)
	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fromdate", nullable = false, length = 23)
	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Todate", nullable = false, length = 23)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "Reason")
	public Serializable getReason() {
		return this.reason;
	}

	public void setReason(Serializable reason) {
		this.reason = reason;
	}

	@Column(name = "isdeleted")
	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
