package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VehTest generated by hbm2java
 */
@Entity
@Table(name = "veh_test", schema = "dbo", catalog = "FMS4.0")
public class VehTest implements java.io.Serializable {

	private VehTestId id;

	public VehTest() {
	}

	public VehTest(VehTestId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "registrationNo", column = @Column(name = "RegistrationNo", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "Type")),
			@AttributeOverride(name = "vehicleClassType", column = @Column(name = "VehicleClassType")),
			@AttributeOverride(name = "puccnumber", column = @Column(name = "PUCCNumber")),
			@AttributeOverride(name = "puccexpiry", column = @Column(name = "PUCCExpiry", length = 23)),
			@AttributeOverride(name = "cngnumber", column = @Column(name = "CNGNumber")),
			@AttributeOverride(name = "cngexpiry", column = @Column(name = "CNGExpiry", length = 23)),
			@AttributeOverride(name = "insuranceNo", column = @Column(name = "InsuranceNo")),
			@AttributeOverride(name = "insuranceExpiry", column = @Column(name = "InsuranceExpiry", length = 23)),
			@AttributeOverride(name = "currentDeviceId", column = @Column(name = "CurrentDeviceID")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy")),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CreatedOn", nullable = false, length = 23)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "ModifiedBy")),
			@AttributeOverride(name = "modifiedOn", column = @Column(name = "ModifiedOn", length = 23)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "isDeleted", nullable = false)),
			@AttributeOverride(name = "insurancePolicyType", column = @Column(name = "InsurancePolicyType")),
			@AttributeOverride(name = "isactivated", column = @Column(name = "isactivated")),
			@AttributeOverride(name = "isCurrent", column = @Column(name = "isCurrent")),
			@AttributeOverride(name = "lastServiceDate", column = @Column(name = "LastServiceDate", length = 23)),
			@AttributeOverride(name = "nextServiceDueDate", column = @Column(name = "NextServiceDueDate", length = 23)),
			@AttributeOverride(name = "permitDueDate", column = @Column(name = "PermitDueDate", length = 23)),
			@AttributeOverride(name = "vehicleMake", column = @Column(name = "VehicleMake")),
			@AttributeOverride(name = "imei", column = @Column(name = "IMEI")),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "MobileNo")),
			@AttributeOverride(name = "commissionDate", column = @Column(name = "CommissionDate", length = 23)),
			@AttributeOverride(name = "yearOfManufacturing", column = @Column(name = "YearOfManufacturing")),
			@AttributeOverride(name = "seatingCapacity", column = @Column(name = "SeatingCapacity")),
			@AttributeOverride(name = "fcnumber", column = @Column(name = "FCNumber")),
			@AttributeOverride(name = "fcdate", column = @Column(name = "FCDate", length = 23)),
			@AttributeOverride(name = "fcexpiryDate", column = @Column(name = "FCExpiryDate", length = 23)),
			@AttributeOverride(name = "taxPaidDate", column = @Column(name = "TaxPaidDate", length = 23)),
			@AttributeOverride(name = "taxPaidRenewalDate", column = @Column(name = "TaxPaidRenewalDate", length = 23)),
			@AttributeOverride(name = "mileage", column = @Column(name = "Mileage")),
			@AttributeOverride(name = "fuelCapacity", column = @Column(name = "FuelCapacity")) })
	public VehTestId getId() {
		return this.id;
	}

	public void setId(VehTestId id) {
		this.id = id;
	}

}
