package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehTestId generated by hbm2java
 */
@Embeddable
public class VehTestId implements java.io.Serializable {

	private int id;
	private Serializable registrationNo;
	private int groupId;
	private Integer type;
	private Integer vehicleClassType;
	private Serializable puccnumber;
	private Date puccexpiry;
	private Serializable cngnumber;
	private Date cngexpiry;
	private Serializable insuranceNo;
	private Date insuranceExpiry;
	private Serializable currentDeviceId;
	private Serializable createdBy;
	private Date createdOn;
	private Serializable modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;
	private Serializable insurancePolicyType;
	private Boolean isactivated;
	private Integer isCurrent;
	private Date lastServiceDate;
	private Date nextServiceDueDate;
	private Date permitDueDate;
	private Serializable vehicleMake;
	private Serializable imei;
	private Serializable mobileNo;
	private Date commissionDate;
	private Integer yearOfManufacturing;
	private Integer seatingCapacity;
	private Serializable fcnumber;
	private Date fcdate;
	private Date fcexpiryDate;
	private Date taxPaidDate;
	private Date taxPaidRenewalDate;
	private Serializable mileage;
	private Integer fuelCapacity;

	public VehTestId() {
	}

	public VehTestId(int id, Serializable registrationNo, int groupId, Date createdOn, boolean isDeleted) {
		this.id = id;
		this.registrationNo = registrationNo;
		this.groupId = groupId;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
	}

	public VehTestId(int id, Serializable registrationNo, int groupId, Integer type, Integer vehicleClassType,
			Serializable puccnumber, Date puccexpiry, Serializable cngnumber, Date cngexpiry, Serializable insuranceNo,
			Date insuranceExpiry, Serializable currentDeviceId, Serializable createdBy, Date createdOn,
			Serializable modifiedBy, Date modifiedOn, boolean isDeleted, Serializable insurancePolicyType,
			Boolean isactivated, Integer isCurrent, Date lastServiceDate, Date nextServiceDueDate, Date permitDueDate,
			Serializable vehicleMake, Serializable imei, Serializable mobileNo, Date commissionDate,
			Integer yearOfManufacturing, Integer seatingCapacity, Serializable fcnumber, Date fcdate, Date fcexpiryDate,
			Date taxPaidDate, Date taxPaidRenewalDate, Serializable mileage, Integer fuelCapacity) {
		this.id = id;
		this.registrationNo = registrationNo;
		this.groupId = groupId;
		this.type = type;
		this.vehicleClassType = vehicleClassType;
		this.puccnumber = puccnumber;
		this.puccexpiry = puccexpiry;
		this.cngnumber = cngnumber;
		this.cngexpiry = cngexpiry;
		this.insuranceNo = insuranceNo;
		this.insuranceExpiry = insuranceExpiry;
		this.currentDeviceId = currentDeviceId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.insurancePolicyType = insurancePolicyType;
		this.isactivated = isactivated;
		this.isCurrent = isCurrent;
		this.lastServiceDate = lastServiceDate;
		this.nextServiceDueDate = nextServiceDueDate;
		this.permitDueDate = permitDueDate;
		this.vehicleMake = vehicleMake;
		this.imei = imei;
		this.mobileNo = mobileNo;
		this.commissionDate = commissionDate;
		this.yearOfManufacturing = yearOfManufacturing;
		this.seatingCapacity = seatingCapacity;
		this.fcnumber = fcnumber;
		this.fcdate = fcdate;
		this.fcexpiryDate = fcexpiryDate;
		this.taxPaidDate = taxPaidDate;
		this.taxPaidRenewalDate = taxPaidRenewalDate;
		this.mileage = mileage;
		this.fuelCapacity = fuelCapacity;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "RegistrationNo", nullable = false)
	public Serializable getRegistrationNo() {
		return this.registrationNo;
	}

	public void setRegistrationNo(Serializable registrationNo) {
		this.registrationNo = registrationNo;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "VehicleClassType")
	public Integer getVehicleClassType() {
		return this.vehicleClassType;
	}

	public void setVehicleClassType(Integer vehicleClassType) {
		this.vehicleClassType = vehicleClassType;
	}

	@Column(name = "PUCCNumber")
	public Serializable getPuccnumber() {
		return this.puccnumber;
	}

	public void setPuccnumber(Serializable puccnumber) {
		this.puccnumber = puccnumber;
	}

	@Column(name = "PUCCExpiry", length = 23)
	public Date getPuccexpiry() {
		return this.puccexpiry;
	}

	public void setPuccexpiry(Date puccexpiry) {
		this.puccexpiry = puccexpiry;
	}

	@Column(name = "CNGNumber")
	public Serializable getCngnumber() {
		return this.cngnumber;
	}

	public void setCngnumber(Serializable cngnumber) {
		this.cngnumber = cngnumber;
	}

	@Column(name = "CNGExpiry", length = 23)
	public Date getCngexpiry() {
		return this.cngexpiry;
	}

	public void setCngexpiry(Date cngexpiry) {
		this.cngexpiry = cngexpiry;
	}

	@Column(name = "InsuranceNo")
	public Serializable getInsuranceNo() {
		return this.insuranceNo;
	}

	public void setInsuranceNo(Serializable insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	@Column(name = "InsuranceExpiry", length = 23)
	public Date getInsuranceExpiry() {
		return this.insuranceExpiry;
	}

	public void setInsuranceExpiry(Date insuranceExpiry) {
		this.insuranceExpiry = insuranceExpiry;
	}

	@Column(name = "CurrentDeviceID")
	public Serializable getCurrentDeviceId() {
		return this.currentDeviceId;
	}

	public void setCurrentDeviceId(Serializable currentDeviceId) {
		this.currentDeviceId = currentDeviceId;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedOn", nullable = false, length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "ModifiedBy")
	public Serializable getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Serializable modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ModifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "InsurancePolicyType")
	public Serializable getInsurancePolicyType() {
		return this.insurancePolicyType;
	}

	public void setInsurancePolicyType(Serializable insurancePolicyType) {
		this.insurancePolicyType = insurancePolicyType;
	}

	@Column(name = "isactivated")
	public Boolean getIsactivated() {
		return this.isactivated;
	}

	public void setIsactivated(Boolean isactivated) {
		this.isactivated = isactivated;
	}

	@Column(name = "isCurrent")
	public Integer getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(Integer isCurrent) {
		this.isCurrent = isCurrent;
	}

	@Column(name = "LastServiceDate", length = 23)
	public Date getLastServiceDate() {
		return this.lastServiceDate;
	}

	public void setLastServiceDate(Date lastServiceDate) {
		this.lastServiceDate = lastServiceDate;
	}

	@Column(name = "NextServiceDueDate", length = 23)
	public Date getNextServiceDueDate() {
		return this.nextServiceDueDate;
	}

	public void setNextServiceDueDate(Date nextServiceDueDate) {
		this.nextServiceDueDate = nextServiceDueDate;
	}

	@Column(name = "PermitDueDate", length = 23)
	public Date getPermitDueDate() {
		return this.permitDueDate;
	}

	public void setPermitDueDate(Date permitDueDate) {
		this.permitDueDate = permitDueDate;
	}

	@Column(name = "VehicleMake")
	public Serializable getVehicleMake() {
		return this.vehicleMake;
	}

	public void setVehicleMake(Serializable vehicleMake) {
		this.vehicleMake = vehicleMake;
	}

	@Column(name = "IMEI")
	public Serializable getImei() {
		return this.imei;
	}

	public void setImei(Serializable imei) {
		this.imei = imei;
	}

	@Column(name = "MobileNo")
	public Serializable getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Serializable mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "CommissionDate", length = 23)
	public Date getCommissionDate() {
		return this.commissionDate;
	}

	public void setCommissionDate(Date commissionDate) {
		this.commissionDate = commissionDate;
	}

	@Column(name = "YearOfManufacturing")
	public Integer getYearOfManufacturing() {
		return this.yearOfManufacturing;
	}

	public void setYearOfManufacturing(Integer yearOfManufacturing) {
		this.yearOfManufacturing = yearOfManufacturing;
	}

	@Column(name = "SeatingCapacity")
	public Integer getSeatingCapacity() {
		return this.seatingCapacity;
	}

	public void setSeatingCapacity(Integer seatingCapacity) {
		this.seatingCapacity = seatingCapacity;
	}

	@Column(name = "FCNumber")
	public Serializable getFcnumber() {
		return this.fcnumber;
	}

	public void setFcnumber(Serializable fcnumber) {
		this.fcnumber = fcnumber;
	}

	@Column(name = "FCDate", length = 23)
	public Date getFcdate() {
		return this.fcdate;
	}

	public void setFcdate(Date fcdate) {
		this.fcdate = fcdate;
	}

	@Column(name = "FCExpiryDate", length = 23)
	public Date getFcexpiryDate() {
		return this.fcexpiryDate;
	}

	public void setFcexpiryDate(Date fcexpiryDate) {
		this.fcexpiryDate = fcexpiryDate;
	}

	@Column(name = "TaxPaidDate", length = 23)
	public Date getTaxPaidDate() {
		return this.taxPaidDate;
	}

	public void setTaxPaidDate(Date taxPaidDate) {
		this.taxPaidDate = taxPaidDate;
	}

	@Column(name = "TaxPaidRenewalDate", length = 23)
	public Date getTaxPaidRenewalDate() {
		return this.taxPaidRenewalDate;
	}

	public void setTaxPaidRenewalDate(Date taxPaidRenewalDate) {
		this.taxPaidRenewalDate = taxPaidRenewalDate;
	}

	@Column(name = "Mileage")
	public Serializable getMileage() {
		return this.mileage;
	}

	public void setMileage(Serializable mileage) {
		this.mileage = mileage;
	}

	@Column(name = "FuelCapacity")
	public Integer getFuelCapacity() {
		return this.fuelCapacity;
	}

	public void setFuelCapacity(Integer fuelCapacity) {
		this.fuelCapacity = fuelCapacity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehTestId))
			return false;
		VehTestId castOther = (VehTestId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getRegistrationNo() == castOther.getRegistrationNo())
						|| (this.getRegistrationNo() != null && castOther.getRegistrationNo() != null
								&& this.getRegistrationNo().equals(castOther.getRegistrationNo())))
				&& (this.getGroupId() == castOther.getGroupId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getVehicleClassType() == castOther.getVehicleClassType())
						|| (this.getVehicleClassType() != null && castOther.getVehicleClassType() != null
								&& this.getVehicleClassType().equals(castOther.getVehicleClassType())))
				&& ((this.getPuccnumber() == castOther.getPuccnumber()) || (this.getPuccnumber() != null
						&& castOther.getPuccnumber() != null && this.getPuccnumber().equals(castOther.getPuccnumber())))
				&& ((this.getPuccexpiry() == castOther.getPuccexpiry()) || (this.getPuccexpiry() != null
						&& castOther.getPuccexpiry() != null && this.getPuccexpiry().equals(castOther.getPuccexpiry())))
				&& ((this.getCngnumber() == castOther.getCngnumber()) || (this.getCngnumber() != null
						&& castOther.getCngnumber() != null && this.getCngnumber().equals(castOther.getCngnumber())))
				&& ((this.getCngexpiry() == castOther.getCngexpiry()) || (this.getCngexpiry() != null
						&& castOther.getCngexpiry() != null && this.getCngexpiry().equals(castOther.getCngexpiry())))
				&& ((this.getInsuranceNo() == castOther.getInsuranceNo())
						|| (this.getInsuranceNo() != null && castOther.getInsuranceNo() != null
								&& this.getInsuranceNo().equals(castOther.getInsuranceNo())))
				&& ((this.getInsuranceExpiry() == castOther.getInsuranceExpiry())
						|| (this.getInsuranceExpiry() != null && castOther.getInsuranceExpiry() != null
								&& this.getInsuranceExpiry().equals(castOther.getInsuranceExpiry())))
				&& ((this.getCurrentDeviceId() == castOther.getCurrentDeviceId())
						|| (this.getCurrentDeviceId() != null && castOther.getCurrentDeviceId() != null
								&& this.getCurrentDeviceId().equals(castOther.getCurrentDeviceId())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
						&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& (this.isIsDeleted() == castOther.isIsDeleted())
				&& ((this.getInsurancePolicyType() == castOther.getInsurancePolicyType())
						|| (this.getInsurancePolicyType() != null && castOther.getInsurancePolicyType() != null
								&& this.getInsurancePolicyType().equals(castOther.getInsurancePolicyType())))
				&& ((this.getIsactivated() == castOther.getIsactivated())
						|| (this.getIsactivated() != null && castOther.getIsactivated() != null
								&& this.getIsactivated().equals(castOther.getIsactivated())))
				&& ((this.getIsCurrent() == castOther.getIsCurrent()) || (this.getIsCurrent() != null
						&& castOther.getIsCurrent() != null && this.getIsCurrent().equals(castOther.getIsCurrent())))
				&& ((this.getLastServiceDate() == castOther.getLastServiceDate())
						|| (this.getLastServiceDate() != null && castOther.getLastServiceDate() != null
								&& this.getLastServiceDate().equals(castOther.getLastServiceDate())))
				&& ((this.getNextServiceDueDate() == castOther.getNextServiceDueDate())
						|| (this.getNextServiceDueDate() != null && castOther.getNextServiceDueDate() != null
								&& this.getNextServiceDueDate().equals(castOther.getNextServiceDueDate())))
				&& ((this.getPermitDueDate() == castOther.getPermitDueDate())
						|| (this.getPermitDueDate() != null && castOther.getPermitDueDate() != null
								&& this.getPermitDueDate().equals(castOther.getPermitDueDate())))
				&& ((this.getVehicleMake() == castOther.getVehicleMake())
						|| (this.getVehicleMake() != null && castOther.getVehicleMake() != null
								&& this.getVehicleMake().equals(castOther.getVehicleMake())))
				&& ((this.getImei() == castOther.getImei()) || (this.getImei() != null && castOther.getImei() != null
						&& this.getImei().equals(castOther.getImei())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this.getMobileNo() != null
						&& castOther.getMobileNo() != null && this.getMobileNo().equals(castOther.getMobileNo())))
				&& ((this.getCommissionDate() == castOther.getCommissionDate())
						|| (this.getCommissionDate() != null && castOther.getCommissionDate() != null
								&& this.getCommissionDate().equals(castOther.getCommissionDate())))
				&& ((this.getYearOfManufacturing() == castOther.getYearOfManufacturing())
						|| (this.getYearOfManufacturing() != null && castOther.getYearOfManufacturing() != null
								&& this.getYearOfManufacturing().equals(castOther.getYearOfManufacturing())))
				&& ((this.getSeatingCapacity() == castOther.getSeatingCapacity())
						|| (this.getSeatingCapacity() != null && castOther.getSeatingCapacity() != null
								&& this.getSeatingCapacity().equals(castOther.getSeatingCapacity())))
				&& ((this.getFcnumber() == castOther.getFcnumber()) || (this.getFcnumber() != null
						&& castOther.getFcnumber() != null && this.getFcnumber().equals(castOther.getFcnumber())))
				&& ((this.getFcdate() == castOther.getFcdate()) || (this.getFcdate() != null
						&& castOther.getFcdate() != null && this.getFcdate().equals(castOther.getFcdate())))
				&& ((this.getFcexpiryDate() == castOther.getFcexpiryDate())
						|| (this.getFcexpiryDate() != null && castOther.getFcexpiryDate() != null
								&& this.getFcexpiryDate().equals(castOther.getFcexpiryDate())))
				&& ((this.getTaxPaidDate() == castOther.getTaxPaidDate())
						|| (this.getTaxPaidDate() != null && castOther.getTaxPaidDate() != null
								&& this.getTaxPaidDate().equals(castOther.getTaxPaidDate())))
				&& ((this.getTaxPaidRenewalDate() == castOther.getTaxPaidRenewalDate())
						|| (this.getTaxPaidRenewalDate() != null && castOther.getTaxPaidRenewalDate() != null
								&& this.getTaxPaidRenewalDate().equals(castOther.getTaxPaidRenewalDate())))
				&& ((this.getMileage() == castOther.getMileage()) || (this.getMileage() != null
						&& castOther.getMileage() != null && this.getMileage().equals(castOther.getMileage())))
				&& ((this.getFuelCapacity() == castOther.getFuelCapacity())
						|| (this.getFuelCapacity() != null && castOther.getFuelCapacity() != null
								&& this.getFuelCapacity().equals(castOther.getFuelCapacity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getRegistrationNo() == null ? 0 : this.getRegistrationNo().hashCode());
		result = 37 * result + this.getGroupId();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getVehicleClassType() == null ? 0 : this.getVehicleClassType().hashCode());
		result = 37 * result + (getPuccnumber() == null ? 0 : this.getPuccnumber().hashCode());
		result = 37 * result + (getPuccexpiry() == null ? 0 : this.getPuccexpiry().hashCode());
		result = 37 * result + (getCngnumber() == null ? 0 : this.getCngnumber().hashCode());
		result = 37 * result + (getCngexpiry() == null ? 0 : this.getCngexpiry().hashCode());
		result = 37 * result + (getInsuranceNo() == null ? 0 : this.getInsuranceNo().hashCode());
		result = 37 * result + (getInsuranceExpiry() == null ? 0 : this.getInsuranceExpiry().hashCode());
		result = 37 * result + (getCurrentDeviceId() == null ? 0 : this.getCurrentDeviceId().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (this.isIsDeleted() ? 1 : 0);
		result = 37 * result + (getInsurancePolicyType() == null ? 0 : this.getInsurancePolicyType().hashCode());
		result = 37 * result + (getIsactivated() == null ? 0 : this.getIsactivated().hashCode());
		result = 37 * result + (getIsCurrent() == null ? 0 : this.getIsCurrent().hashCode());
		result = 37 * result + (getLastServiceDate() == null ? 0 : this.getLastServiceDate().hashCode());
		result = 37 * result + (getNextServiceDueDate() == null ? 0 : this.getNextServiceDueDate().hashCode());
		result = 37 * result + (getPermitDueDate() == null ? 0 : this.getPermitDueDate().hashCode());
		result = 37 * result + (getVehicleMake() == null ? 0 : this.getVehicleMake().hashCode());
		result = 37 * result + (getImei() == null ? 0 : this.getImei().hashCode());
		result = 37 * result + (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		result = 37 * result + (getCommissionDate() == null ? 0 : this.getCommissionDate().hashCode());
		result = 37 * result + (getYearOfManufacturing() == null ? 0 : this.getYearOfManufacturing().hashCode());
		result = 37 * result + (getSeatingCapacity() == null ? 0 : this.getSeatingCapacity().hashCode());
		result = 37 * result + (getFcnumber() == null ? 0 : this.getFcnumber().hashCode());
		result = 37 * result + (getFcdate() == null ? 0 : this.getFcdate().hashCode());
		result = 37 * result + (getFcexpiryDate() == null ? 0 : this.getFcexpiryDate().hashCode());
		result = 37 * result + (getTaxPaidDate() == null ? 0 : this.getTaxPaidDate().hashCode());
		result = 37 * result + (getTaxPaidRenewalDate() == null ? 0 : this.getTaxPaidRenewalDate().hashCode());
		result = 37 * result + (getMileage() == null ? 0 : this.getMileage().hashCode());
		result = 37 * result + (getFuelCapacity() == null ? 0 : this.getFuelCapacity().hashCode());
		return result;
	}

}
