package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehWaypointAssociation generated by hbm2java
 */
@Entity
@Table(name = "VehWaypointAssociation", schema = "dbo", catalog = "FMS4.0")
public class VehWaypointAssociation implements java.io.Serializable {

	private int id;
	private int groupId;
	private int vehicleId;
	private int waypointId;
	private int alertType;
	private Serializable phoneNumber;
	private Serializable email;
	private Date fromTime;
	private Date toTime;
	private Serializable createdby;
	private Date createdOn;
	private boolean isDeleted;
	private Boolean checkInAlert;
	private Boolean checkOutAlert;
	private Boolean smsalert;
	private Boolean emailAlert;

	public VehWaypointAssociation() {
	}

	public VehWaypointAssociation(int id, int groupId, int vehicleId, int waypointId, int alertType,
			boolean isDeleted) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleId = vehicleId;
		this.waypointId = waypointId;
		this.alertType = alertType;
		this.isDeleted = isDeleted;
	}

	public VehWaypointAssociation(int id, int groupId, int vehicleId, int waypointId, int alertType,
			Serializable phoneNumber, Serializable email, Date fromTime, Date toTime, Serializable createdby,
			Date createdOn, boolean isDeleted, Boolean checkInAlert, Boolean checkOutAlert, Boolean smsalert,
			Boolean emailAlert) {
		this.id = id;
		this.groupId = groupId;
		this.vehicleId = vehicleId;
		this.waypointId = waypointId;
		this.alertType = alertType;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.fromTime = fromTime;
		this.toTime = toTime;
		this.createdby = createdby;
		this.createdOn = createdOn;
		this.isDeleted = isDeleted;
		this.checkInAlert = checkInAlert;
		this.checkOutAlert = checkOutAlert;
		this.smsalert = smsalert;
		this.emailAlert = emailAlert;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "VehicleID", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "WaypointID", nullable = false)
	public int getWaypointId() {
		return this.waypointId;
	}

	public void setWaypointId(int waypointId) {
		this.waypointId = waypointId;
	}

	@Column(name = "AlertType", nullable = false)
	public int getAlertType() {
		return this.alertType;
	}

	public void setAlertType(int alertType) {
		this.alertType = alertType;
	}

	@Column(name = "PhoneNumber")
	public Serializable getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Serializable phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "FromTime", length = 16)
	public Date getFromTime() {
		return this.fromTime;
	}

	public void setFromTime(Date fromTime) {
		this.fromTime = fromTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ToTime", length = 16)
	public Date getToTime() {
		return this.toTime;
	}

	public void setToTime(Date toTime) {
		this.toTime = toTime;
	}

	@Column(name = "Createdby")
	public Serializable getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Serializable createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedOn", length = 23)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "CheckInAlert")
	public Boolean getCheckInAlert() {
		return this.checkInAlert;
	}

	public void setCheckInAlert(Boolean checkInAlert) {
		this.checkInAlert = checkInAlert;
	}

	@Column(name = "CheckOutAlert")
	public Boolean getCheckOutAlert() {
		return this.checkOutAlert;
	}

	public void setCheckOutAlert(Boolean checkOutAlert) {
		this.checkOutAlert = checkOutAlert;
	}

	@Column(name = "SMSAlert")
	public Boolean getSmsalert() {
		return this.smsalert;
	}

	public void setSmsalert(Boolean smsalert) {
		this.smsalert = smsalert;
	}

	@Column(name = "EmailAlert")
	public Boolean getEmailAlert() {
		return this.emailAlert;
	}

	public void setEmailAlert(Boolean emailAlert) {
		this.emailAlert = emailAlert;
	}

}
