package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewUserLocationCurrent generated by hbm2java
 */
@Entity
@Table(name = "view_user_location_current", schema = "dbo", catalog = "FMS4.0")
public class ViewUserLocationCurrent implements java.io.Serializable {

	private ViewUserLocationCurrentId id;

	public ViewUserLocationCurrent() {
	}

	public ViewUserLocationCurrent(ViewUserLocationCurrentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "msid", column = @Column(name = "msid", nullable = false, length = 20)),
			@AttributeOverride(name = "latitude", column = @Column(name = "Latitude", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "longitude", column = @Column(name = "Longitude", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "dateTime", column = @Column(name = "DateTime", nullable = false, length = 23)),
			@AttributeOverride(name = "speed", column = @Column(name = "speed", precision = 53, scale = 0)),
			@AttributeOverride(name = "direction", column = @Column(name = "direction", precision = 53, scale = 0)),
			@AttributeOverride(name = "ignition", column = @Column(name = "Ignition", precision = 10, scale = 0)),
			@AttributeOverride(name = "imei", column = @Column(name = "imei", nullable = false)),
			@AttributeOverride(name = "odometer", column = @Column(name = "odometer", precision = 53, scale = 0)),
			@AttributeOverride(name = "gpsDistace", column = @Column(name = "gps_distace", precision = 53, scale = 0)),
			@AttributeOverride(name = "fuel", column = @Column(name = "fuel", precision = 53, scale = 0)),
			@AttributeOverride(name = "vehicleid", column = @Column(name = "vehicleid", nullable = false)),
			@AttributeOverride(name = "reversegeocode", column = @Column(name = "reversegeocode")),
			@AttributeOverride(name = "analog", column = @Column(name = "Analog")),
			@AttributeOverride(name = "deviceName", column = @Column(name = "DeviceName")),
			@AttributeOverride(name = "batteryPercentage", column = @Column(name = "BatteryPercentage")) })
	public ViewUserLocationCurrentId getId() {
		return this.id;
	}

	public void setId(ViewUserLocationCurrentId id) {
		this.id = id;
	}

}
