package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewUserLocationHistory generated by hbm2java
 */
@Entity
@Table(name = "view_user_location_history", schema = "dbo", catalog = "FMS4.0")
public class ViewUserLocationHistory implements java.io.Serializable {

	private ViewUserLocationHistoryId id;

	public ViewUserLocationHistory() {
	}

	public ViewUserLocationHistory(ViewUserLocationHistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lat", column = @Column(name = "lat", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "lon", column = @Column(name = "lon", nullable = false, precision = 53, scale = 0)),
			@AttributeOverride(name = "timestamp", column = @Column(name = "timestamp", nullable = false, length = 23)),
			@AttributeOverride(name = "speed", column = @Column(name = "speed", precision = 53, scale = 0)),
			@AttributeOverride(name = "direction", column = @Column(name = "direction", precision = 53, scale = 0)),
			@AttributeOverride(name = "locationType", column = @Column(name = "location_type", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "odometer", column = @Column(name = "odometer", precision = 53, scale = 0)),
			@AttributeOverride(name = "gpsDistace", column = @Column(name = "gps_distace", precision = 53, scale = 0)),
			@AttributeOverride(name = "fuel", column = @Column(name = "fuel", precision = 53, scale = 0)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)),
			@AttributeOverride(name = "reversegeocode", column = @Column(name = "reversegeocode")),
			@AttributeOverride(name = "msid", column = @Column(name = "msid", nullable = false, length = 20)),
			@AttributeOverride(name = "multiValue1", column = @Column(name = "multi_value1")),
			@AttributeOverride(name = "createddatetime", column = @Column(name = "createddatetime", length = 23)),
			@AttributeOverride(name = "binarycontent", column = @Column(name = "binarycontent")) })
	public ViewUserLocationHistoryId getId() {
		return this.id;
	}

	public void setId(ViewUserLocationHistoryId id) {
		this.id = id;
	}

}
