package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewVehiclestopAll generated by hbm2java
 */
@Entity
@Table(name = "view_Vehiclestop_all", schema = "dbo", catalog = "FMS4.0")
public class ViewVehiclestopAll implements java.io.Serializable {

	private ViewVehiclestopAllId id;

	public ViewVehiclestopAll() {
	}

	public ViewVehiclestopAll(ViewVehiclestopAllId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "stopIdDtc", column = @Column(name = "stop_id_dtc")),
			@AttributeOverride(name = "stopIdSirf", column = @Column(name = "stop_id_sirf")),
			@AttributeOverride(name = "stopName", column = @Column(name = "STOP_NAME")),
			@AttributeOverride(name = "altName", column = @Column(name = "ALT_NAME")),
			@AttributeOverride(name = "lat", column = @Column(name = "lat", precision = 53, scale = 0)),
			@AttributeOverride(name = "lon", column = @Column(name = "lon", precision = 53, scale = 0)),
			@AttributeOverride(name = "geom", column = @Column(name = "geom")),
			@AttributeOverride(name = "fenceGeom", column = @Column(name = "fence_geom")) })
	public ViewVehiclestopAllId getId() {
		return this.id;
	}

	public void setId(ViewVehiclestopAllId id) {
		this.id = id;
	}

}
