package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewRouteseta generated by hbm2java
 */
@Entity
@Table(name = "view_routeseta", schema = "dbo", catalog = "FMS4.0")
public class ViewRouteseta implements java.io.Serializable {

	private ViewRoutesetaId id;

	public ViewRouteseta() {
	}

	public ViewRouteseta(ViewRoutesetaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "routeName", column = @Column(name = "RouteName")),
			@AttributeOverride(name = "wayPointName", column = @Column(name = "WayPointName", length = 80)),
			@AttributeOverride(name = "sequenceOrder", column = @Column(name = "SequenceOrder", nullable = false)) })
	public ViewRoutesetaId getId() {
		return this.id;
	}

	public void setId(ViewRoutesetaId id) {
		this.id = id;
	}

}
