package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewGroup generated by hbm2java
 */
@Entity
@Table(name = "view_Group", schema = "dbo", catalog = "FMS4.0")
public class ViewGroup implements java.io.Serializable {

	private ViewGroupId id;

	public ViewGroup() {
	}

	public ViewGroup(ViewGroupId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "depotId", column = @Column(name = "depot_id", nullable = false)),
			@AttributeOverride(name = "depotName", column = @Column(name = "depot_name")),
			@AttributeOverride(name = "fenceGeom", column = @Column(name = "fence_geom")) })
	public ViewGroupId getId() {
		return this.id;
	}

	public void setId(ViewGroupId id) {
		this.id = id;
	}

}
