package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewBusstopAll generated by hbm2java
 */
@Entity
@Table(name = "view_busstop_all", schema = "dbo", catalog = "FMS4.0")
public class ViewBusstopAll implements java.io.Serializable {

	private ViewBusstopAllId id;

	public ViewBusstopAll() {
	}

	public ViewBusstopAll(ViewBusstopAllId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "agency", column = @Column(name = "AGENCY")),
			@AttributeOverride(name = "gpsId", column = @Column(name = "GPS_ID")),
			@AttributeOverride(name = "idDtc", column = @Column(name = "ID_DTC")),
			@AttributeOverride(name = "uniqId", column = @Column(name = "UNIQ_ID")),
			@AttributeOverride(name = "idDmts", column = @Column(name = "ID_DMTS")),
			@AttributeOverride(name = "stopName", column = @Column(name = "STOP_NAME")),
			@AttributeOverride(name = "altName", column = @Column(name = "ALT_NAME")),
			@AttributeOverride(name = "startEnd", column = @Column(name = "START_END")),
			@AttributeOverride(name = "endTime", column = @Column(name = "END_TIME")),
			@AttributeOverride(name = "side", column = @Column(name = "SIDE")),
			@AttributeOverride(name = "fareStage", column = @Column(name = "FARE_STAGE")),
			@AttributeOverride(name = "x", column = @Column(name = "X", precision = 53, scale = 0)),
			@AttributeOverride(name = "y", column = @Column(name = "Y", precision = 53, scale = 0)),
			@AttributeOverride(name = "city", column = @Column(name = "CITY")),
			@AttributeOverride(name = "state", column = @Column(name = "STATE")) })
	public ViewBusstopAllId getId() {
		return this.id;
	}

	public void setId(ViewBusstopAllId id) {
		this.id = id;
	}

}
