package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewNamedRouteBusstopsId generated by hbm2java
 */
@Embeddable
public class ViewNamedRouteBusstopsId implements java.io.Serializable {

	private Serializable routeNumber;
	private Serializable stopId;
	private int id;
	private int indx;
	private Integer distance;
	private Integer distanceFromOrigin;

	public ViewNamedRouteBusstopsId() {
	}

	public ViewNamedRouteBusstopsId(Serializable routeNumber, Serializable stopId, int id, int indx) {
		this.routeNumber = routeNumber;
		this.stopId = stopId;
		this.id = id;
		this.indx = indx;
	}

	public ViewNamedRouteBusstopsId(Serializable routeNumber, Serializable stopId, int id, int indx, Integer distance,
			Integer distanceFromOrigin) {
		this.routeNumber = routeNumber;
		this.stopId = stopId;
		this.id = id;
		this.indx = indx;
		this.distance = distance;
		this.distanceFromOrigin = distanceFromOrigin;
	}

	@Column(name = "route_number", nullable = false)
	public Serializable getRouteNumber() {
		return this.routeNumber;
	}

	public void setRouteNumber(Serializable routeNumber) {
		this.routeNumber = routeNumber;
	}

	@Column(name = "stop_id", nullable = false)
	public Serializable getStopId() {
		return this.stopId;
	}

	public void setStopId(Serializable stopId) {
		this.stopId = stopId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "indx", nullable = false)
	public int getIndx() {
		return this.indx;
	}

	public void setIndx(int indx) {
		this.indx = indx;
	}

	@Column(name = "distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "DISTANCE_FROM_ORIGIN")
	public Integer getDistanceFromOrigin() {
		return this.distanceFromOrigin;
	}

	public void setDistanceFromOrigin(Integer distanceFromOrigin) {
		this.distanceFromOrigin = distanceFromOrigin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewNamedRouteBusstopsId))
			return false;
		ViewNamedRouteBusstopsId castOther = (ViewNamedRouteBusstopsId) other;

		return ((this.getRouteNumber() == castOther.getRouteNumber()) || (this.getRouteNumber() != null
				&& castOther.getRouteNumber() != null && this.getRouteNumber().equals(castOther.getRouteNumber())))
				&& ((this.getStopId() == castOther.getStopId()) || (this.getStopId() != null
						&& castOther.getStopId() != null && this.getStopId().equals(castOther.getStopId())))
				&& (this.getId() == castOther.getId()) && (this.getIndx() == castOther.getIndx())
				&& ((this.getDistance() == castOther.getDistance()) || (this.getDistance() != null
						&& castOther.getDistance() != null && this.getDistance().equals(castOther.getDistance())))
				&& ((this.getDistanceFromOrigin() == castOther.getDistanceFromOrigin())
						|| (this.getDistanceFromOrigin() != null && castOther.getDistanceFromOrigin() != null
								&& this.getDistanceFromOrigin().equals(castOther.getDistanceFromOrigin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRouteNumber() == null ? 0 : this.getRouteNumber().hashCode());
		result = 37 * result + (getStopId() == null ? 0 : this.getStopId().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + this.getIndx();
		result = 37 * result + (getDistance() == null ? 0 : this.getDistance().hashCode());
		result = 37 * result + (getDistanceFromOrigin() == null ? 0 : this.getDistanceFromOrigin().hashCode());
		return result;
	}

}
