package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewAlertlog generated by hbm2java
 */
@Entity
@Table(name = "view_alertlog", schema = "dbo", catalog = "FMS4.0")
public class ViewAlertlog implements java.io.Serializable {

	private ViewAlertlogId id;

	public ViewAlertlog() {
	}

	public ViewAlertlog(ViewAlertlogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "vehicleno", column = @Column(name = "Vehicleno", length = 50)),
			@AttributeOverride(name = "lat", column = @Column(name = "lat", precision = 53, scale = 0)),
			@AttributeOverride(name = "long_", column = @Column(name = "long", precision = 53, scale = 0)),
			@AttributeOverride(name = "speed", column = @Column(name = "speed", precision = 53, scale = 0)),
			@AttributeOverride(name = "datetime", column = @Column(name = "datetime", length = 23)),
			@AttributeOverride(name = "wayPointName", column = @Column(name = "WayPointName", length = 50)),
			@AttributeOverride(name = "groupid", column = @Column(name = "Groupid")),
			@AttributeOverride(name = "alerttype", column = @Column(name = "alerttype")),
			@AttributeOverride(name = "fleetid", column = @Column(name = "fleetid")),
			@AttributeOverride(name = "odometerReading", column = @Column(name = "odometerReading", precision = 53, scale = 0)),
			@AttributeOverride(name = "probableroutes", column = @Column(name = "Probableroutes", length = 200)),
			@AttributeOverride(name = "routeName", column = @Column(name = "RouteName", length = 50)),
			@AttributeOverride(name = "actualDateTime", column = @Column(name = "ActualDateTime", length = 23)) })
	public ViewAlertlogId getId() {
		return this.id;
	}

	public void setId(ViewAlertlogId id) {
		this.id = id;
	}

}
