package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewUserLocationCurrentId generated by hbm2java
 */
@Embeddable
public class ViewUserLocationCurrentId implements java.io.Serializable {

	private String msid;
	private double latitude;
	private double longitude;
	private Date dateTime;
	private Double speed;
	private Double direction;
	private Long ignition;
	private Serializable imei;
	private Double odometer;
	private Double gpsDistace;
	private Double fuel;
	private Serializable vehicleid;
	private Serializable reversegeocode;
	private Serializable analog;
	private Serializable deviceName;
	private Serializable batteryPercentage;

	public ViewUserLocationCurrentId() {
	}

	public ViewUserLocationCurrentId(String msid, double latitude, double longitude, Date dateTime, Serializable imei,
			Serializable vehicleid) {
		this.msid = msid;
		this.latitude = latitude;
		this.longitude = longitude;
		this.dateTime = dateTime;
		this.imei = imei;
		this.vehicleid = vehicleid;
	}

	public ViewUserLocationCurrentId(String msid, double latitude, double longitude, Date dateTime, Double speed,
			Double direction, Long ignition, Serializable imei, Double odometer, Double gpsDistace, Double fuel,
			Serializable vehicleid, Serializable reversegeocode, Serializable analog, Serializable deviceName,
			Serializable batteryPercentage) {
		this.msid = msid;
		this.latitude = latitude;
		this.longitude = longitude;
		this.dateTime = dateTime;
		this.speed = speed;
		this.direction = direction;
		this.ignition = ignition;
		this.imei = imei;
		this.odometer = odometer;
		this.gpsDistace = gpsDistace;
		this.fuel = fuel;
		this.vehicleid = vehicleid;
		this.reversegeocode = reversegeocode;
		this.analog = analog;
		this.deviceName = deviceName;
		this.batteryPercentage = batteryPercentage;
	}

	@Column(name = "msid", nullable = false, length = 20)
	public String getMsid() {
		return this.msid;
	}

	public void setMsid(String msid) {
		this.msid = msid;
	}

	@Column(name = "Latitude", nullable = false, precision = 53, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", nullable = false, precision = 53, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "DateTime", nullable = false, length = 23)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Column(name = "direction", precision = 53, scale = 0)
	public Double getDirection() {
		return this.direction;
	}

	public void setDirection(Double direction) {
		this.direction = direction;
	}

	@Column(name = "Ignition", precision = 10, scale = 0)
	public Long getIgnition() {
		return this.ignition;
	}

	public void setIgnition(Long ignition) {
		this.ignition = ignition;
	}

	@Column(name = "imei", nullable = false)
	public Serializable getImei() {
		return this.imei;
	}

	public void setImei(Serializable imei) {
		this.imei = imei;
	}

	@Column(name = "odometer", precision = 53, scale = 0)
	public Double getOdometer() {
		return this.odometer;
	}

	public void setOdometer(Double odometer) {
		this.odometer = odometer;
	}

	@Column(name = "gps_distace", precision = 53, scale = 0)
	public Double getGpsDistace() {
		return this.gpsDistace;
	}

	public void setGpsDistace(Double gpsDistace) {
		this.gpsDistace = gpsDistace;
	}

	@Column(name = "fuel", precision = 53, scale = 0)
	public Double getFuel() {
		return this.fuel;
	}

	public void setFuel(Double fuel) {
		this.fuel = fuel;
	}

	@Column(name = "vehicleid", nullable = false)
	public Serializable getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(Serializable vehicleid) {
		this.vehicleid = vehicleid;
	}

	@Column(name = "reversegeocode")
	public Serializable getReversegeocode() {
		return this.reversegeocode;
	}

	public void setReversegeocode(Serializable reversegeocode) {
		this.reversegeocode = reversegeocode;
	}

	@Column(name = "Analog")
	public Serializable getAnalog() {
		return this.analog;
	}

	public void setAnalog(Serializable analog) {
		this.analog = analog;
	}

	@Column(name = "DeviceName")
	public Serializable getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(Serializable deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "BatteryPercentage")
	public Serializable getBatteryPercentage() {
		return this.batteryPercentage;
	}

	public void setBatteryPercentage(Serializable batteryPercentage) {
		this.batteryPercentage = batteryPercentage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewUserLocationCurrentId))
			return false;
		ViewUserLocationCurrentId castOther = (ViewUserLocationCurrentId) other;

		return ((this.getMsid() == castOther.getMsid()) || (this.getMsid() != null && castOther.getMsid() != null
				&& this.getMsid().equals(castOther.getMsid()))) && (this.getLatitude() == castOther.getLatitude())
				&& (this.getLongitude() == castOther.getLongitude())
				&& ((this.getDateTime() == castOther.getDateTime()) || (this.getDateTime() != null
						&& castOther.getDateTime() != null && this.getDateTime().equals(castOther.getDateTime())))
				&& ((this.getSpeed() == castOther.getSpeed()) || (this.getSpeed() != null
						&& castOther.getSpeed() != null && this.getSpeed().equals(castOther.getSpeed())))
				&& ((this.getDirection() == castOther.getDirection()) || (this.getDirection() != null
						&& castOther.getDirection() != null && this.getDirection().equals(castOther.getDirection())))
				&& ((this.getIgnition() == castOther.getIgnition()) || (this.getIgnition() != null
						&& castOther.getIgnition() != null && this.getIgnition().equals(castOther.getIgnition())))
				&& ((this.getImei() == castOther.getImei()) || (this.getImei() != null && castOther.getImei() != null
						&& this.getImei().equals(castOther.getImei())))
				&& ((this.getOdometer() == castOther.getOdometer()) || (this.getOdometer() != null
						&& castOther.getOdometer() != null && this.getOdometer().equals(castOther.getOdometer())))
				&& ((this.getGpsDistace() == castOther.getGpsDistace()) || (this.getGpsDistace() != null
						&& castOther.getGpsDistace() != null && this.getGpsDistace().equals(castOther.getGpsDistace())))
				&& ((this.getFuel() == castOther.getFuel()) || (this.getFuel() != null && castOther.getFuel() != null
						&& this.getFuel().equals(castOther.getFuel())))
				&& ((this.getVehicleid() == castOther.getVehicleid()) || (this.getVehicleid() != null
						&& castOther.getVehicleid() != null && this.getVehicleid().equals(castOther.getVehicleid())))
				&& ((this.getReversegeocode() == castOther.getReversegeocode())
						|| (this.getReversegeocode() != null && castOther.getReversegeocode() != null
								&& this.getReversegeocode().equals(castOther.getReversegeocode())))
				&& ((this.getAnalog() == castOther.getAnalog()) || (this.getAnalog() != null
						&& castOther.getAnalog() != null && this.getAnalog().equals(castOther.getAnalog())))
				&& ((this.getDeviceName() == castOther.getDeviceName()) || (this.getDeviceName() != null
						&& castOther.getDeviceName() != null && this.getDeviceName().equals(castOther.getDeviceName())))
				&& ((this.getBatteryPercentage() == castOther.getBatteryPercentage())
						|| (this.getBatteryPercentage() != null && castOther.getBatteryPercentage() != null
								&& this.getBatteryPercentage().equals(castOther.getBatteryPercentage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMsid() == null ? 0 : this.getMsid().hashCode());
		result = 37 * result + (int) this.getLatitude();
		result = 37 * result + (int) this.getLongitude();
		result = 37 * result + (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		result = 37 * result + (getSpeed() == null ? 0 : this.getSpeed().hashCode());
		result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
		result = 37 * result + (getIgnition() == null ? 0 : this.getIgnition().hashCode());
		result = 37 * result + (getImei() == null ? 0 : this.getImei().hashCode());
		result = 37 * result + (getOdometer() == null ? 0 : this.getOdometer().hashCode());
		result = 37 * result + (getGpsDistace() == null ? 0 : this.getGpsDistace().hashCode());
		result = 37 * result + (getFuel() == null ? 0 : this.getFuel().hashCode());
		result = 37 * result + (getVehicleid() == null ? 0 : this.getVehicleid().hashCode());
		result = 37 * result + (getReversegeocode() == null ? 0 : this.getReversegeocode().hashCode());
		result = 37 * result + (getAnalog() == null ? 0 : this.getAnalog().hashCode());
		result = 37 * result + (getDeviceName() == null ? 0 : this.getDeviceName().hashCode());
		result = 37 * result + (getBatteryPercentage() == null ? 0 : this.getBatteryPercentage().hashCode());
		return result;
	}

}
