package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewUserLocationHistoryId generated by hbm2java
 */
@Embeddable
public class ViewUserLocationHistoryId implements java.io.Serializable {

	private double lat;
	private double lon;
	private Date timestamp;
	private Double speed;
	private Double direction;
	private long locationType;
	private Double odometer;
	private Double gpsDistace;
	private Double fuel;
	private Serializable userid;
	private Serializable reversegeocode;
	private String msid;
	private Serializable multiValue1;
	private Date createddatetime;
	private byte[] binarycontent;

	public ViewUserLocationHistoryId() {
	}

	public ViewUserLocationHistoryId(double lat, double lon, Date timestamp, long locationType, Serializable userid,
			String msid) {
		this.lat = lat;
		this.lon = lon;
		this.timestamp = timestamp;
		this.locationType = locationType;
		this.userid = userid;
		this.msid = msid;
	}

	public ViewUserLocationHistoryId(double lat, double lon, Date timestamp, Double speed, Double direction,
			long locationType, Double odometer, Double gpsDistace, Double fuel, Serializable userid,
			Serializable reversegeocode, String msid, Serializable multiValue1, Date createddatetime,
			byte[] binarycontent) {
		this.lat = lat;
		this.lon = lon;
		this.timestamp = timestamp;
		this.speed = speed;
		this.direction = direction;
		this.locationType = locationType;
		this.odometer = odometer;
		this.gpsDistace = gpsDistace;
		this.fuel = fuel;
		this.userid = userid;
		this.reversegeocode = reversegeocode;
		this.msid = msid;
		this.multiValue1 = multiValue1;
		this.createddatetime = createddatetime;
		this.binarycontent = binarycontent;
	}

	@Column(name = "lat", nullable = false, precision = 53, scale = 0)
	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	@Column(name = "lon", nullable = false, precision = 53, scale = 0)
	public double getLon() {
		return this.lon;
	}

	public void setLon(double lon) {
		this.lon = lon;
	}

	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Column(name = "direction", precision = 53, scale = 0)
	public Double getDirection() {
		return this.direction;
	}

	public void setDirection(Double direction) {
		this.direction = direction;
	}

	@Column(name = "location_type", nullable = false, precision = 10, scale = 0)
	public long getLocationType() {
		return this.locationType;
	}

	public void setLocationType(long locationType) {
		this.locationType = locationType;
	}

	@Column(name = "odometer", precision = 53, scale = 0)
	public Double getOdometer() {
		return this.odometer;
	}

	public void setOdometer(Double odometer) {
		this.odometer = odometer;
	}

	@Column(name = "gps_distace", precision = 53, scale = 0)
	public Double getGpsDistace() {
		return this.gpsDistace;
	}

	public void setGpsDistace(Double gpsDistace) {
		this.gpsDistace = gpsDistace;
	}

	@Column(name = "fuel", precision = 53, scale = 0)
	public Double getFuel() {
		return this.fuel;
	}

	public void setFuel(Double fuel) {
		this.fuel = fuel;
	}

	@Column(name = "userid", nullable = false)
	public Serializable getUserid() {
		return this.userid;
	}

	public void setUserid(Serializable userid) {
		this.userid = userid;
	}

	@Column(name = "reversegeocode")
	public Serializable getReversegeocode() {
		return this.reversegeocode;
	}

	public void setReversegeocode(Serializable reversegeocode) {
		this.reversegeocode = reversegeocode;
	}

	@Column(name = "msid", nullable = false, length = 20)
	public String getMsid() {
		return this.msid;
	}

	public void setMsid(String msid) {
		this.msid = msid;
	}

	@Column(name = "multi_value1")
	public Serializable getMultiValue1() {
		return this.multiValue1;
	}

	public void setMultiValue1(Serializable multiValue1) {
		this.multiValue1 = multiValue1;
	}

	@Column(name = "createddatetime", length = 23)
	public Date getCreateddatetime() {
		return this.createddatetime;
	}

	public void setCreateddatetime(Date createddatetime) {
		this.createddatetime = createddatetime;
	}

	@Column(name = "binarycontent")
	public byte[] getBinarycontent() {
		return this.binarycontent;
	}

	public void setBinarycontent(byte[] binarycontent) {
		this.binarycontent = binarycontent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewUserLocationHistoryId))
			return false;
		ViewUserLocationHistoryId castOther = (ViewUserLocationHistoryId) other;

		return (this.getLat() == castOther.getLat()) && (this.getLon() == castOther.getLon())
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
						&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getSpeed() == castOther.getSpeed()) || (this.getSpeed() != null
						&& castOther.getSpeed() != null && this.getSpeed().equals(castOther.getSpeed())))
				&& ((this.getDirection() == castOther.getDirection()) || (this.getDirection() != null
						&& castOther.getDirection() != null && this.getDirection().equals(castOther.getDirection())))
				&& (this.getLocationType() == castOther.getLocationType())
				&& ((this.getOdometer() == castOther.getOdometer()) || (this.getOdometer() != null
						&& castOther.getOdometer() != null && this.getOdometer().equals(castOther.getOdometer())))
				&& ((this.getGpsDistace() == castOther.getGpsDistace()) || (this.getGpsDistace() != null
						&& castOther.getGpsDistace() != null && this.getGpsDistace().equals(castOther.getGpsDistace())))
				&& ((this.getFuel() == castOther.getFuel()) || (this.getFuel() != null && castOther.getFuel() != null
						&& this.getFuel().equals(castOther.getFuel())))
				&& ((this.getUserid() == castOther.getUserid()) || (this.getUserid() != null
						&& castOther.getUserid() != null && this.getUserid().equals(castOther.getUserid())))
				&& ((this.getReversegeocode() == castOther.getReversegeocode())
						|| (this.getReversegeocode() != null && castOther.getReversegeocode() != null
								&& this.getReversegeocode().equals(castOther.getReversegeocode())))
				&& ((this.getMsid() == castOther.getMsid()) || (this.getMsid() != null && castOther.getMsid() != null
						&& this.getMsid().equals(castOther.getMsid())))
				&& ((this.getMultiValue1() == castOther.getMultiValue1())
						|| (this.getMultiValue1() != null && castOther.getMultiValue1() != null
								&& this.getMultiValue1().equals(castOther.getMultiValue1())))
				&& ((this.getCreateddatetime() == castOther.getCreateddatetime())
						|| (this.getCreateddatetime() != null && castOther.getCreateddatetime() != null
								&& this.getCreateddatetime().equals(castOther.getCreateddatetime())))
				&& ((this.getBinarycontent() == castOther.getBinarycontent())
						|| (this.getBinarycontent() != null && castOther.getBinarycontent() != null
								&& Arrays.equals(this.getBinarycontent(), castOther.getBinarycontent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLat();
		result = 37 * result + (int) this.getLon();
		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result + (getSpeed() == null ? 0 : this.getSpeed().hashCode());
		result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
		result = 37 * result + (int) this.getLocationType();
		result = 37 * result + (getOdometer() == null ? 0 : this.getOdometer().hashCode());
		result = 37 * result + (getGpsDistace() == null ? 0 : this.getGpsDistace().hashCode());
		result = 37 * result + (getFuel() == null ? 0 : this.getFuel().hashCode());
		result = 37 * result + (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result + (getReversegeocode() == null ? 0 : this.getReversegeocode().hashCode());
		result = 37 * result + (getMsid() == null ? 0 : this.getMsid().hashCode());
		result = 37 * result + (getMultiValue1() == null ? 0 : this.getMultiValue1().hashCode());
		result = 37 * result + (getCreateddatetime() == null ? 0 : this.getCreateddatetime().hashCode());
		result = 37 * result + (getBinarycontent() == null ? 0 : Arrays.hashCode(this.getBinarycontent()));
		return result;
	}

}
