package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewRoutesetaId generated by hbm2java
 */
@Embeddable
public class ViewRoutesetaId implements java.io.Serializable {

	private Serializable routeName;
	private String wayPointName;
	private int sequenceOrder;

	public ViewRoutesetaId() {
	}

	public ViewRoutesetaId(int sequenceOrder) {
		this.sequenceOrder = sequenceOrder;
	}

	public ViewRoutesetaId(Serializable routeName, String wayPointName, int sequenceOrder) {
		this.routeName = routeName;
		this.wayPointName = wayPointName;
		this.sequenceOrder = sequenceOrder;
	}

	@Column(name = "RouteName")
	public Serializable getRouteName() {
		return this.routeName;
	}

	public void setRouteName(Serializable routeName) {
		this.routeName = routeName;
	}

	@Column(name = "WayPointName", length = 80)
	public String getWayPointName() {
		return this.wayPointName;
	}

	public void setWayPointName(String wayPointName) {
		this.wayPointName = wayPointName;
	}

	@Column(name = "SequenceOrder", nullable = false)
	public int getSequenceOrder() {
		return this.sequenceOrder;
	}

	public void setSequenceOrder(int sequenceOrder) {
		this.sequenceOrder = sequenceOrder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRoutesetaId))
			return false;
		ViewRoutesetaId castOther = (ViewRoutesetaId) other;

		return ((this.getRouteName() == castOther.getRouteName()) || (this.getRouteName() != null
				&& castOther.getRouteName() != null && this.getRouteName().equals(castOther.getRouteName())))
				&& ((this.getWayPointName() == castOther.getWayPointName())
						|| (this.getWayPointName() != null && castOther.getWayPointName() != null
								&& this.getWayPointName().equals(castOther.getWayPointName())))
				&& (this.getSequenceOrder() == castOther.getSequenceOrder());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRouteName() == null ? 0 : this.getRouteName().hashCode());
		result = 37 * result + (getWayPointName() == null ? 0 : this.getWayPointName().hashCode());
		result = 37 * result + this.getSequenceOrder();
		return result;
	}

}
