package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WayPoints generated by hbm2java
 */
@Entity
@Table(name = "WayPoints", schema = "dbo", catalog = "FMS4.0")
public class WayPoints implements java.io.Serializable {

	private int id;
	private String wayPointName;
	private Serializable vehicleStopType;
	private String locationName;
	private Double latitude;
	private Double longitude;
	private String createdBy;
	private Date createOn;
	private String modifiedBy;
	private Date modifiedOn;
	private boolean isDeleted;
	private Serializable wayPointId;
	private Integer companyId;
	private Integer groupId;
	private Integer radius;
	private Serializable color;
	private Serializable waypointType;

	public WayPoints() {
	}

	public WayPoints(int id, Date createOn, boolean isDeleted) {
		this.id = id;
		this.createOn = createOn;
		this.isDeleted = isDeleted;
	}

	public WayPoints(int id, String wayPointName, Serializable vehicleStopType, String locationName, Double latitude,
			Double longitude, String createdBy, Date createOn, String modifiedBy, Date modifiedOn, boolean isDeleted,
			Serializable wayPointId, Integer companyId, Integer groupId, Integer radius, Serializable color,
			Serializable waypointType) {
		this.id = id;
		this.wayPointName = wayPointName;
		this.vehicleStopType = vehicleStopType;
		this.locationName = locationName;
		this.latitude = latitude;
		this.longitude = longitude;
		this.createdBy = createdBy;
		this.createOn = createOn;
		this.modifiedBy = modifiedBy;
		this.modifiedOn = modifiedOn;
		this.isDeleted = isDeleted;
		this.wayPointId = wayPointId;
		this.companyId = companyId;
		this.groupId = groupId;
		this.radius = radius;
		this.color = color;
		this.waypointType = waypointType;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "WayPointName", length = 80)
	public String getWayPointName() {
		return this.wayPointName;
	}

	public void setWayPointName(String wayPointName) {
		this.wayPointName = wayPointName;
	}

	@Column(name = "VehicleStopType")
	public Serializable getVehicleStopType() {
		return this.vehicleStopType;
	}

	public void setVehicleStopType(Serializable vehicleStopType) {
		this.vehicleStopType = vehicleStopType;
	}

	@Column(name = "LocationName", length = 50)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "CreatedBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createOn", nullable = false, length = 23)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedOn", length = 23)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "isDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "WayPointID")
	public Serializable getWayPointId() {
		return this.wayPointId;
	}

	public void setWayPointId(Serializable wayPointId) {
		this.wayPointId = wayPointId;
	}

	@Column(name = "CompanyID")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "GroupID")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "Radius")
	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	@Column(name = "Color")
	public Serializable getColor() {
		return this.color;
	}

	public void setColor(Serializable color) {
		this.color = color;
	}

	@Column(name = "WaypointType")
	public Serializable getWaypointType() {
		return this.waypointType;
	}

	public void setWaypointType(Serializable waypointType) {
		this.waypointType = waypointType;
	}

}
