package com.example.demo.datasource.sqlserver.domain;
// Generated Sep 8, 2017 3:06:00 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XmlwithOpenXml generated by hbm2java
 */
@Entity
@Table(name = "XMLwithOpenXML", schema = "dbo", catalog = "FMS4.0")
public class XmlwithOpenXml implements java.io.Serializable {

	private int id;
	private Serializable xmldata;
	private Date loadedDateTime;

	public XmlwithOpenXml() {
	}

	public XmlwithOpenXml(int id) {
		this.id = id;
	}

	public XmlwithOpenXml(int id, Serializable xmldata, Date loadedDateTime) {
		this.id = id;
		this.xmldata = xmldata;
		this.loadedDateTime = loadedDateTime;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "XMLData")
	public Serializable getXmldata() {
		return this.xmldata;
	}

	public void setXmldata(Serializable xmldata) {
		this.xmldata = xmldata;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LoadedDateTime", length = 23)
	public Date getLoadedDateTime() {
		return this.loadedDateTime;
	}

	public void setLoadedDateTime(Date loadedDateTime) {
		this.loadedDateTime = loadedDateTime;
	}

}
